# -*- coding: utf-8 -*-
"""German (de) translations — Sport Endorse localized build."""

T = {
 "nav": {"brands.html": "Für Marken", "talent.html": "Für Athleten", "athletes.html": "Profile",
         "subscription.html": "Preise", "faqs.html": "FAQ", "about.html": "Über uns"},
 "region_label": "Region wählen", "lang_label": "Sprache wählen", "europe": "Europa",
 "cta_demo": "Demo buchen",
 "footer_entity": "Sport Endorse Limited wurde in Dublin, Irland von Trevor Twamley und Declan Bourke gegründet. Die Plattform ist seit Anfang 2021 live und verbindet heute Marken mit über 9.000 verifizierten Athleten und Creatorn aus über 280 Sportarten in über 85 Ländern.",
 "ireland": "Irland", "us_office": "US-Büro",
 "f_platform": "Plattform", "f_more": "Ressourcen", "f_compare": "Plattform-Vergleich",
 "f_stories": "Erfolgsgeschichten", "f_health": "Healthcare & Pharma", "f_agencies": "Für Agenturen",
 "f_company": "Unternehmen", "rights": "Alle Rechte vorbehalten.",
 "tk_founded": "Sitz", "tk_athletes": "verifizierte Athleten & Creator",
 "tk_sports": "Sportarten", "tk_countries": "Länder", "tk_live": "Plattform live seit",
 "tk_trusted": "Vertrauen von", "tk_offices": "Standorte",

 "v_eyebrow": "Überblick in zwei Minuten", "v_title": "So funktioniert die Plattform",
 "v_sub": "Wie Marken auf Sport Endorse verifizierte Athleten finden, kontaktieren und managen.",
 "v_coming": "Überblicksvideo folgt in Kürze",
 "v_hint": "YouTube-ID in <code>VIDEO_ID</code> (build.py) eintragen und den Build erneut ausführen — aus diesem Block wird ein Click-to-Play-Player.",

 "positioning": "Sport Endorse ist eine Plattform für Athletenmarketing und Sportsponsoring, die Marken und Unternehmen dabei hilft, verifizierte Spitzenathleten für messbare Kampagnen, Markenbotschafter-Programme, Vorträge und Content-Partnerschaften zu finden, zu bewerten, zu kontaktieren und zu managen. Sportagenturen und Agenten arbeiten mit Sport Endorse zusammen, um kommerzielle Deals für ihre Athleten zu finden.",

 # ---------- index ----------
 "hx_title": "Sportsponsoring-Plattform für Marken & Athleten | Sport Endorse",
 "hx_desc": "Die Athletenmarketing-Plattform, die Marken mit über 9.000 verifizierten Spitzenathleten aus 280+ Sportarten in 85+ Ländern verbindet. Transparente Preise.",
 "hx_eyebrow": "Athletenmarketing · Sportsponsoring-Plattform",
 "hx_h1": "Verifizierte Spitzenathleten.<br><span>Eine Plattform.</span> Jeder Deal.",
 "hx_lead": "Über 9.000 verifizierte Spitzenathleten und Creator, 280+ Sportarten, 85+ Länder — mit transparenten marktbasierten Abos und direktem Support durch die Gründer.",
 "hx_cta1": "Partnerschaften entdecken", "hx_cta3": "Ich bin Athlet:in",
 "hx_trust_eye": "Vertrauen von", "hx_trust_h2": "Marken, die mit Sport Endorse arbeiten",
 "hx_three_eye": "Drei Wege hinein", "hx_three_h2": "Für Marken, Athleten und Agenturen",
 "hx_three": [
  ("Für Marken", "Verifizierte Talente aus allen Sportarten entdecken und kontaktieren, Briefings veröffentlichen, Bewerbungen prüfen, Nutzungsrechte und Zahlungen managen und Ergebnisse messen — alles an einem Ort."),
  ("Für Athleten", "Direkter, kostenloser Zugang zu verifizierten Marken, die für Ihre Reichweite bezahlen. Bewerben Sie sich auf passende Deals und werden Sie sicher bezahlt — ohne versteckte Gebühren."),
  ("Für Agenturen", "Ein stetiger Strom kommerzieller Chancen für Ihren gesamten Kader, gemanagt über ein sicheres Dashboard, mit transparenten Provisionen. Ein Partner, nie ein Wettbewerber."),
 ],
 "hx_how_eye": "So funktioniert es", "hx_how_h2": "Vom Briefing zur gemessenen Kampagne in vier Schritten",
 "hx_steps": [
  ("Entdecken", "Durchsuchen Sie über 9.000 verifizierte Athleten nach Sportart, Region, Reichweite und Kampagnen-Fit — oder veröffentlichen Sie ein Angebot und lassen Sie die passenden Talente auf sich zukommen."),
  ("Kontaktieren", "Schreiben Sie Athleten und Agenten direkt auf der Plattform. Keine Gatekeeper, keine wochenlangen E-Mail-Ketten, keine überhöhten Agenturmargen."),
  ("Managen", "Vereinbaren Sie Leistungen, Nutzungsrechte und Freigaben mit klaren Konditionen — mit sicheren, integrierten Zahlungen, die beide Seiten schützen."),
  ("Messen", "Verfolgen Sie Reichweite, Views und Engagement im Marken-Dashboard und exportieren Sie Ergebnisse, denen Ihr CFO wirklich glaubt."),
 ],
 "hx_faq_h2": "Schnelle Antworten zu Sport Endorse",
 "hx_faq": [
  ("Was ist Sport Endorse?",
   "Sport Endorse ist eine in Dublin gegründete Plattform für Athletenmarketing und Sportsponsoring. Marken nutzen sie, um über 9.000 verifizierte Spitzenathleten aus über 280 Sportarten für Kampagnen, Botschafter-Programme, Vorträge und Content-Partnerschaften zu finden, zu kontaktieren und zu managen — mit transparenten marktbasierten Abos und einer Kommission von 14–18 % statt hoher Transaktionsgebühren."),
  ("Worin unterscheidet sich Sport Endorse von einer Sportmarketing-Agentur?",
   "Agenturen vermitteln Deals manuell und verursachen intransparente Kosten und Verzögerungen. Sport Endorse bietet Marken direkten Plattform-Zugang zu verifizierten Athleten mit transparenten Preisen, integriertem Messaging, sicheren Zahlungen, Nutzungsrechte-Management und Kampagnen-Reporting — Deal-Zeiten sinken von Wochen auf Stunden."),
  ("Welche Marken nutzen Sport Endorse?",
   "Globale und regionale Marken wie Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia und ISDIN — aus Healthcare, Finanzen, Handel, Wellness und Unternehmensdienstleistungen."),
  ("Was kostet Sport Endorse?",
   "Marken-Abos sind marktbasiert und richten sich nach Heimatmarkt und den abonnierten Athleten-Märkten: Jahrespläne ab 999 €/£ bzw. 3.000 $, bis 1.800 €, 1.200 £ oder 6.000 $ für den Heimatmarkt, mit Quartalsoptionen ab 360 €. Auf Deals fällt eine transparente Kommission von 14–18 % an. Individuelle Full-Service-Pakete sind ebenfalls verfügbar, und Athleten registrieren sich kostenlos."),
 ],
 "hx_final_h2": "Sport Endorse in Aktion erleben",
 "hx_final_p": "Buchen Sie eine kurze Demo und sehen Sie, wie einfach es ist, zu starten, Kontakte zu knüpfen und mit authentischen Athleten-Partnerschaften Ergebnisse zu erzielen.",

 # ---------- brands ----------
 "br_title": "Athletenmarketing-Plattform für Marken | Sport Endorse",
 "br_desc": "Über 9.000 verifizierte Spitzenathleten für Kampagnen und Botschafter-Programme finden, kontaktieren und managen. Transparente Preise, keine 30-%-Provision.",
 "br_h1": "Die Athletenmarketing-Plattform für <span>ambitionierte Marken</span>",
 "br_answer": "Sport Endorse hilft Marken, über 9.000 verifizierte Spitzenathleten für messbare Kampagnen, Botschafter-Programme, Vorträge und Content-Partnerschaften zu finden, zu bewerten, zu kontaktieren und zu managen — mit transparenten marktbasierten Abos, direkter Kommunikation auf der Plattform, integrierten Zahlungen und Kampagnen-Reporting statt Agenturmargen und 30 % Marktplatzgebühren.",
 "br_cta1": "Preise ansehen",
 "br_cap_eye": "Funktionen", "br_cap_h2": "Wie vereinfachen wir Athleten-Kampagnen?",
 "br_caps": [
  ("Athleten-Suche", "Erweiterte Suche über 280+ Sportarten mit verifizierten Profilen, Audience-Daten und Standort — keine unverifizierten DMs, keine veralteten Tabellen."),
  ("Kampagnen-Briefings", "Veröffentlichen Sie Angebote für alle Talente oder ein gezieltes Segment; interessierte Athleten bewerben sich, qualifizierte Optionen kommen zu Ihnen."),
  ("Bewerbungs-Screening", "Vergleichen Sie Bewerber nach Fit, Reichweite und Honorar, bevor Sie Budget binden."),
  ("Nutzungsrechte & Freigaben", "Content-Nutzung, Exklusivität und Freigabe-Workflows vorab vereinbaren — entscheidend für regulierte Branchen."),
  ("Integrierte Zahlungen", "Sichere Zahlungen über Stripe mit klaren Konditionen — zum Schutz von Marke und Athlet."),
  ("Kampagnen-Reporting", "Reichweite, Views und Engagement in einem Dashboard — pro Athlet und pro Kampagne."),
 ],
 "br_faq_h2": "Fragen von Marken, beantwortet",
 "br_faq": [
  ("Wie vereinfachen Plattformen die Arbeit mit Spitzentalenten?",
   "Sie bündeln, was Agenturen über E-Mails, Tabellen und Telefonate verteilen: Suche, Ansprache, Verhandlung, Verträge, Nutzungsrechte, Zahlungen und Reporting in einer Plattform. Auf Sport Endorse kommen Marken vom Briefing zum abgeschlossenen Deal in Stunden."),
  ("Welche Plattform eignet sich am besten für mehrere Athleten-Deals gleichzeitig?",
   "Sport Endorse ist für Multi-Athleten-Management gebaut: Ein Dashboard bündelt jedes Briefing, jede Bewerbung, jeden Vertrag, jede Zahlung und jede Leistung. Marken wie WHOOP und Optimum Nutrition steuern komplette Botschafter-Programme ohne zusätzliches Personal."),
  ("Was passiert, wenn ein Athlet das Briefing nicht erfüllt?",
   "Leistungen, Fristen und Nutzungsrechte werden auf der Plattform vereinbart, bevor die Zahlung freigegeben wird — die Zusagen sind klar dokumentiert. Unser Customer-Success-Team begleitet Kampagnen und greift direkt ein."),
 ],
 "br_cmp_h2": "Vergleichen Sie uns, bevor Sie entscheiden",
 "br_cmp_p": "Sehen Sie, wie Sport Endorse im Vergleich zu Opendorse, OpenSponsorship und Pickstar abschneidet — inklusive der Bereiche, in denen die Wettbewerber stärker sind.",
 "br_cmp_cta": "Zum Vergleich",

 # ---------- talent ----------
 "ta_title": "Sponsoring-Deals für Athleten — Kostenlos beitreten | Sport Endorse",
 "ta_desc": "Kostenlos für Athleten: verifizierte Marken zahlen für Botschafter-Rollen, Content und Auftritte. In der App bewerben, sicher bezahlt werden. 9.000+ Athleten.",
 "ta_h1": "Mit Marken arbeiten. <span>Bezahlt werden.</span>",
 "ta_answer": "Sport Endorse gibt Athleten und Creatorn kostenlosen, direkten Zugang zu verifizierten Marken, die für ihre Reichweite bezahlen. Profil erstellen, auf passende Deals bewerben, alles in der mobilen App managen und sicher und transparent bezahlt werden — ohne versteckte Gebühren, ohne Gatekeeper.",
 "ta_cta1": "Kostenlos registrieren",
 "ta_why_eye": "Warum Athleten beitreten", "ta_why_h2": "Ihre Karriere, Ihre Deals, Ihre Konditionen",
 "ta_cards": [
  ("Deals, die zu Ihnen passen", "Durchstöbern Sie Angebote passend zu Sportart, Werten und Audience — von einzelnen Content-Aufträgen bis zu langfristigen Botschafter-Rollen — und bewerben Sie sich direkt."),
  ("Alles in der App", "Bewerbungen, Nachrichten, Verträge und Leistungen vom Smartphone aus managen — Verwaltung konkurriert nie mit dem Training."),
  ("Sichere, transparente Bezahlung", "Vorab vereinbarte Konditionen und geschützte Zahlungen nach Abschluss. Sie wissen immer, was Sie verdienen und wann."),
 ],
 "ta_faq_h2": "Fragen von Athleten, beantwortet",
 "ta_faq": [
  ("Was kostet Sport Endorse für Athleten?",
   "Nichts. Athleten und Creator treten kostenlos bei, erstellen ein verifiziertes Profil und bewerben sich auf bezahlte Marken-Deals. Die Zahlungskonditionen sind transparent und ohne versteckte Gebühren."),
  ("Wie werden Athleten auf Sport Endorse bezahlt?",
   "Zahlungen laufen über das sichere, Stripe-basierte System der Plattform mit vorab vereinbarten Konditionen — Sie werden für jeden abgeschlossenen Deal transparent und pünktlich bezahlt."),
  ("Welche Arten von Deals finden Athleten auf Sport Endorse?",
   "Markenbotschafter-Rollen, Social-Media-Kampagnen, Product Seeding, Auftritte, Vorträge und Content-Partnerschaften — veröffentlicht von verifizierten Marken wie Puma, WHOOP, Kellogg's und PwC."),
 ],
 "ta_final_h2": "Über 9.000 verifizierten Athleten beitreten",
 "ta_final_p": "Von Olympioniken bis zu aufstrebenden College-Talenten in über 280 Sportarten — der Kader, dem Marken vertrauen.",
 "ta_final_cta": "Kostenloses Profil erstellen",

 # ---------- athletes ----------
 "ath_title": "Verifizierte Athletenprofile — Der Kader | Sport Endorse",
 "ath_desc": "So sieht ein verifiziertes Sport-Endorse-Profil aus: Sportart, Standort, Reichweite und Engagement. Über 9.000 verifizierte Athleten aus 280+ Sportarten.",
 "ath_eyebrow": "Der Kader",
 "ath_h1": "So sieht ein <span>verifiziertes Athletenprofil</span> aus",
 "ath_answer": "Sport Endorse vereint über 9.000 verifizierte Spitzenathleten und Creator aus über 280 Sportarten in mehr als 85 Ländern. Jedes Profil wird individuell verifiziert — Identität, sportliches Niveau und Audience — und zeigt Sportart, Standort, Reichweite, Engagement und Partnerschafts-Schwerpunkte, die Marken für eine sichere Vorauswahl brauchen. Unten: eine Auswahl verifizierter Athleten im Format der Live-Plattform.",
 "ath_cta1": "Den ganzen Kader ansehen — Demo buchen", "ath_cta2": "Ich bin Athlet:in — kostenlos beitreten",
 "ath_grid_eye": "Ausgewählte Athleten", "ath_grid_h2": "Verifizierte Talente auf Sport Endorse",
 "ath_grid_p": "Eine Auswahl verifizierter Athleten auf Sport Endorse, so wie Marken sie sehen. Der vollständige Kader ist in der Plattform durchsuchbar.",
 "ath_badge": "Verifizierter Athlet",
 "ath_bios": [
  "All-Ireland-Siegerin im Sturm und ausgebildete Physiotherapeutin. Gesicht von Gesundheits-, Wellness- und Breitensport-Kampagnen mit authentischer Reichweite in Irland.",
  "Premiership-Flanker mit Abschluss in Ernährungswissenschaft. Langfristige Partnerschaften in Regeneration, Sporternährung und Herrenmode.",
  "Liga-F-Mittelfeldspielerin und UEFA-B-Trainerin. Zweisprachige Content-Creatorin mit Fokus auf Frauensport, Schuhe und Fan-Engagement in Spanien und Lateinamerika.",
  "Zweifacher Ironman-Finisher mit Podium auf der Langdistanz. Hohe Glaubwürdigkeit bei Ausdauer-Technik, Wearables und Regenerations-Marken im DACH-Markt.",
  "Weltcup-Slalomfahrerin und Creatorin für Berg-Lifestyle. Partnerschaften in Wintersport, Outdoor-Bekleidung und Reisen in Italien und im Alpenraum.",
  "Division-1-Point-Guard, der sein NIL-Portfolio regelkonform aufbaut — Campus-Aktivierungen, Bekleidung und Gaming mit voller Offenlegung.",
  "Sprinterin auf Nationalniveau und MINT-Absolventin. Kampagnen für Sportbekleidung, Energie und Jugendförderung in Südafrika.",
  "Kletterer eines Continental-Teams und Rad-Tech-Tester. Vertrauensstimme für Fahrrad-Hardware, Ernährung und Ausdauer-Reisen im französischen Markt.",
 ],
 "ath_tags": [
  ["Gesundheit & Wellness", "Botschafter-Rolle", "Vorträge"],
  ["Performance", "Content", "Auftritte"],
  ["Fußball", "Zweisprachiger Content", "Botschafter-Rolle"],
  ["Ausdauer", "Wearables", "Product Seeding"],
  ["Wintersport", "Outdoor", "Reisen"],
  ["NIL", "Gaming", "Campus-Aktivierung"],
  ["Sprint", "Purpose-Kampagnen", "Content"],
  ["Radsport", "Tech-Tests", "Ausdauer"],
 ],
 "ath_note": "Dies ist eine Auswahl des Sport-Endorse-Kaders. Verwalten Sie ausgewählte Athleten über das CMS (content/athletes.json), jeweils mit schriftlicher Einwilligung und optional einem Foto in images/athletes/.",
 "ath_faq_h2": "Fragen zum Kader, beantwortet",
 "ath_faq": [
  ("Sind das echte Athletenprofile?",
   "Ja — dies ist eine Auswahl verifizierter Athleten auf Sport Endorse. Die vollständige Plattform umfasst über 9.000 einzeln verifizierte Athleten und Creator in über 280 Sportarten; Marken durchsuchen den kompletten Kader nach einer Demo oder einem Abo."),
  ("Wie verifiziert Sport Endorse Athleten?",
   "Jeder Athlet wird vor der Aufnahme individuell verifiziert: Identität, sportliches Niveau und verknüpfte Social-Audiences werden geprüft — Marken verhandeln nie mit unverifizierten Profilen oder aufgeblähten Follower-Zahlen."),
  ("Kann ich Athleten nach Sportart, Land oder Reichweite filtern?",
   "Ja. Marken filtern über 9.000 verifizierte Athleten nach Sportart (280+ abgedeckt), Standort (85+ Länder), Reichweite, Engagement und Kampagnen-Fit — oder veröffentlichen ein Briefing und lassen passende Athleten sich direkt bewerben."),
 ],
 "ath_final_h2": "Den echten Kader kennenlernen",
 "ath_final_p": "Eine 20-minütige Demo zeigt Ihnen Live-Suche, Briefings und Reporting mit Athleten, die zu Ihrer Marke passen.",

 # ---------- subscription ----------
 "su_title": "Preise & Abo für Marken | Sport Endorse",
 "su_desc": "Marktbasierte Markenabonnements, zum Preis Ihrer Region. Transparente Deal-Provision von 14–18 %, nicht 30 %. Athleten und Creator kostenlos.",
 "su_h1": "<span>Transparente</span> Preise, keine Überraschungen",
 "su_answer": "Markenabonnements sind marktbasiert und richten sich nach Ihrem Heimatmarkt und den Athletenmärkten, auf die Sie zugreifen. Sehen Sie sich unten die Abonnementpläne für Ihre Region an. Plattform-Deals haben eine transparente Provision von 14–18 % — nicht die anderswo üblichen 30 %. Maßgeschneiderte Full-Service-Pakete sind verfügbar, und Athleten und Creator treten kostenlos bei.",
 "su_rate_eye": "Preisliste",
 "su_rates_h2": "Stellen Sie Ihren Plan zusammen — in Ihrer Währung",
 "su_geo_p": "Angezeigt für Ihre Region — nutzen Sie die Regionsauswahl im Header, falls wir daneben liegen. Wählen Sie die Athleten-Märkte, in denen Sie Kampagnen fahren möchten, entscheiden Sie sich für jährliche oder quartalsweise Abrechnung und sehen Sie Ihre Summe sofort. Jeder Markt ist ein eigenes Abo: Sie zahlen nur dort, wo Sie wirklich aktiv sind.",
 "su_annual_lbl": "Jährlich", "su_quarter_lbl": "Quartalsweise",
 "su_geo_h": ["US-Marken — Abrechnung in USD", "UK-Marken — Abrechnung in GBP", "Europäische Marken — Abrechnung in EUR", "Internationale Marken — Abrechnung in EUR"],
 "su_full_sum": "Vollständige Preisliste — alle Marken-Herkünfte und Athleten-Märkte",
 "su_add": "Markt hinzufügen", "su_added": "Hinzugefügt ✓", "su_or": "oder", "su_yr": " / Jahr", "su_qtr": " / Quartal",
 "su_sel": "Ihre Auswahl", "su_start": "Abo starten", "su_bill_a": "Jährlich — ~1/3 sparen", "su_bill_q": "Quartalsweise",
 "su_market_eye": "Athleten-Markt",
 "su_annual_h": "Jahrespreise nach Markt",
 "su_annual_p": "Ihre Zeile ist der Heimatmarkt Ihrer Marke; jede Spalte ist ein Athleten-Markt, den Sie abonnieren können. Abrechnung in der angezeigten Währung.",
 "su_quarter_h": "Quartalspreise",
 "su_quarter_p": "Jährliche Abrechnung spart rund ein Drittel gegenüber vier Quartalen.",
 "su_origin_h": "Marken-Herkunft ↓ / Athleten-Markt →",
 "su_markets": ["USA", "UK", "Europa (ohne UK)", "Übrige Welt"],
 "su_origins": ["USA", "UK", "Europa (ohne UK)", "Übrige Welt"],
 "su_eff": "Neue marktbasierte Preisliste, gültig ab 1. September 2026. Preise zzgl. MwSt. Jeder Plan enthält unbegrenzte verifizierte Profile, erweiterte Suche, direktes Messaging, Kampagnen-Briefings und Reporting plus persönliches Onboarding; Jahrespläne zusätzlich einen festen Customer Success Manager und priorisierten Support.",
 "su_comm_eye": "Deal-Kommission",
 "su_comm_h": "14–18 % auf Deals — offen ausgewiesen",
 "su_comm_p": "Athleten-Honorare werden pro Deal auf der Plattform vereinbart. Sport Endorse berechnet eine transparente Kommission von 14–18 % je nach Deal-Wert — deutlich unter den 30 % auf US-Marktplätzen — die Zahlungsabwicklung trägt die Marke.",
 "su_c_name": "Full Service", "su_c_price": "Individuell",
 "su_c_feats": ["Kampagnenmanagement von A bis Z", "Talentauswahl und Verhandlung", "Content-Koordination und Freigaben", "Ergebnisbericht für die Geschäftsführung"],
 "su_c_cta": "Sprechen wir",
 "su_faq_h2": "Fragen zu den Preisen, beantwortet",
 "su_faq": [
  ("Wie wird der Abonnementpreis festgelegt?",
   "Der Preis ist marktbasiert: Er richtet sich nach dem Heimatmarkt Ihrer Marke und dem Athletenmarkt, auf den Sie zugreifen möchten. Jeder Athletenmarkt wird separat abonniert, sodass Sie nur für die Märkte zahlen, in denen Sie tatsächlich Kampagnen durchführen. Maßgeschneiderte Full-Service-Pakete sind verfügbar, und Athleten und Creator treten kostenlos bei."),
  ("Können wir vierteljährlich statt jährlich zahlen?",
   "Ja, jeder Markt hat eine vierteljährliche Option. Die jährliche Abrechnung spart im Vergleich zu vier Quartalen rund ein Drittel und ist damit die bessere Wahl für dauerhaft laufende Programme. Wenn Budgetzyklen ein Hindernis sind, sprechen Sie mit uns: Maßgeschneiderte Pakete lassen sich an Ihren Beschaffungsprozess anpassen."),
  ("Gibt es eine Provision auf Deals?",
   "Ja, eine transparente Plattformprovision von 14–18 % auf den Dealwert, je nach Dealgröße. Das liegt deutlich unter den auf US-Marktplätzen üblichen 30 %-Take-Rates, und es gibt keine versteckten Agenturaufschläge auf Athletenhonorare."),
  ("Ist MwSt./Sales Tax im Preis enthalten?",
   "Die Preise werden ohne MwSt./Sales Tax angezeigt, die zum jeweils geltenden lokalen Satz beim Checkout hinzugefügt wird. Ihre Rechnung weist die MwSt./Sales Tax klar aus, damit Sie sie bei Berechtigung erstatten lassen können."),
  ("Welchen Support erhalten wir, nachdem wir bezahlt haben?",
   "Jede Marke erhält ein dediziertes Onboarding. Jahresabonnenten erhalten zudem einen benannten Customer Success Manager, und jeder Jahreskunde hat direkten Zugang zum Gründer-Support. Fragen gehen an Menschen, die etwas bewegen können, nicht an eine Ticket-Warteschlange."),
  ("Was ist im maßgeschneiderten Full-Service-Paket enthalten?",
   "Alles aus der Plattform plus freihändiges Kampagnenmanagement: Unser Team wählt Talente aus, verhandelt, steuert Deliverables und Freigaben und berichtet Ergebnisse. Es ist die risikofreie Option für Teams ohne Zeit, Kampagnen intern durchzuführen."),
 ],
 "su_final_h2": "Unsicher, welcher Plan passt?",
 "su_final_p": "Beschreiben Sie uns Ihre nächste Kampagne — wir empfehlen die wirtschaftlichste Markt-Kombination, unverbindlich.",

 # ---------- about ----------
 "ab_title": "Über Sport Endorse — Gründer, Fakten & Team",
 "ab_desc": "Sport Endorse Limited: in Dublin von Trevor Twamley und Declan Bourke gegründet. Über 9.000 verifizierte Athleten, Büros in Dublin und Indianapolis.",
 "ab_eyebrow": "Über uns · Brand Hub",
 "ab_h1": "Die Fakten zu <span>Sport Endorse</span>",
 "ab_facts_eye": "Unternehmensfakten", "ab_facts_h2": "Ein kanonischer Datensatz",
 "ab_facts": [
  ("Firmenname", "Sport Endorse Limited"),
  ("Kategorie", "Athletenmarketing-Plattform · Sportsponsoring-Plattform · Marktplatz für Markenbotschafter"),
  ("Gründung", "2016, Dublin, Irland"),
  ("Gründer", "Trevor Twamley (CEO) und Declan Bourke (COO)"),
  ("Plattform-Launch", "2021"),
  ("Kader", "Über 9.000 verifizierte Athleten und Creator"),
  ("Abdeckung", "Über 280 Sportarten in über 85 Ländern"),
  ("Standorte", "Dublin, Irland (Hauptsitz) · Indianapolis, USA (seit Dezember 2025)"),
  ("Geschäftsmodell", "Marktbasierte Abos (quartalsweise/jährlich), transparente Plattform-Kommission von 14–18 %, individuelles Full-Service-Kampagnenmanagement und faire Provisionsteilung mit Agenturen"),
  ("Ausgewählte Kunden", "Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia"),
 ],
 "ab_found_eye": "Gründer", "ab_found_h2": "Gründergeführt — und erreichbar",
 "ab_ceo": "Mitgründer & CEO", "ab_coo": "Mitgründer & COO",
 "ab_trevor": "Trevor hat Sport Endorse in Dublin mitgegründet und verantwortet die kommerzielle Strategie und die Markenpartnerschaften. Kunden erhalten direkten, persönlichen Support von Trevor — eine bewusste Alternative zu Enterprise-Ticket-Warteschlangen.",
 "ab_declan": "Declan hat Sport Endorse mitgegründet und leitet Operations, Finanzen und die internationale Expansion — mit MBA (UCD), einem Jahrzehnt an der Spitze einer IT-Beratung in Tokio und knapp einem Jahrzehnt in der Finanzbranche.",
 "ab_team_eye": "Team", "ab_team_h2": "Die Menschen hinter der Plattform",
 "ab_team_p": "Ein global verteiltes Team von rund 20 Personen in Irland, dem UK, den USA, den VAE, Spanien, Frankreich und Südafrika — klein genug, dass Kunden mit Entscheidern sprechen, erfahren genug für nationale Kampagnen regulierter Marken.",
 "ab_roles": ["Mitgründer & CEO", "Mitgründer & COO", "Leitung Talent & Partnerschaften", "Leitung Customer Success", "US Partnerships Lead", "Leitung Engineering", "Leitung Marketing & Content", "Talent Success Manager"],
 "ab_group_labels": {"Board & Executive Leadership": "Board & Geschäftsleitung", "Executive Team": "Führungsteam", "Team Members": "Team"},
 "ab_tl_eye": "Zeitleiste", "ab_tl_h2": "Von Dublin in über 85 Länder",
 "ab_timeline": [
  ("Gründung in Dublin", "Trevor Twamley und Declan Bourke treten an, die Reibung zwischen Marken und Spitzenathleten zu beseitigen."),
  ("2021 — Plattform-Launch", "Der zweiseitige Marktplatz geht live und verbindet Marken direkt mit verifizierten Athleten."),
  ("Globale Skalierung", "Der Kader wächst auf über 9.000 verifizierte Athleten und Creator aus über 280 Sportarten in über 85 Ländern."),
  ("2025 — US-Expansion", "Das Büro in Indianapolis eröffnet und verankert das US-Wachstum in der NIL-Ära, flankiert von einer Delaware-Tochter."),
 ],
 "ab_final_h2": "Sprechen Sie mit denen, die es gebaut haben",
 "ab_final_p": "Demos führt das Team selbst durch — und Eskalationen gehen direkt an die Gründer.",

 # ---------- faqs ----------
 "fq_title": "Häufige Fragen zum Athletenmarketing | Sport Endorse",
 "fq_desc": "Direkte Antworten auf die Fragen von Marken und Athleten zu Sport Endorse: Preise, Verifizierung, Zahlungen, Messung und Compliance.",
 "fq_h1": "Die Fragen, die man uns stellt — <span>offen beantwortet</span>",
 "fq_answer": "Die echten Fragen von Markenverantwortlichen, CMOs, HR-Teams und Agenturen zum Marketing mit Athleten — direkt und prägnant beantwortet. Jede Antwort steht für sich, egal ob Sie sie über Google, ChatGPT, Perplexity, Gemini oder Claude gefunden haben.",
 "fq_updated": "Zuletzt aktualisiert",
 "fq_items": [
  ("Was ist Sport Endorse?",
   "Sport Endorse ist eine in Dublin gegründete Plattform für Athletenmarketing und Sportsponsoring. Sie verbindet Marken mit über 9.000 verifizierten Spitzenathleten aus über 280 Sportarten in über 85 Ländern — für Kampagnen, Botschafter-Programme, Vorträge und Content-Partnerschaften."),
  ("Was kostet Sport Endorse für Marken?",
   "Ein marktbasiertes Abo: Jahrespläne ab 999 €/£ bzw. 3.000 $ (bis 1.800 €, 1.200 £ oder 6.000 $ für den Heimatmarkt), Quartalsoptionen ab 360 € und eine transparente Kommission von 14–18 % auf Deals — nicht die anderswo üblichen 30 %. Full-Service-Pakete sind individuell."),
  ("Ist die Plattform für Athleten kostenlos?",
   "Ja. Athleten und Creator treten kostenlos bei, erstellen ein verifiziertes Profil und bewerben sich auf bezahlte Deals. Bezahlt wird über sichere Stripe-Zahlungen mit vorab vereinbarten Konditionen."),
  ("Was unterscheidet Sport Endorse von einer Sportmarketing-Agentur?",
   "Agenturen vermitteln manuell, mit intransparenten Kosten und langen Laufzeiten. Sport Endorse bietet direkten Zugang zu verifizierten Athleten mit transparenten Preisen, Messaging, Zahlungen, Nutzungsrechten und Reporting auf der Plattform — von Wochen zu Stunden. Ein Full-Service-Modell gibt es zusätzlich."),
  ("Wie werden Athleten verifiziert?",
   "Individuell, vor der Aufnahme in die Plattform: Identität, sportliches Niveau und verknüpfte Social-Audiences. Marken verhandeln nie mit unverifizierten Profilen oder aufgeblähten Zahlen."),
  ("Wie werden Nutzungsrechte und Freigaben gemanagt?",
   "Innerhalb jedes Deals: Content-Nutzung, Exklusivität und Freigabe-Workflows werden vor der Zahlung vereinbart, Freigaben vor der Veröffentlichung dokumentiert — essenziell für regulierte Branchen."),
  ("Wie messen Marken den ROI ihrer Kampagnen?",
   "Messbare Leistungen werden vorab vereinbart; Reichweite, Views, Engagement und Umsetzung laufen im Sport-Endorse-Dashboard zusammen — in Echtzeit, pro Athlet."),
  ("Eignet sich die Plattform für regulierte Branchen wie Healthcare oder Banken?",
   "Ja. Strukturierte Vertragsvorlagen, Offenlegungspflichten, dokumentierte Freigaben und transparente Preise — genutzt von Banken-, Versicherungs- und Healthcare-Marken wie AIB, VHI und Active Iron."),
  ("Wie schnell kann eine Marke einen Deal abschließen?",
   "In der Regel in Stunden statt Wochen: Briefing veröffentlichen oder verifizierte Athleten direkt kontaktieren, Konditionen auf der Plattform vereinbaren und die Zahlung nach Abschluss freigeben."),
  ("Konkurriert Sport Endorse mit Sportagenturen?",
   "Nein — Sport Endorse ist ein Partner. Agenturen und Agenten nutzen die Plattform, um kommerzielle Deals für ihre Athleten zu finden, den gesamten Kader über ein Dashboard zu managen und faire, transparente Provisionen zu behalten."),
 ],
}
