# -*- coding: utf-8 -*-
"""Spanish (es) translations — Sport Endorse localized build."""

T = {
 "nav": {"brands.html": "Para marcas", "talent.html": "Para deportistas", "athletes.html": "Perfiles",
         "subscription.html": "Precios", "faqs.html": "FAQ", "about.html": "Quiénes somos"},
 "region_label": "Elige tu región", "lang_label": "Elige idioma", "europe": "Europa",
 "cta_demo": "Solicitar una demo",
 "footer_entity": "Sport Endorse Limited fue fundada en Dublín, Irlanda por Trevor Twamley y Declan Bourke. La plataforma opera desde principios de 2021 y hoy conecta marcas con más de 9.000 deportistas y creadores verificados de más de 280 deportes en más de 85 países.",
 "ireland": "Irlanda", "us_office": "Oficina en EE. UU.",
 "f_platform": "Plataforma", "f_more": "Recursos", "f_compare": "Comparativa de plataformas",
 "f_stories": "Casos de éxito", "f_health": "Salud y farmacia", "f_agencies": "Para agencias",
 "f_company": "Empresa", "rights": "Todos los derechos reservados.",
 "tk_founded": "Sede", "tk_athletes": "deportistas y creadores verificados",
 "tk_sports": "deportes", "tk_countries": "países", "tk_live": "Plataforma activa desde",
 "tk_trusted": "Confían en nosotros", "tk_offices": "Oficinas en",

 "v_eyebrow": "Resumen en dos minutos", "v_title": "Así funciona la plataforma",
 "v_sub": "Cómo las marcas descubren, contactan y gestionan deportistas verificados en Sport Endorse.",
 "v_coming": "Vídeo de presentación próximamente",
 "v_hint": "Añade el ID de YouTube en <code>VIDEO_ID</code> (build.py) y vuelve a ejecutar el build: este bloque se convierte en un reproductor.",

 "positioning": "Sport Endorse es una plataforma de marketing deportivo y patrocinio que ayuda a marcas y empresas a descubrir, evaluar, contactar y gestionar deportistas de élite verificados para campañas medibles, embajadas de marca, conferencias y colaboraciones de contenido. Las agencias y agentes deportivos se asocian con Sport Endorse para encontrar acuerdos comerciales para sus deportistas.",

 # ---------- index ----------
 "hx_title": "Plataforma de patrocinio deportivo para marcas | Sport Endorse",
 "hx_desc": "La plataforma de marketing deportivo que conecta marcas con más de 9.000 deportistas de élite verificados de 280+ deportes en 85+ países. Precios transparentes.",
 "hx_eyebrow": "Marketing deportivo · Plataforma de patrocinio",
 "hx_h1": "Deportistas de élite verificados.<br><span>Una plataforma.</span> Todos los acuerdos.",
 "hx_lead": "Más de 9.000 deportistas y creadores de élite verificados, 280+ deportes, 85+ países — con suscripciones transparentes basadas en el mercado y soporte directo de los fundadores.",
 "hx_cta1": "Explorar colaboraciones", "hx_cta3": "Soy deportista",
 "hx_trust_eye": "Confían en nosotros", "hx_trust_h2": "Marcas que construyen con Sport Endorse",
 "hx_three_eye": "Tres formas de entrar", "hx_three_h2": "Para marcas, deportistas y agencias",
 "hx_three": [
  ("Para marcas", "Descubre y contacta talento verificado de todos los deportes, publica briefings, evalúa candidaturas, gestiona derechos de uso y pagos, y mide resultados — todo en un solo lugar."),
  ("Para deportistas", "Acceso directo y gratuito a marcas verificadas dispuestas a pagar por tu influencia. Solicita los acuerdos que encajan contigo y cobra de forma segura, sin comisiones ocultas."),
  ("Para agencias", "Un flujo constante de oportunidades comerciales para toda tu cartera, gestionado desde un único panel seguro, con comisiones transparentes. Un socio, nunca un competidor."),
 ],
 "hx_how_eye": "Cómo funciona", "hx_how_h2": "Del briefing a la campaña medida en cuatro pasos",
 "hx_steps": [
  ("Descubre", "Busca entre más de 9.000 deportistas verificados por deporte, región, tamaño de audiencia y encaje de campaña — o publica una oportunidad y deja que el talento adecuado se presente."),
  ("Conecta", "Envía mensajes a deportistas y agentes directamente en la plataforma. Sin intermediarios, sin cadenas de correos interminables, sin márgenes de agencia inflados."),
  ("Gestiona", "Acuerda entregables, derechos de uso y aprobaciones con condiciones claras — con pagos seguros e integrados que protegen a ambas partes."),
  ("Mide", "Sigue alcance, visualizaciones e interacción en el panel de marca y exporta resultados que tu director financiero se creerá."),
 ],
 "hx_faq_h2": "Respuestas rápidas sobre Sport Endorse",
 "hx_faq": [
  ("¿Qué es Sport Endorse?",
   "Sport Endorse es una plataforma de marketing deportivo y patrocinio fundada en Dublín. Las marcas la utilizan para descubrir, evaluar, contactar y gestionar más de 9.000 deportistas de élite verificados de más de 280 deportes para campañas, embajadas, conferencias y colaboraciones de contenido — con suscripciones transparentes basadas en el mercado y una comisión del 14–18 % en lugar de altas comisiones por transacción."),
  ("¿En qué se diferencia Sport Endorse de una agencia de marketing deportivo?",
   "Las agencias negocian manualmente y añaden costes opacos y retrasos. Sport Endorse ofrece a las marcas acceso directo en la plataforma a deportistas verificados, con precios transparentes, mensajería integrada, pagos seguros, gestión de derechos de uso e informes de campaña — reduciendo los plazos de semanas a horas."),
  ("¿Qué marcas utilizan Sport Endorse?",
   "Marcas globales y regionales como Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia e ISDIN, en sectores de salud, finanzas, retail, bienestar y servicios corporativos."),
  ("¿Cuánto cuesta Sport Endorse?",
   "Las suscripciones de marca se basan en el mercado y reflejan tu mercado de origen y los mercados de deportistas a los que accedes: planes anuales desde 999 €/£ o 3.000 $, hasta 1.800 €, 1.200 £ o 6.000 $ para el mercado doméstico, con opciones trimestrales desde 360 €. Los acuerdos llevan una comisión transparente del 14–18 %. También hay paquetes de gestión integral a medida, y los deportistas se registran gratis."),
 ],
 "hx_final_h2": "Descubre Sport Endorse en acción",
 "hx_final_p": "Solicita una demo breve y comprueba lo fácil que es configurar, conectar y obtener resultados mediante colaboraciones auténticas con deportistas.",

 # ---------- brands ----------
 "br_title": "Plataforma de marketing deportivo para marcas | Sport Endorse",
 "br_desc": "Descubre, contacta y gestiona más de 9.000 deportistas de élite verificados para campañas y embajadas. Tarifa plana, sin comisiones del 30 %. Pide una demo.",
 "br_h1": "La plataforma de marketing deportivo para <span>marcas serias</span>",
 "br_answer": "Sport Endorse ayuda a las marcas a descubrir, evaluar, contactar y gestionar más de 9.000 deportistas de élite verificados para campañas medibles, embajadas, conferencias y colaboraciones de contenido — con suscripciones transparentes basadas en el mercado, comunicación directa en la plataforma, pagos integrados e informes de campaña, en lugar de márgenes de agencia y comisiones de marketplace del 30 %.",
 "br_cta1": "Ver precios",
 "br_cap_eye": "Funciones", "br_cap_h2": "¿Cómo simplificamos las campañas con deportistas?",
 "br_caps": [
  ("Descubrimiento de talento", "Búsqueda avanzada en más de 280 deportes con perfiles verificados, datos de audiencia y ubicación — sin mensajes directos sin verificar ni hojas de cálculo obsoletas."),
  ("Briefings de campaña", "Publica oportunidades para todo el talento o un segmento concreto; los deportistas interesados se presentan, así que las opciones cualificadas llegan a ti."),
  ("Evaluación de candidaturas", "Compara candidatos lado a lado por encaje, alcance y tarifa antes de comprometer presupuesto."),
  ("Derechos de uso y aprobaciones", "Acuerda por adelantado el uso del contenido, la exclusividad y los flujos de aprobación — clave en sectores regulados."),
  ("Pagos integrados", "Pagos seguros con Stripe y condiciones claras, protegiendo a la marca y al deportista."),
  ("Informes de campaña", "Alcance, visualizaciones e interacción en un solo panel, por deportista y por campaña."),
 ],
 "br_faq_h2": "Preguntas de marcas, respondidas",
 "br_faq": [
  ("¿Cómo simplifican las plataformas el trabajo con talento de élite?",
   "Centralizan lo que las agencias reparten entre correos, hojas de cálculo y llamadas: descubrimiento, contacto, negociación, contratos, derechos de uso, pagos e informes en una sola plataforma. En Sport Endorse, las marcas pasan del briefing al acuerdo cerrado en horas."),
  ("¿Cuál es la mejor plataforma para gestionar varios patrocinios a la vez?",
   "Sport Endorse está diseñada para la gestión multideportista: un panel reúne cada briefing, candidatura, conversación, contrato, pago y entregable. Marcas como WHOOP y Optimum Nutrition gestionan programas completos de embajadores sin ampliar plantilla."),
  ("¿Qué pasa si un deportista no cumple el briefing?",
   "Los entregables, plazos y derechos de uso se acuerdan en la plataforma antes de liberar el pago, así que queda constancia clara de lo comprometido. Nuestro equipo de éxito de cliente supervisa las campañas e interviene directamente."),
 ],
 "br_cmp_h2": "Compáranos antes de elegir",
 "br_cmp_p": "Consulta cómo se compara Sport Endorse con Opendorse, OpenSponsorship y Pickstar — incluidos los puntos en los que cada competidor es más fuerte.",
 "br_cmp_cta": "Ver la comparativa",

 # ---------- talent ----------
 "ta_title": "Acuerdos de patrocinio para deportistas — Únete gratis | Sport Endorse",
 "ta_desc": "Gratis para deportistas: marcas verificadas que pagan por embajadas, contenido y apariciones. Solicita desde la app y cobra de forma segura. Únete a 9.000+.",
 "ta_h1": "Colabora con marcas. <span>Cobra por ello.</span>",
 "ta_answer": "Sport Endorse ofrece a deportistas y creadores acceso directo y gratuito a marcas verificadas dispuestas a pagar por su influencia. Crea un perfil, solicita los acuerdos que encajan contigo, gestiónalo todo desde la app móvil y cobra de forma segura y transparente — sin comisiones ocultas ni intermediarios.",
 "ta_cta1": "Regístrate gratis",
 "ta_why_eye": "Por qué se unen los deportistas", "ta_why_h2": "Tu carrera, tus acuerdos, tus condiciones",
 "ta_cards": [
  ("Acuerdos a tu medida", "Explora y solicita oportunidades acordes a tu deporte, tus valores y tu audiencia — desde contenido puntual hasta embajadas de larga duración."),
  ("Todo en la app", "Candidaturas, mensajes, contratos y entregables gestionados desde el móvil, para que la administración nunca compita con el entrenamiento."),
  ("Cobro seguro y transparente", "Condiciones acordadas por adelantado y pagos protegidos al completar el trabajo. Siempre sabes cuánto ganas y cuándo."),
 ],
 "ta_faq_h2": "Preguntas de deportistas, respondidas",
 "ta_faq": [
  ("¿Cuánto cuesta Sport Endorse para deportistas?",
   "Nada. Los deportistas y creadores se unen gratis, crean un perfil verificado y solicitan acuerdos remunerados con marcas. Las condiciones de pago son transparentes y sin costes ocultos."),
  ("¿Cómo cobran los deportistas en Sport Endorse?",
   "Los pagos se realizan mediante el sistema seguro de la plataforma, con tecnología Stripe, y con condiciones acordadas antes de empezar el trabajo — cobras de forma transparente y puntual por cada acuerdo completado."),
  ("¿Qué tipo de acuerdos pueden encontrar los deportistas?",
   "Embajadas de marca, campañas en redes sociales, envío de producto, apariciones, conferencias y colaboraciones de contenido — publicados por marcas verificadas como Puma, WHOOP, Kellogg's y PwC."),
 ],
 "ta_final_h2": "Únete a más de 9.000 deportistas verificados",
 "ta_final_p": "De olímpicos a jóvenes promesas universitarias en más de 280 deportes — el plantel en el que confían las marcas.",
 "ta_final_cta": "Crea tu perfil gratis",

 # ---------- athletes ----------
 "ath_title": "Perfiles de deportistas verificados — El plantel | Sport Endorse",
 "ath_desc": "Descubre cómo es un perfil verificado de Sport Endorse: deporte, ubicación, audiencia e interacción. Más de 9.000 deportistas verificados de 280+ deportes.",
 "ath_eyebrow": "El plantel",
 "ath_h1": "Así es un <span>perfil verificado</span> de deportista",
 "ath_answer": "Sport Endorse reúne a más de 9.000 deportistas y creadores de élite verificados de más de 280 deportes en más de 85 países. Cada perfil se verifica individualmente — identidad, nivel deportivo y audiencia — y muestra el deporte, la ubicación, el alcance, la interacción y el enfoque de colaboración que las marcas necesitan para preseleccionar con confianza. Abajo: una selección de deportistas verificados, en el formato real de la plataforma.",
 "ath_cta1": "Ver el plantel completo — pide una demo", "ath_cta2": "Soy deportista — únete gratis",
 "ath_grid_eye": "Deportistas destacados", "ath_grid_h2": "Talento verificado en Sport Endorse",
 "ath_grid_p": "Una selección de deportistas verificados en Sport Endorse, tal como aparecen ante las marcas. El plantel completo se explora dentro de la plataforma.",
 "ath_badge": "Deportista verificado",
 "ath_bios": [
  "Delantera campeona de la All-Ireland y fisioterapeuta titulada. Protagoniza campañas de salud, bienestar y deporte de base con alcance auténtico en Irlanda.",
  "Tercera línea de la Premiership con grado en nutrición. Colaboraciones de larga duración en recuperación, nutrición deportiva y moda masculina.",
  "Centrocampista de la Liga F y entrenadora UEFA B. Creadora bilingüe centrada en el deporte femenino, botas y engagement de aficionados en España y Latinoamérica.",
  "Dos veces finisher de Ironman y podio en distancia completa. Gran credibilidad en tecnología de resistencia, wearables y marcas de recuperación en el mercado DACH.",
  "Esquiadora de slalom de Copa del Mundo y creadora de estilo de vida de montaña. Colaboraciones de deportes de invierno, ropa outdoor y viajes en Italia y los Alpes.",
  "Base de División 1 que construye su cartera NIL de forma conforme — activaciones en el campus, ropa deportiva y gaming con total transparencia.",
  "Velocista de nivel nacional y graduada STEM. Campañas de ropa deportiva, energía y causas de desarrollo juvenil en Sudáfrica.",
  "Escalador de equipo continental y analista de tecnología ciclista. Voz de referencia en componentes, nutrición y viajes de resistencia en el mercado francés.",
 ],
 "ath_tags": [
  ["Salud y bienestar", "Embajada", "Conferencias"],
  ["Rendimiento", "Contenido", "Apariciones"],
  ["Fútbol", "Contenido bilingüe", "Embajada"],
  ["Resistencia", "Wearables", "Envío de producto"],
  ["Deportes de invierno", "Outdoor", "Viajes"],
  ["NIL", "Gaming", "Activación en campus"],
  ["Velocidad", "Con propósito", "Contenido"],
  ["Ciclismo", "Análisis técnico", "Resistencia"],
 ],
 "ath_note": "Esta es una selección del plantel de Sport Endorse. Gestiona los deportistas destacados mediante el CMS (content/athletes.json), cada uno con su consentimiento por escrito y, opcionalmente, una foto en images/athletes/.",
 "ath_faq_h2": "Preguntas sobre el plantel, respondidas",
 "ath_faq": [
  ("¿Son reales estos perfiles?",
   "Sí — estos son una selección de deportistas verificados en Sport Endorse. La plataforma completa aloja más de 9.000 deportistas y creadores verificados individualmente en más de 280 deportes; las marcas exploran el plantel completo tras pedir una demo o suscribirse."),
  ("¿Cómo verifica Sport Endorse a los deportistas?",
   "Cada deportista se verifica individualmente antes de aparecer en la plataforma: se comprueban la identidad, el nivel deportivo y las audiencias sociales conectadas, de modo que las marcas nunca negocian con perfiles sin verificar ni cifras de seguidores infladas."),
  ("¿Puedo buscar deportistas por deporte, país o audiencia?",
   "Sí. Las marcas filtran más de 9.000 deportistas verificados por deporte (280+ cubiertos), ubicación (85+ países), tamaño de audiencia, interacción y encaje de campaña — o publican un briefing y dejan que los deportistas adecuados se presenten directamente."),
 ],
 "ath_final_h2": "Descubre el plantel real",
 "ath_final_p": "Una demo de 20 minutos te muestra la búsqueda en vivo, los briefings y los informes con deportistas relevantes para tu marca.",

 # ---------- subscription ----------
 "su_title": "Precios y suscripción para marcas | Sport Endorse",
 "su_desc": "Suscripciones de marca según el mercado, con precios para tu región. Comisión transparente del 14–18 % en acuerdos, no del 30 %. Deportistas y creadores gratis.",
 "su_h1": "Precios <span>transparentes</span>, sin sorpresas",
 "su_answer": "Las suscripciones de marca se basan en el mercado y reflejan tu mercado de origen y los mercados de deportistas a los que accedes. Consulta los precios a continuación para ver los planes de suscripción de tu región. Los acuerdos en plataforma tienen una comisión transparente del 14–18% — no el 30% habitual en otros sitios. Hay paquetes full-service a medida disponibles, y los deportistas y creadores se unen gratis.",
 "su_rate_eye": "Tarifas",
 "su_rates_h2": "Configura tu plan, en tu moneda",
 "su_geo_p": "Se muestra para tu región — usa el selector de región en la cabecera si nos hemos equivocado. Elige los mercados de deportistas en los que quieres hacer campañas, selecciona facturación anual o trimestral y ve tu total al instante. Cada mercado es una suscripción independiente: solo pagas por donde realmente haces campañas.",
 "su_annual_lbl": "Anual", "su_quarter_lbl": "Trimestral",
 "su_geo_h": ["Marcas de EE. UU. — facturación en USD", "Marcas del Reino Unido — facturación en GBP", "Marcas europeas — facturación en EUR", "Marcas internacionales — facturación en EUR"],
 "su_full_sum": "Tarifa completa — todos los orígenes de marca y mercados de deportistas",
 "su_add": "Añadir mercado", "su_added": "Añadido ✓", "su_or": "o", "su_yr": " / año", "su_qtr": " / trimestre",
 "su_sel": "Tu selección", "su_start": "Iniciar suscripción", "su_bill_a": "Anual — ahorra ~1/3", "su_bill_q": "Trimestral",
 "su_market_eye": "Mercado de deportistas",
 "su_annual_h": "Tarifas anuales por mercado",
 "su_annual_p": "Tu fila es el mercado de origen de tu marca; cada columna es un mercado de deportistas al que puedes suscribirte. Se factura en la moneda indicada.",
 "su_quarter_h": "Tarifas trimestrales",
 "su_quarter_p": "La facturación anual ahorra aproximadamente un tercio frente a cuatro trimestres.",
 "su_origin_h": "Origen de la marca ↓ / Mercado del deportista →",
 "su_markets": ["EE. UU.", "Reino Unido", "Europa (sin RU)", "Resto del mundo"],
 "su_origins": ["EE. UU.", "Reino Unido", "Europa (sin RU)", "Resto del mundo"],
 "su_eff": "Nueva tarifa basada en mercado en vigor desde el 1 de septiembre de 2026. Precios sin IVA. Todos los planes incluyen perfiles verificados ilimitados, búsqueda avanzada, mensajería directa, briefings de campaña e informes, además de onboarding dedicado; los planes anuales añaden un gestor de éxito de cliente y soporte prioritario.",
 "su_comm_eye": "Comisión por acuerdo",
 "su_comm_h": "14–18 % en los acuerdos, con total transparencia",
 "su_comm_p": "Los honorarios del deportista se pactan acuerdo a acuerdo en la plataforma. Sport Endorse añade una comisión transparente del 14 al 18 % según el valor del acuerdo — muy por debajo del 30 % habitual en los marketplaces estadounidenses — y la marca cubre el procesamiento del pago.",
 "su_c_name": "Servicio integral", "su_c_price": "A medida",
 "su_c_feats": ["Gestión de campañas de principio a fin", "Selección de talento y negociación", "Coordinación de contenido y aprobaciones", "Informe de resultados para dirección"],
 "su_c_cta": "Hablemos",
 "su_faq_h2": "Preguntas sobre precios, respondidas",
 "su_faq": [
  ("¿Cómo se determina el precio de la suscripción?",
   "El precio se basa en el mercado: refleja el mercado de origen de tu marca y el mercado de deportistas al que quieres acceder. Cada mercado de deportistas se contrata por separado, así que solo pagas por los mercados en los que realmente haces campaña. Hay paquetes full-service a medida disponibles, y los deportistas y creadores se unen gratis."),
  ("¿Podemos pagar trimestralmente en lugar de anualmente?",
   "Sí, cada mercado tiene una opción trimestral. La facturación anual ahorra aproximadamente un tercio frente a cuatro trimestres, por lo que es la mejor opción para programas siempre activos. Si los ciclos presupuestarios son un obstáculo, habla con nosotros: los paquetes a medida pueden estructurarse en torno a tu proceso de compras."),
  ("¿Hay comisión en los acuerdos?",
   "Sí, una comisión de plataforma transparente del 14–18% sobre el valor del acuerdo, según su tamaño. Está muy por debajo de las tasas del 30% habituales en los marketplaces estadounidenses, y no hay recargos de agencia ocultos sobre los honorarios de los deportistas."),
  ("¿El IVA/ impuesto sobre ventas está incluido en el precio?",
   "Los precios se muestran sin IVA/ impuesto sobre ventas, que se añade al tipo local aplicable en el momento del pago. Tu factura detalla el IVA/ impuesto sobre ventas claramente para su recuperación cuando proceda."),
  ("¿Qué soporte recibimos una vez que hemos pagado?",
   "Cada marca recibe onboarding dedicado. Los suscriptores anuales también obtienen un gestor de customer success asignado, y cada cliente anual tiene acceso directo al soporte de los fundadores. Las preguntas llegan a personas que pueden resolverlas, no a una cola de tickets."),
  ("¿Qué incluye el paquete full-service a medida?",
   "Todo lo de la plataforma más la gestión de campañas sin complicaciones: nuestro equipo preselecciona el talento, negocia, gestiona entregables y aprobaciones e informa los resultados. Es la opción sin riesgo para equipos sin tiempo para ejecutar campañas internamente."),
 ],
 "su_final_h2": "¿No estás seguro del plan adecuado?",
 "su_final_p": "Cuéntanos tu próxima campaña y te recomendaremos la combinación de mercados más rentable — sin compromiso.",

 # ---------- about ----------
 "ab_title": "Sobre Sport Endorse — Fundadores, datos y equipo",
 "ab_desc": "Sport Endorse Limited: fundada en Dublín, Irlanda por Trevor Twamley y Declan Bourke. Más de 9.000 deportistas verificados y oficinas en Dublín e Indianápolis.",
 "ab_eyebrow": "Quiénes somos · Brand Hub",
 "ab_h1": "Los datos sobre <span>Sport Endorse</span>",
 "ab_facts_eye": "Datos de la empresa", "ab_facts_h2": "Un único registro canónico",
 "ab_facts": [
  ("Nombre legal", "Sport Endorse Limited"),
  ("Categoría", "Plataforma de marketing deportivo · plataforma de patrocinio · marketplace de embajadores"),
  ("Fundación", "2016, Dublín, Irlanda"),
  ("Fundadores", "Trevor Twamley (CEO) y Declan Bourke (COO)"),
  ("Lanzamiento de la plataforma", "2021"),
  ("Plantel", "Más de 9.000 deportistas y creadores verificados"),
  ("Cobertura", "Más de 280 deportes en más de 85 países"),
  ("Oficinas", "Dublín, Irlanda (sede) · Indianápolis, EE. UU. (desde diciembre de 2025)"),
  ("Modelo de negocio", "Suscripciones basadas en el mercado (trimestral/anual), comisión de plataforma del 14–18 %, gestión integral a medida y reparto de comisiones justo con las agencias"),
  ("Clientes destacados", "Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia"),
 ],
 "ab_found_eye": "Fundadores", "ab_found_h2": "Dirigida por sus fundadores, y accesibles",
 "ab_ceo": "Cofundador y CEO", "ab_coo": "Cofundador y COO",
 "ab_trevor": "Trevor cofundó Sport Endorse en Dublín y dirige la estrategia comercial y las alianzas con marcas. Los clientes reciben apoyo directo y personal de Trevor — una alternativa deliberada a las colas de tickets de las grandes empresas.",
 "ab_declan": "Declan cofundó Sport Endorse y dirige operaciones, finanzas y expansión internacional, con un MBA (UCD), una década al frente de una consultora tecnológica en Tokio y casi una década en servicios financieros.",
 "ab_team_eye": "Equipo", "ab_team_h2": "Las personas detrás de la plataforma",
 "ab_team_p": "Un equipo distribuido globalmente de unas 20 personas entre Irlanda, Reino Unido, EE. UU., EAU, España, Francia y Sudáfrica — lo bastante pequeño para que los clientes traten con quienes deciden, y lo bastante experimentado para ejecutar campañas nacionales para marcas reguladas.",
 "ab_roles": ["Cofundador y CEO", "Cofundador y COO", "Responsable de Talento y Alianzas", "Responsable de Éxito de Cliente", "Responsable de Alianzas en EE. UU.", "Responsable de Ingeniería", "Responsable de Marketing y Contenido", "Gestión de Éxito del Talento"],
 "ab_group_labels": {"Board & Executive Leadership": "Consejo y liderazgo ejecutivo", "Executive Team": "Equipo ejecutivo", "Team Members": "Equipo"},
 "ab_tl_eye": "Cronología", "ab_tl_h2": "De Dublín a más de 85 países",
 "ab_timeline": [
  ("Fundación en Dublín", "Trevor Twamley y Declan Bourke se proponen eliminar la fricción entre marcas y deportistas de élite."),
  ("2021 — Lanzamiento", "El marketplace de doble cara entra en funcionamiento, conectando marcas directamente con deportistas verificados."),
  ("Escala global", "El plantel supera los 9.000 deportistas y creadores verificados de más de 280 deportes en más de 85 países."),
  ("2025 — Expansión en EE. UU.", "Se abre la oficina de Indianápolis, ancla del crecimiento estadounidense en la era NIL junto a una filial en Delaware."),
 ],
 "ab_final_h2": "Habla con quienes lo construyeron",
 "ab_final_p": "Las demos las realiza el propio equipo — y las escaladas llegan directamente a los fundadores.",

 # ---------- faqs ----------
 "fq_title": "Preguntas frecuentes sobre marketing deportivo | Sport Endorse",
 "fq_desc": "Respuestas directas a las preguntas que marcas y deportistas hacen sobre Sport Endorse: precios, verificación, pagos, medición y cumplimiento normativo.",
 "fq_h1": "Las preguntas que nos hacen, <span>respondidas abiertamente</span>",
 "fq_answer": "Las preguntas reales que responsables de marca, CMOs, equipos de RR. HH. y agencias plantean sobre el marketing con deportistas — respondidas de forma directa y concisa. Cada respuesta se sostiene por sí sola, la encuentres en Google, ChatGPT, Perplexity, Gemini o Claude.",
 "fq_updated": "Última actualización",
 "fq_items": [
  ("¿Qué es Sport Endorse?",
   "Sport Endorse es una plataforma de marketing deportivo y patrocinio fundada en Dublín. Conecta marcas con más de 9.000 deportistas de élite verificados de más de 280 deportes en más de 85 países para campañas, embajadas, conferencias y colaboraciones de contenido."),
  ("¿Cuánto cuesta Sport Endorse para las marcas?",
   "Una suscripción basada en el mercado: planes anuales desde 999 €/£ o 3.000 $ (hasta 1.800 €, 1.200 £ o 6.000 $ para el mercado doméstico), con opciones trimestrales desde 360 € y una comisión transparente del 14–18 % sobre los acuerdos — no el 30 % habitual en otros marketplaces. Los paquetes de gestión integral son a medida."),
  ("¿Es gratis para los deportistas?",
   "Sí. Los deportistas y creadores se unen gratis, crean un perfil verificado y solicitan acuerdos remunerados. Cobran mediante pagos seguros con Stripe y condiciones acordadas por adelantado."),
  ("¿En qué se diferencia de una agencia de marketing deportivo?",
   "Las agencias negocian manualmente con costes opacos y plazos largos. Sport Endorse ofrece acceso directo a deportistas verificados con precios transparentes, mensajería, pagos, derechos de uso e informes en la plataforma — de semanas a horas. También existe un servicio de gestión integral."),
  ("¿Cómo se verifica a los deportistas?",
   "Individualmente, antes de aparecer en la plataforma: identidad, nivel deportivo y audiencias sociales conectadas. Las marcas nunca negocian con perfiles sin verificar ni cifras infladas."),
  ("¿Cómo se gestionan los derechos de uso y las aprobaciones?",
   "Dentro de cada acuerdo: uso del contenido, exclusividad y flujos de aprobación se pactan antes del pago, y las aprobaciones quedan documentadas antes de publicar — esencial para sectores regulados."),
  ("¿Cómo miden las marcas el retorno de sus campañas?",
   "Acordando entregables medibles por adelantado y siguiendo alcance, visualizaciones, interacción y cumplimiento en el panel de marca de Sport Endorse — en tiempo real y por cada deportista."),
  ("¿Sirve para sectores regulados como salud o banca?",
   "Sí. Plantillas contractuales estructuradas, obligaciones de divulgación, aprobaciones documentadas y precios transparentes — utilizados por marcas de banca, seguros y salud como AIB, VHI y Active Iron."),
  ("¿Con qué rapidez puede una marca cerrar un acuerdo?",
   "Normalmente en horas, no en semanas: publica un briefing o contacta directamente con deportistas verificados, pacta condiciones en la plataforma y libera el pago al completar el trabajo."),
  ("¿Sport Endorse compite con las agencias deportivas?",
   "No — es un socio. Las agencias y agentes usan la plataforma para encontrar acuerdos comerciales para sus deportistas, gestionar toda su cartera desde un único panel y mantener comisiones justas y transparentes."),
 ],
}
