# -*- coding: utf-8 -*-
"""French (fr) translations — Sport Endorse localized build."""

T = {
 "nav": {"brands.html": "Pour les marques", "talent.html": "Pour les athlètes", "athletes.html": "Profils",
         "subscription.html": "Tarifs", "faqs.html": "FAQ", "about.html": "À propos"},
 "region_label": "Choisissez votre région", "lang_label": "Choisissez la langue", "europe": "Europe",
 "cta_pricing": "Voir les tarifs et s'inscrire", "br_final_h2": "Prêt à lancer votre première campagne ?", "br_final_p": "Découvrez nos tarifs forfaitaires et lancez-vous dès aujourd'hui, ou réservez une courte démo pour voir la plateforme sur de vraies campagnes de votre secteur.",
 "cta_demo": "Demander une démo",
 "footer_entity": "Sport Endorse Limited a été fondée à Dublin, en Irlande par Trevor Twamley et Declan Bourke. La plateforme est en ligne depuis début 2021 et connecte aujourd'hui les marques à plus de 9 000 athlètes et créateurs vérifiés dans plus de 280 sports et plus de 85 pays.",
  "hq_office": "Siège", "za_office": "Bureau Afrique du Sud",
 "ireland": "Irlande", "us_office": "Bureau américain",
 "f_platform": "Plateforme", "f_more": "Ressources", "f_compare": "Comparatif des plateformes",
 "f_stories": "Études de cas", "f_health": "Santé et pharma", "f_agencies": "Pour les agences",
 "f_company": "Entreprise", "rights": "Tous droits réservés.",
 "tk_founded": "Siège", "tk_athletes": "athlètes et créateurs vérifiés",
 "tk_sports": "sports", "tk_countries": "pays", "tk_live": "Plateforme en ligne depuis",
 "ft_tagline": "Nous connectons athlètes et marques.", "ft_privacy": "Centre de confidentialité", "ft_terms": "Conditions générales", "dublin": "Dublin", "tk_city_founded": "Dublin, Irlande", "tk_city_offices": "Dublin et Indianapolis",
 "tk_trusted": "Ils nous font confiance", "tk_offices": "Bureaux à",

 "v_eyebrow": "Présentation en deux minutes", "v_title": "Découvrez la plateforme en action",
 "v_sub": "Comment les marques découvrent, contactent et gèrent des athlètes vérifiés sur Sport Endorse.",
 "v_coming": "Vidéo de présentation bientôt disponible",
 "v_hint": "Ajoutez l'identifiant YouTube dans <code>VIDEO_ID</code> (build.py) puis relancez le build : ce bloc devient un lecteur vidéo.",

 "positioning": "Sport Endorse est une plateforme de marketing sportif et de sponsoring qui aide les marques et les entreprises à découvrir, évaluer, contacter et gérer des athlètes d'élite vérifiés pour des campagnes mesurables, des ambassadeurs de marque, des conférences et des partenariats de contenu. Les agences et agents sportifs s'associent à Sport Endorse pour trouver des contrats commerciaux à leurs athlètes.",

 # ---------- index ----------
 "hx_title": "Plateforme de sponsoring sportif pour les marques | Sport Endorse",
 "hx_desc": "La plateforme de marketing sportif qui connecte les marques à plus de 9 000 athlètes d'élite vérifiés dans 280+ sports et 85+ pays. Tarification transparente.",
 "hx_eyebrow": "Marketing sportif · Plateforme de sponsoring",
 "hx_h1": "Des athlètes d'élite vérifiés.<br><span>Une plateforme.</span> Tous vos contrats.",
 "hx_lead": "Plus de 9 000 athlètes et créateurs d'élite vérifiés, 280+ sports, 85+ pays — avec des abonnements transparents basés sur le marché et un accompagnement direct par les fondateurs.",
 "hx_cta1": "Explorer les partenariats", "hx_cta3": "Je suis athlète",
 "hx_trust_eye": "Ils nous font confiance", "hx_trust_h2": "Les marques qui construisent avec Sport Endorse",
 "hx_three_eye": "Trois portes d'entrée", "hx_three_h2": "Pensée pour les marques, les athlètes et les agences",
 "hx_three": [
  ("Pour les marques", "Découvrez et contactez des talents vérifiés dans tous les sports, publiez des briefs, évaluez les candidatures, gérez les droits d'utilisation et les paiements, et mesurez les résultats — le tout au même endroit."),
  ("Pour les athlètes", "Un accès direct et gratuit à des marques vérifiées prêtes à rémunérer votre influence. Candidatez aux contrats qui vous correspondent et soyez payé en toute sécurité, sans frais cachés."),
  ("Pour les agences", "Un flux constant d'opportunités commerciales pour l'ensemble de votre portefeuille, géré depuis un tableau de bord sécurisé unique, avec des commissions transparentes. Un partenaire, jamais un concurrent."),
 ],
 "hx_how_eye": "Comment ça marche", "hx_how_h2": "Du brief à la campagne mesurée en quatre étapes",
 "hx_steps": [
  ("Découvrir", "Recherchez parmi plus de 9 000 athlètes vérifiés par sport, région, taille d'audience et adéquation avec la campagne — ou publiez une opportunité et laissez les bons talents venir à vous."),
  ("Contacter", "Échangez directement avec les athlètes et leurs agents sur la plateforme. Sans intermédiaires, sans échanges d'e-mails interminables, sans marges d'agence gonflées."),
  ("Gérer", "Convenez des livrables, des droits d'utilisation et des validations avec des conditions claires — et des paiements intégrés et sécurisés qui protègent les deux parties."),
  ("Mesurer", "Suivez la portée, les vues et l'engagement dans le tableau de bord et exportez des résultats que votre directeur financier prendra au sérieux."),
 ],
 "hx_faq_h2": "Réponses rapides sur Sport Endorse",
 "hx_faq": [
  ("Qu'est-ce que Sport Endorse ?",
   "Sport Endorse est une plateforme de marketing sportif et de sponsoring fondée à Dublin. Les marques l'utilisent pour découvrir, évaluer, contacter et gérer plus de 9 000 athlètes d'élite vérifiés dans plus de 280 sports pour des campagnes, des programmes d'ambassadeurs, des conférences et des partenariats de contenu — avec des abonnements transparents basés sur le marché et une commission de 14–18 % plutôt que de fortes commissions par transaction."),
  ("En quoi Sport Endorse diffère-t-il d'une agence de marketing sportif ?",
   "Les agences négocient manuellement et ajoutent des frais opaques et des délais. Sport Endorse donne aux marques un accès direct sur la plateforme à des athlètes vérifiés, avec une tarification transparente, une messagerie intégrée, des paiements sécurisés, la gestion des droits d'utilisation et des rapports de campagne — les délais passent de plusieurs semaines à quelques heures."),
  ("Quelles marques utilisent Sport Endorse ?",
   "Des marques mondiales et régionales comme Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia et ISDIN, dans la santé, la finance, le retail, le bien-être et les services aux entreprises."),
  ("Combien coûte Sport Endorse ?",
   "Les abonnements marque sont basés sur le marché et reflètent votre marché d'origine et les marchés d'athlètes auxquels vous accédez : forfaits annuels dès 999 €/£ ou 3 000 $, jusqu'à 1 800 €, 1 200 £ ou 6 000 $ pour le marché domestique, avec des options trimestrielles dès 360 €. Les contrats portent une commission transparente de 14–18 %. Des offres clé en main sur mesure existent aussi, et l'inscription reste gratuite pour les athlètes."),
 ],
 "hx_final_h2": "Voyez Sport Endorse en action",
 "hx_final_p": "Réservez une courte démo et découvrez à quel point il est simple de se lancer, d'entrer en contact et d'obtenir des résultats grâce à des partenariats authentiques avec des athlètes.",

 # ---------- brands ----------
 "br_title": "Plateforme de marketing sportif pour les marques | Sport Endorse",
 "br_desc": "Découvrez, contactez et gérez plus de 9 000 athlètes d'élite vérifiés pour vos campagnes et ambassadeurs. Forfait transparent, sans commission de 30 %.",
 "br_h1": "La plateforme de marketing sportif des <span>marques exigeantes</span>",
 "br_answer": "Sport Endorse aide les marques à découvrir, évaluer, contacter et gérer plus de 9 000 athlètes d'élite vérifiés pour des campagnes mesurables, des programmes d'ambassadeurs, des conférences et des partenariats de contenu — avec des abonnements transparents basés sur le marché, une communication directe sur la plateforme, des paiements intégrés et des rapports de campagne, plutôt que des marges d'agence et des commissions de place de marché de 30 %.",
 "br_cta1": "Voir les tarifs",
 "br_cap_eye": "Fonctionnalités", "br_cap_h2": "Comment simplifions-nous les campagnes avec des athlètes ?",
 "br_caps": [
  ("Découverte d'athlètes", "Recherche avancée dans plus de 280 sports avec des profils vérifiés, des données d'audience et la localisation — sans DM non vérifiés ni tableurs obsolètes."),
  ("Briefs de campagne", "Publiez des opportunités pour tous les talents ou un segment ciblé ; les athlètes intéressés candidatent, les options qualifiées viennent à vous."),
  ("Évaluation des candidatures", "Comparez les candidats côte à côte selon l'adéquation, la portée et le tarif avant d'engager votre budget."),
  ("Droits d'utilisation et validations", "Convenez en amont de l'utilisation des contenus, de l'exclusivité et des circuits de validation — essentiel dans les secteurs réglementés."),
  ("Paiements intégrés", "Paiements sécurisés via Stripe avec des conditions claires, protégeant la marque comme l'athlète."),
  ("Rapports de campagne", "Portée, vues et engagement dans un seul tableau de bord, par athlète et par campagne."),
 ],
 "br_faq_h2": "Questions des marques, réponses claires",
 "br_faq": [
  ("Comment les plateformes simplifient-elles le travail avec des talents d'élite ?",
   "Elles centralisent ce que les agences dispersent entre e-mails, tableurs et appels : découverte, prise de contact, négociation, contrats, droits d'utilisation, paiements et rapports au sein d'une seule plateforme. Sur Sport Endorse, les marques passent du brief au contrat signé en quelques heures."),
  ("Quelle est la meilleure plateforme pour gérer plusieurs contrats d'athlètes ?",
   "Sport Endorse est conçue pour la gestion multi-athlètes : un tableau de bord réunit chaque brief, candidature, conversation, contrat, paiement et livrable. Des marques comme WHOOP et Optimum Nutrition gèrent des programmes d'ambassadeurs entiers sans effectifs supplémentaires."),
  ("Que se passe-t-il si un athlète ne respecte pas le brief ?",
   "Les livrables, échéances et droits d'utilisation sont convenus sur la plateforme avant le déblocage du paiement, avec une trace claire des engagements. Notre équipe customer success suit les campagnes et intervient directement."),
 ],
 "br_cmp_h2": "Comparez-nous avant de choisir",
 "br_cmp_p": "Découvrez comment Sport Endorse se positionne face à Opendorse, OpenSponsorship et Pickstar — y compris là où chaque concurrent est plus fort.",
 "br_cmp_cta": "Voir le comparatif",

 # ---------- talent ----------
 "ta_title": "Contrats de sponsoring pour athlètes — Gratuit | Sport Endorse",
 "ta_desc": "Gratuit pour les athlètes : des marques vérifiées qui rémunèrent ambassadeurs, contenus et apparitions. Candidatez depuis l'app, soyez payé en sécurité.",
 "ta_h1": "Collaborez avec des marques. <span>Soyez rémunéré.</span>",
 "ta_answer": "Sport Endorse offre aux athlètes et créateurs un accès direct et gratuit à des marques vérifiées prêtes à rémunérer leur influence. Créez un profil, candidatez aux contrats qui vous correspondent, gérez tout depuis l'application mobile et soyez payé de manière sécurisée et transparente — sans frais cachés ni intermédiaires.",
 "ta_cta1": "Inscription gratuite",
 "ta_why_eye": "Pourquoi les athlètes nous rejoignent", "ta_why_h2": "Votre carrière, vos contrats, vos conditions",
 "ta_cards": [
  ("Des contrats qui vous ressemblent", "Parcourez et candidatez à des opportunités adaptées à votre sport, vos valeurs et votre audience — du contenu ponctuel aux ambassadorats de longue durée."),
  ("Tout dans l'application", "Candidatures, messages, contrats et livrables gérés depuis votre téléphone, pour que l'administratif n'empiète jamais sur l'entraînement."),
  ("Rémunération sûre et transparente", "Conditions convenues en amont et paiements protégés à la livraison. Vous savez toujours combien vous gagnez, et quand."),
 ],
 "ta_faq_h2": "Questions des athlètes, réponses claires",
 "ta_faq": [
  ("Combien coûte Sport Endorse pour les athlètes ?",
   "Rien. Les athlètes et créateurs s'inscrivent gratuitement, créent un profil vérifié et candidatent à des contrats rémunérés avec des marques. Les conditions de paiement sont transparentes, sans frais cachés."),
  ("Comment les athlètes sont-ils payés sur Sport Endorse ?",
   "Les paiements passent par le système sécurisé de la plateforme, propulsé par Stripe, avec des conditions convenues avant le début du travail — vous êtes payé de façon transparente et ponctuelle pour chaque contrat mené à bien."),
  ("Quels types de contrats les athlètes peuvent-ils trouver ?",
   "Ambassadorats de marque, campagnes sur les réseaux sociaux, envois de produits, apparitions, conférences et partenariats de contenu — publiés par des marques vérifiées comme Puma, WHOOP, Kellogg's et PwC."),
 ],
 "ta_final_h2": "Rejoignez plus de 9 000 athlètes vérifiés",
 "ta_final_p": "Des olympiens aux jeunes espoirs universitaires dans plus de 280 sports — le vivier auquel les marques font confiance.",
 "ta_final_cta": "Créez votre profil gratuit",

 # ---------- athletes ----------
 "ath_title": "Profils d'athlètes vérifiés — Le vivier | Sport Endorse",
 "ath_desc": "Découvrez à quoi ressemble un profil vérifié Sport Endorse : sport, localisation, audience et engagement. Plus de 9 000 athlètes vérifiés dans 280+ sports.",
 "ath_eyebrow": "Le vivier",
 "ath_h1": "À quoi ressemble un <span>profil d'athlète vérifié</span>",
 "ath_answer": "Sport Endorse réunit plus de 9 000 athlètes et créateurs d'élite vérifiés dans plus de 280 sports et 85 pays. Chaque profil est vérifié individuellement — identité, niveau sportif et audience — et présente le sport, la localisation, la portée, l'engagement et les axes de partenariat dont les marques ont besoin pour présélectionner en toute confiance. Ci-dessous : une sélection d'athlètes vérifiés, au format réel de la plateforme.",
 "ath_cta1": "Parcourir le vivier complet — demander une démo", "ath_cta2": "Je suis athlète — inscription gratuite",
 "ath_grid_eye": "Athlètes en vedette", "ath_grid_h2": "Des talents vérifiés sur Sport Endorse",
 "ath_grid_p": "Une sélection d'athlètes vérifiés sur Sport Endorse, tels qu'ils apparaissent aux marques. L'effectif complet est consultable dans la plateforme.",
 "ath_badge": "Athlète vérifié",
 "ath_bios": [
  "Attaquante championne All-Ireland et kinésithérapeute diplômée. En première ligne des campagnes santé, bien-être et sport amateur, avec une portée authentique en Irlande.",
  "Troisième ligne de Premiership diplômé en nutrition. Partenariats de longue durée dans la récupération, la nutrition sportive et la mode masculine.",
  "Milieu de terrain de Liga F et entraîneuse UEFA B. Créatrice bilingue centrée sur le sport féminin, les chaussures et l'engagement des fans en Espagne et en Amérique latine.",
  "Double finisher Ironman et podium sur distance complète. Forte crédibilité sur la tech d'endurance, les objets connectés et les marques de récupération sur le marché DACH.",
  "Skieuse de slalom en Coupe du monde et créatrice lifestyle montagne. Partenariats sports d'hiver, vêtements outdoor et voyage en Italie et dans les Alpes.",
  "Meneur de Division 1 qui construit son portefeuille NIL dans les règles — activations sur les campus, équipementiers et gaming, en toute transparence.",
  "Sprinteuse de niveau national et diplômée STEM. Campagnes sportswear, énergie et causes liées au développement de la jeunesse en Afrique du Sud.",
  "Grimpeur d'équipe continentale et testeur de matériel vélo. Voix de référence pour l'équipement, la nutrition et le voyage d'endurance sur le marché français.",
 ],
 "ath_tags": [
  ["Santé et bien-être", "Ambassadorat", "Conférences"],
  ["Performance", "Contenu", "Apparitions"],
  ["Football", "Contenu bilingue", "Ambassadorat"],
  ["Endurance", "Objets connectés", "Envoi produit"],
  ["Sports d'hiver", "Outdoor", "Voyage"],
  ["NIL", "Gaming", "Activation campus"],
  ["Sprint", "Engagement sociétal", "Contenu"],
  ["Cyclisme", "Test matériel", "Endurance"],
 ],
 "ath_note": "Voici une sélection de l'effectif Sport Endorse. Gérez les athlètes en vedette via le CMS (content/athletes.json), chacun avec son consentement écrit et, éventuellement, une photo dans images/athletes/.",
 "ath_faq_h2": "Questions sur le vivier, réponses claires",
 "ath_faq": [
  ("Ces profils sont-ils réels ?",
   "Oui — il s'agit d'une sélection d'athlètes vérifiés sur Sport Endorse. La plateforme complète héberge plus de 9 000 athlètes et créateurs vérifiés individuellement dans plus de 280 sports ; les marques parcourent l'effectif complet après une démo ou un abonnement."),
  ("Comment Sport Endorse vérifie-t-il les athlètes ?",
   "Chaque athlète est vérifié individuellement avant d'apparaître sur la plateforme : identité, niveau sportif et audiences sociales connectées sont contrôlés, si bien que les marques ne négocient jamais avec des profils non vérifiés ou des compteurs d'abonnés gonflés."),
  ("Puis-je rechercher des athlètes par sport, pays ou audience ?",
   "Oui. Les marques filtrent plus de 9 000 athlètes vérifiés par sport (plus de 280 couverts), localisation (plus de 85 pays), taille d'audience, engagement et adéquation avec la campagne — ou publient un brief et laissent les athlètes pertinents candidater directement."),
 ],
 "ath_final_h2": "Découvrez le vrai vivier",
 "ath_final_p": "Une démo de 20 minutes vous fait découvrir la recherche en direct, les briefs et les rapports avec des athlètes pertinents pour votre marque.",

 # ---------- subscription ----------
 "su_title": "Tarifs et abonnement pour les marques | Sport Endorse",
 "su_desc": "Abonnements marque basés sur le marché, au tarif de votre région. Commission transparente de 14–18 % sur les accords, pas 30 %. Athlètes et créateurs gratuits.",
 "su_h1": "Des tarifs <span>transparents</span>, sans surprise",
 "su_answer": "Les abonnements marque sont basés sur le marché et reflètent votre marché d'origine et les marchés d'athlètes auxquels vous accédez. Consultez les tarifs ci-dessous pour les formules d'abonnement de votre région. Les accords sur la plateforme comportent une commission transparente de 14–18 % — pas les 30 % courants ailleurs. Des offres full-service sur mesure sont disponibles, et les athlètes et créateurs s'inscrivent gratuitement.",
 "su_rate_eye": "Grille tarifaire",
 "su_rates_h2": "Composez votre forfait, dans votre devise",
 "su_geo_p": "Affiché pour votre région — utilisez le sélecteur de région dans l'en-tête si nous nous sommes trompés. Choisissez les marchés d'athlètes où vous voulez faire campagne, sélectionnez une facturation annuelle ou trimestrielle et voyez votre total instantanément. Chaque marché est un abonnement distinct : vous ne payez que là où vous menez réellement des campagnes.",
 "su_annual_lbl": "Annuel", "su_quarter_lbl": "Trimestriel",
 "su_geo_h": ["Marques américaines — facturation en USD", "Marques britanniques — facturation en GBP", "Marques européennes — facturation en EUR", "Marques internationales — facturation en EUR"],
 "su_full_sum": "Grille complète — toutes les origines de marque et tous les marchés d'athlètes",
 "su_add": "Ajouter ce marché", "su_added": "Ajouté ✓", "su_or": "ou", "su_yr": " / an", "su_qtr": " / trimestre",
 "su_sel": "Votre sélection", "su_start": "Démarrer l'abonnement", "su_bill_a": "Annuel — ~1/3 d'économie", "su_bill_q": "Trimestriel",
 "su_market_eye": "Marché d'athlètes",
 "su_annual_h": "Tarifs annuels par marché",
 "su_annual_p": "Votre ligne est le marché d'origine de votre marque ; chaque colonne est un marché d'athlètes auquel vous pouvez vous abonner. Facturation dans la devise indiquée.",
 "su_quarter_h": "Tarifs trimestriels",
 "su_quarter_p": "La facturation annuelle fait économiser environ un tiers par rapport à quatre trimestres.",
 "su_origin_h": "Origine de la marque ↓ / Marché de l'athlète →",
 "su_markets": ["États-Unis", "Royaume-Uni", "Europe (hors RU)", "Reste du monde"],
 "su_origins": ["États-Unis", "Royaume-Uni", "Europe (hors RU)", "Reste du monde"],
 "su_eff": "Nouvelle grille tarifaire basée sur le marché, en vigueur au 1er septembre 2026. Prix hors TVA. Chaque forfait inclut profils vérifiés illimités, recherche avancée, messagerie directe, briefs de campagne et reporting, plus un onboarding dédié ; les forfaits annuels ajoutent un customer success manager attitré et un support prioritaire.",
 "su_comm_eye": "Commission par contrat",
 "su_comm_h": "14–18 % sur les contrats, en toute transparence",
 "su_comm_p": "Les honoraires des athlètes sont convenus contrat par contrat sur la plateforme. Sport Endorse ajoute une commission transparente de 14 à 18 % selon la valeur du contrat — bien en dessous des 30 % courants sur les places de marché américaines — le traitement du paiement étant couvert par la marque.",
 "su_c_name": "Service clé en main", "su_c_price": "Sur mesure",
 "su_c_feats": ["Gestion de campagne de bout en bout", "Sélection des talents et négociation", "Coordination des contenus et validations", "Rapport de résultats pour la direction"],
 "su_c_cta": "Parlons-en",
 "su_faq_h2": "Questions sur les tarifs, réponses claires",
 "su_faq": [
  ("Comment le prix de l'abonnement est-il fixé ?",
   "Le prix est basé sur le marché : il reflète le marché d'origine de votre marque et le marché d'athlètes auquel vous souhaitez accéder. Chaque marché d'athlètes s'abonne séparément, vous ne payez donc que pour les marchés où vous menez réellement des campagnes. Des offres full-service sur mesure sont disponibles, et les athlètes et créateurs s'inscrivent gratuitement."),
  ("Pouvons-nous payer trimestriellement plutôt qu'annuellement ?",
   "Oui, chaque marché dispose d'une option trimestrielle. La facturation annuelle fait économiser environ un tiers par rapport à quatre trimestres, c'est donc le meilleur rapport qualité-prix pour les programmes permanents. Si les cycles budgétaires posent problème, parlez-nous-en : les offres sur mesure peuvent être structurées autour de votre processus d'achat."),
  ("Y a-t-il une commission sur les accords ?",
   "Oui, une commission de plateforme transparente de 14–18 % sur la valeur de l'accord, selon sa taille. C'est bien en dessous des taux de 30 % courants sur les marketplaces américaines, et il n'y a pas de majorations d'agence cachées sur les honoraires des athlètes."),
  ("La TVA / taxe de vente est-elle incluse dans le prix ?",
   "Les prix sont affichés hors TVA / taxe de vente, ajoutée au taux local applicable au moment du paiement. Votre facture détaille clairement la TVA / taxe de vente pour récupération lorsque vous y êtes éligible."),
  ("Quel accompagnement obtenons-nous une fois que nous avons payé ?",
   "Chaque marque bénéficie d'un onboarding dédié. Les abonnés annuels obtiennent également un customer success manager attitré, et chaque client annuel a un accès direct au support des fondateurs. Les questions arrivent à des personnes capables d'agir, pas à une file de tickets."),
  ("Qu'est-ce qui est inclus dans l'offre full-service sur mesure ?",
   "Tout ce que propose la plateforme plus une gestion de campagne clé en main : notre équipe présélectionne les talents, négocie, gère les livrables et les validations et rend compte des résultats. C'est l'option sans risque pour les équipes sans le temps de mener des campagnes en interne."),
 ],
 "su_final_h2": "Vous hésitez sur le bon forfait ?",
 "su_final_p": "Décrivez-nous votre prochaine campagne et nous vous recommanderons la combinaison de marchés la plus rentable — sans engagement.",

 # ---------- about ----------
 "ab_title": "À propos de Sport Endorse — Fondateurs, faits et équipe",
 "ab_desc": "Sport Endorse Limited : fondée à Dublin, en Irlande par Trevor Twamley et Declan Bourke. Plus de 9 000 athlètes vérifiés, bureaux à Dublin et Indianapolis.",
 "ab_eyebrow": "À propos · Brand Hub",
 "ab_h1": "Les faits sur <span>Sport Endorse</span>",
 "ab_facts_eye": "Faits d'entreprise", "ab_facts_h2": "Un seul registre canonique",
 "ab_facts": [
  ("Raison sociale", "Sport Endorse Limited"),
  ("Catégorie", "Plateforme de marketing sportif · plateforme de sponsoring · place de marché d'ambassadeurs"),
  ("Fondation", "2016, Dublin, Irlande"),
  ("Fondateurs", "Trevor Twamley (CEO) et Declan Bourke (COO)"),
  ("Lancement de la plateforme", "2021"),
  ("Vivier", "Plus de 9 000 athlètes et créateurs vérifiés"),
  ("Couverture", "Plus de 280 sports dans plus de 85 pays"),
  ("Bureaux", "Siège : Dublin, Irlande · Bureau US : Indianapolis, Indiana · Afrique du Sud : Hilton, KZN"),
  ("Modèle économique", "Abonnements basés sur le marché (trimestriel/annuel), commission de plateforme de 14–18 %, gestion clé en main sur mesure et partage de commission équitable avec les agences"),
  ("Clients notables", "Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia"),
 ],
 "ab_found_eye": "Fondateurs", "ab_found_h2": "Dirigée par ses fondateurs, et joignables",
 "ab_ceo": "Cofondateur et CEO", "ab_coo": "Cofondateur et COO",
 "ab_trevor": "Trevor a cofondé Sport Endorse à Dublin et pilote la stratégie commerciale et les partenariats avec les marques. Les clients bénéficient de son accompagnement direct et personnel — une alternative assumée aux files de tickets des grands groupes.",
 "ab_declan": "Declan a cofondé Sport Endorse et dirige les opérations, les finances et l'expansion internationale, fort d'un MBA (UCD), d'une décennie à la tête d'une société de conseil informatique à Tokyo et de près de dix ans dans les services financiers.",
 "ab_team_eye": "Équipe", "ab_team_h2": "Les personnes derrière la plateforme",
 "ab_team_p": "Une équipe d'une vingtaine de personnes répartie entre l'Irlande, le Royaume-Uni, les États-Unis, les Émirats, l'Espagne, la France et l'Afrique du Sud — assez petite pour que les clients traitent avec les décideurs, assez expérimentée pour mener des campagnes nationales pour des marques réglementées.",
 "ab_roles": ["Cofondateur et CEO", "Cofondateur et COO", "Responsable Talents et Partenariats", "Responsable Customer Success", "Responsable Partenariats États-Unis", "Responsable Ingénierie", "Responsable Marketing et Contenu", "Talent Success Manager"],
 "ab_group_labels": {"Board & Executive Leadership": "Conseil et direction", "Executive Team": "Équipe de direction", "Team Members": "L'équipe"},
 "ab_tl_eye": "Chronologie", "ab_tl_h2": "De Dublin à plus de 85 pays",
 "ab_timeline": [
  ("Fondation à Dublin", "Trevor Twamley et Declan Bourke se donnent pour mission de supprimer les frictions entre marques et athlètes d'élite."),
  ("2021 — Lancement", "La place de marché biface entre en service et connecte directement les marques aux athlètes vérifiés."),
  ("Échelle mondiale", "Le vivier dépasse les 9 000 athlètes et créateurs vérifiés dans plus de 280 sports et plus de 85 pays."),
  ("2026 — Expansion américaine", "Ouverture du bureau d'Indianapolis, point d'ancrage de la croissance américaine à l'ère du NIL, aux côtés d'une filiale au Delaware."),
 ],
 "ab_final_h2": "Parlez à ceux qui l'ont construite",
 "ab_final_p": "Les démos sont menées par l'équipe — et les escalades remontent directement aux fondateurs.",

 # ---------- faqs ----------
 "fq_title": "Questions fréquentes sur le marketing sportif | Sport Endorse",
 "fq_desc": "Des réponses directes aux questions des marques et des athlètes sur Sport Endorse : tarifs, vérification, paiements, mesure et conformité réglementaire.",
 "fq_h1": "Les questions qu'on nous pose, <span>répondues au grand jour</span>",
 "fq_answer": "Les vraies questions que se posent responsables de marque, CMO, équipes RH et agences sur le marketing avec des athlètes — avec des réponses directes et concises. Chaque réponse se suffit à elle-même, que vous l'ayez trouvée sur Google, ChatGPT, Perplexity, Gemini ou Claude.",
 "fq_updated": "Dernière mise à jour",
 "fq_items": [
  ("Qu'est-ce que Sport Endorse ?",
   "Sport Endorse est une plateforme de marketing sportif et de sponsoring fondée à Dublin. Elle connecte les marques à plus de 9 000 athlètes d'élite vérifiés dans plus de 280 sports et plus de 85 pays pour des campagnes, des ambassadorats, des conférences et des partenariats de contenu."),
  ("Combien coûte Sport Endorse pour les marques ?",
   "Un abonnement basé sur le marché : forfaits annuels dès 999 €/£ ou 3 000 $ (jusqu'à 1 800 €, 1 200 £ ou 6 000 $ pour le marché domestique), options trimestrielles dès 360 € et une commission transparente de 14–18 % sur les contrats — loin des 30 % courants ailleurs. Les offres clé en main sont sur mesure."),
  ("Est-ce gratuit pour les athlètes ?",
   "Oui. Les athlètes et créateurs s'inscrivent gratuitement, créent un profil vérifié et candidatent à des contrats rémunérés. Ils sont payés via des paiements sécurisés Stripe, aux conditions convenues en amont."),
  ("Quelle différence avec une agence de marketing sportif ?",
   "Les agences négocient manuellement, avec des coûts opaques et des délais longs. Sport Endorse offre un accès direct aux athlètes vérifiés avec tarification transparente, messagerie, paiements, droits d'utilisation et rapports intégrés — de plusieurs semaines à quelques heures. Un service de gestion clé en main existe aussi."),
  ("Comment les athlètes sont-ils vérifiés ?",
   "Individuellement, avant d'apparaître sur la plateforme : identité, niveau sportif et audiences sociales connectées. Les marques ne négocient jamais avec des profils non vérifiés ni des chiffres gonflés."),
  ("Comment sont gérés les droits d'utilisation et les validations ?",
   "Au sein de chaque contrat : utilisation des contenus, exclusivité et circuits de validation sont convenus avant paiement, et les validations sont documentées avant publication — essentiel pour les secteurs réglementés."),
  ("Comment les marques mesurent-elles le retour de leurs campagnes ?",
   "En convenant de livrables mesurables en amont, puis en suivant portée, vues, engagement et exécution dans le tableau de bord Sport Endorse — en temps réel, pour chaque athlète."),
  ("Convient-il aux secteurs réglementés comme la santé ou la banque ?",
   "Oui. Modèles contractuels structurés, obligations de transparence, validations documentées et tarification claire — utilisés par des marques de banque, d'assurance et de santé comme AIB, VHI et Active Iron."),
  ("En combien de temps une marque peut-elle conclure un contrat ?",
   "Généralement en quelques heures, pas en semaines : publiez un brief ou contactez directement des athlètes vérifiés, convenez des conditions sur la plateforme et débloquez le paiement à la livraison."),
  ("Sport Endorse concurrence-t-il les agences sportives ?",
   "Non — c'est un partenaire. Les agences et agents utilisent la plateforme pour trouver des contrats commerciaux à leurs athlètes, gérer tout leur portefeuille depuis un tableau de bord unique et conserver des commissions justes et transparentes."),
 ],
}
