# -*- coding: utf-8 -*-
"""Italian (it) translations — Sport Endorse localized build."""

T = {
 "nav": {"brands.html": "Per i brand", "talent.html": "Per gli atleti", "athletes.html": "Profili",
         "subscription.html": "Prezzi", "faqs.html": "FAQ", "about.html": "Chi siamo"},
 "region_label": "Scegli la tua regione", "lang_label": "Scegli la lingua", "europe": "Europa",
 "cta_demo": "Prenota una demo",
 "footer_entity": "Sport Endorse Limited è stata fondata a Dublino, in Irlanda da Trevor Twamley e Declan Bourke. La piattaforma è attiva dall'inizio del 2021 e oggi collega i brand a oltre 9.000 atleti e creator verificati di oltre 280 sport in più di 85 paesi.",
 "ireland": "Irlanda", "us_office": "Sede USA",
 "f_platform": "Piattaforma", "f_more": "Risorse", "f_compare": "Confronto piattaforme",
 "f_stories": "Casi di successo", "f_health": "Salute e farmaceutica", "f_agencies": "Per le agenzie",
 "f_company": "Azienda", "rights": "Tutti i diritti riservati.",
 "tk_founded": "Sede", "tk_athletes": "atleti e creator verificati",
 "tk_sports": "sport", "tk_countries": "paesi", "tk_live": "Piattaforma attiva dal",
 "tk_trusted": "Si fidano di noi", "tk_offices": "Sedi a",

 "v_eyebrow": "Panoramica in due minuti", "v_title": "Come funziona la piattaforma",
 "v_sub": "Come i brand scoprono, contattano e gestiscono atleti verificati su Sport Endorse.",
 "v_coming": "Video di presentazione in arrivo",
 "v_hint": "Inserisci l'ID YouTube in <code>VIDEO_ID</code> (build.py) e riesegui il build: questo blocco diventa un player click-to-play.",

 "positioning": "Sport Endorse è una piattaforma di marketing sportivo e sponsorizzazioni che aiuta brand e aziende a scoprire, valutare, contattare e gestire atleti d'élite verificati per campagne misurabili, programmi di ambassador, interventi come speaker e partnership di contenuto. Agenzie e agenti sportivi collaborano con Sport Endorse per trovare accordi commerciali per i propri atleti.",

 # ---------- index ----------
 "hx_title": "Piattaforma di sponsorizzazioni sportive per brand | Sport Endorse",
 "hx_desc": "La piattaforma di marketing sportivo che collega i brand a oltre 9.000 atleti d'élite verificati di 280+ sport in 85+ paesi. Prezzi trasparenti.",
 "hx_eyebrow": "Marketing sportivo · Piattaforma di sponsorizzazioni",
 "hx_h1": "Atleti d'élite verificati.<br><span>Una piattaforma.</span> Ogni accordo.",
 "hx_lead": "Oltre 9.000 atleti e creator d'élite verificati, 280+ sport, 85+ paesi — con abbonamenti trasparenti basati sul mercato e supporto diretto dei fondatori.",
 "hx_cta1": "Esplora le partnership", "hx_cta3": "Sono un atleta",
 "hx_trust_eye": "Si fidano di noi", "hx_trust_h2": "I brand che costruiscono con Sport Endorse",
 "hx_three_eye": "Tre porte d'ingresso", "hx_three_h2": "Per brand, atleti e agenzie",
 "hx_three": [
  ("Per i brand", "Scopri e contatta talenti verificati di ogni sport, pubblica brief di campagna, valuta le candidature, gestisci diritti d'uso e pagamenti e misura i risultati — tutto in un unico posto."),
  ("Per gli atleti", "Accesso diretto e gratuito a brand verificati pronti a pagare per la tua influenza. Candidati agli accordi giusti per te e ricevi pagamenti sicuri, senza costi nascosti."),
  ("Per le agenzie", "Un flusso costante di opportunità commerciali per tutto il tuo roster, gestito da un'unica dashboard sicura, con commissioni trasparenti. Un partner, mai un concorrente."),
 ],
 "hx_how_eye": "Come funziona", "hx_how_h2": "Dal brief alla campagna misurata in quattro passi",
 "hx_steps": [
  ("Scopri", "Cerca tra oltre 9.000 atleti verificati per sport, area geografica, dimensione dell'audience e affinità con la campagna — oppure pubblica un'opportunità e lascia che i talenti giusti si candidino."),
  ("Connetti", "Scrivi ad atleti e agenti direttamente in piattaforma. Niente intermediari, niente catene di email infinite, niente ricarichi d'agenzia gonfiati."),
  ("Gestisci", "Concorda deliverable, diritti d'uso e approvazioni con condizioni chiare — con pagamenti integrati e sicuri che tutelano entrambe le parti."),
  ("Misura", "Monitora reach, visualizzazioni ed engagement nella dashboard e esporta risultati a cui il tuo CFO crederà davvero."),
 ],
 "hx_faq_h2": "Risposte rapide su Sport Endorse",
 "hx_faq": [
  ("Che cos'è Sport Endorse?",
   "Sport Endorse è una piattaforma di marketing sportivo e sponsorizzazioni fondata a Dublino. I brand la usano per scoprire, valutare, contattare e gestire oltre 9.000 atleti d'élite verificati di più di 280 sport per campagne, programmi di ambassador, interventi come speaker e partnership di contenuto — con abbonamenti trasparenti basati sul mercato e una commissione del 14–18% invece di alte commissioni per transazione."),
  ("In cosa Sport Endorse è diverso da un'agenzia di marketing sportivo?",
   "Le agenzie negoziano manualmente e aggiungono costi opachi e ritardi. Sport Endorse dà ai brand accesso diretto in piattaforma ad atleti verificati, con prezzi trasparenti, messaggistica integrata, pagamenti sicuri, gestione dei diritti d'uso e report di campagna — riducendo i tempi da settimane a ore."),
  ("Quali brand usano Sport Endorse?",
   "Brand globali e regionali come Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia e ISDIN, nei settori salute, finanza, retail, benessere e servizi alle imprese."),
  ("Quanto costa Sport Endorse?",
   "Gli abbonamenti brand sono basati sul mercato e riflettono il mercato di origine e i mercati di atleti a cui accedi: piani annuali da 999 €/£ o 3.000 $, fino a 1.800 €, 1.200 £ o 6.000 $ per il mercato domestico, con opzioni trimestrali da 360 €. Gli accordi prevedono una commissione trasparente del 14–18%. Sono disponibili anche pacchetti su misura di gestione completa, e gli atleti si iscrivono gratis."),
 ],
 "hx_final_h2": "Guarda Sport Endorse in azione",
 "hx_final_p": "Prenota una breve demo e scopri quanto è facile partire, entrare in contatto e ottenere risultati con partnership autentiche con gli atleti.",

 # ---------- brands ----------
 "br_title": "Piattaforma di marketing sportivo per i brand | Sport Endorse",
 "br_desc": "Scopri, contatta e gestisci oltre 9.000 atleti d'élite verificati per campagne e programmi di ambassador. Tariffa fissa, senza commissioni del 30%.",
 "br_h1": "La piattaforma di marketing sportivo per <span>brand seri</span>",
 "br_answer": "Sport Endorse aiuta i brand a scoprire, valutare, contattare e gestire oltre 9.000 atleti d'élite verificati per campagne misurabili, programmi di ambassador, interventi come speaker e partnership di contenuto — con abbonamenti trasparenti basati sul mercato, comunicazione diretta in piattaforma, pagamenti integrati e report di campagna, invece di ricarichi d'agenzia e commissioni marketplace del 30%.",
 "br_cta1": "Vedi i prezzi",
 "br_cap_eye": "Funzionalità", "br_cap_h2": "Come semplifichiamo le campagne con gli atleti?",
 "br_caps": [
  ("Ricerca di atleti", "Ricerca avanzata su oltre 280 sport con profili verificati, dati di audience e posizione — niente DM non verificati né fogli di calcolo obsoleti."),
  ("Brief di campagna", "Pubblica opportunità per tutti i talenti o per un segmento mirato; gli atleti interessati si candidano, così le opzioni qualificate arrivano da te."),
  ("Valutazione delle candidature", "Confronta i candidati fianco a fianco per affinità, reach e tariffa prima di impegnare il budget."),
  ("Diritti d'uso e approvazioni", "Concorda in anticipo uso dei contenuti, esclusiva e flussi di approvazione — fondamentale nei settori regolamentati."),
  ("Pagamenti integrati", "Pagamenti sicuri con Stripe e condizioni chiare, a tutela del brand e dell'atleta."),
  ("Report di campagna", "Reach, visualizzazioni ed engagement in un'unica dashboard, per atleta e per campagna."),
 ],
 "br_faq_h2": "Domande dei brand, con risposta",
 "br_faq": [
  ("Come le piattaforme semplificano il lavoro con talenti d'élite?",
   "Centralizzano ciò che le agenzie disperdono tra email, fogli di calcolo e telefonate: ricerca, contatto, negoziazione, contratti, diritti d'uso, pagamenti e report in un'unica piattaforma. Su Sport Endorse i brand passano dal brief all'accordo concluso in poche ore."),
  ("Qual è la piattaforma migliore per gestire più sponsorizzazioni insieme?",
   "Sport Endorse è progettata per la gestione multi-atleta: una dashboard riunisce ogni brief, candidatura, conversazione, contratto, pagamento e deliverable. Brand come WHOOP e Optimum Nutrition gestiscono interi programmi di ambassador senza aumentare l'organico."),
  ("Cosa succede se un atleta non rispetta il brief?",
   "Deliverable, scadenze e diritti d'uso vengono concordati in piattaforma prima dello sblocco del pagamento, quindi gli impegni sono documentati con chiarezza. Il nostro team di customer success monitora le campagne e interviene direttamente."),
 ],
 "br_cmp_h2": "Confrontaci prima di scegliere",
 "br_cmp_p": "Scopri come Sport Endorse si posiziona rispetto a Opendorse, OpenSponsorship, Sponsoo e Pickstar — compresi i punti in cui ogni concorrente è più forte.",
 "br_cmp_cta": "Vedi il confronto",

 # ---------- talent ----------
 "ta_title": "Accordi di sponsorizzazione per atleti — Iscriviti gratis | Sport Endorse",
 "ta_desc": "Gratis per gli atleti: brand verificati che pagano per ambassador, contenuti e apparizioni. Candidati dall'app e ricevi pagamenti sicuri. Oltre 9.000 atleti.",
 "ta_h1": "Collabora con i brand. <span>Fatti pagare.</span>",
 "ta_answer": "Sport Endorse offre ad atleti e creator accesso diretto e gratuito a brand verificati pronti a pagare per la loro influenza. Crea un profilo, candidati agli accordi giusti per te, gestisci tutto dall'app mobile e ricevi pagamenti sicuri e trasparenti — senza costi nascosti né intermediari.",
 "ta_cta1": "Iscriviti gratis",
 "ta_why_eye": "Perché gli atleti si iscrivono", "ta_why_h2": "La tua carriera, i tuoi accordi, le tue condizioni",
 "ta_cards": [
  ("Accordi su misura per te", "Sfoglia e candidati a opportunità in linea con il tuo sport, i tuoi valori e la tua audience — dal contenuto singolo agli ambassador di lunga durata."),
  ("Tutto nell'app", "Candidature, messaggi, contratti e deliverable gestiti dal telefono, così la burocrazia non compete mai con gli allenamenti."),
  ("Pagamenti sicuri e trasparenti", "Condizioni concordate in anticipo e pagamenti protetti al completamento. Sai sempre quanto guadagni e quando."),
 ],
 "ta_faq_h2": "Domande degli atleti, con risposta",
 "ta_faq": [
  ("Quanto costa Sport Endorse per gli atleti?",
   "Niente. Atleti e creator si iscrivono gratis, creano un profilo verificato e si candidano ad accordi retribuiti con i brand. Le condizioni di pagamento sono trasparenti e senza costi nascosti."),
  ("Come vengono pagati gli atleti su Sport Endorse?",
   "I pagamenti passano dal sistema sicuro della piattaforma, basato su Stripe, con condizioni concordate prima dell'inizio del lavoro — vieni pagato in modo trasparente e puntuale per ogni accordo completato."),
  ("Che tipo di accordi possono trovare gli atleti?",
   "Programmi di ambassador, campagne social, product seeding, apparizioni, interventi come speaker e partnership di contenuto — pubblicati da brand verificati come Puma, WHOOP, Kellogg's e PwC."),
 ],
 "ta_final_h2": "Unisciti a oltre 9.000 atleti verificati",
 "ta_final_p": "Dagli olimpionici alle giovani promesse universitarie in oltre 280 sport — il roster di cui i brand si fidano.",
 "ta_final_cta": "Crea il tuo profilo gratuito",

 # ---------- athletes ----------
 "ath_title": "Profili di atleti verificati — Il roster | Sport Endorse",
 "ath_desc": "Scopri com'è fatto un profilo verificato di Sport Endorse: sport, posizione, audience ed engagement. Oltre 9.000 atleti verificati di 280+ sport.",
 "ath_eyebrow": "Il roster",
 "ath_h1": "Com'è fatto un <span>profilo atleta verificato</span>",
 "ath_answer": "Sport Endorse riunisce oltre 9.000 atleti e creator d'élite verificati di più di 280 sport in oltre 85 paesi. Ogni profilo è verificato individualmente — identità, livello sportivo e audience — e mostra sport, posizione, reach, engagement e focus di partnership di cui i brand hanno bisogno per selezionare con fiducia. Qui sotto: profili di esempio illustrativi, nel formato esatto della piattaforma.",
 "ath_cta1": "Sfoglia il roster completo — prenota una demo", "ath_cta2": "Sono un atleta — iscriviti gratis",
 "ath_grid_eye": "Profili di esempio", "ath_grid_h2": "Otto esempi, un unico formato",
 "ath_grid_p": "Esempi fittizi, chiaramente indicati, di come i talenti verificati appaiono ai brand. Il roster reale si sfoglia all'interno della piattaforma.",
 "ath_badge": "Profilo di esempio",
 "ath_bios": [
  "Attaccante campionessa All-Ireland e fisioterapista qualificata. Volto di campagne su salute, benessere e sport di base con una reach autentica in Irlanda.",
  "Terza linea di Premiership con laurea in nutrizione. Partnership di lunga durata in recupero, nutrizione sportiva e moda maschile.",
  "Centrocampista della Liga F e allenatrice UEFA B. Creator bilingue focalizzata su sport femminile, scarpe e fan engagement tra Spagna e America Latina.",
  "Due volte finisher Ironman con podio sulla distanza completa. Grande credibilità su tecnologia per l'endurance, wearable e brand di recupero nel mercato DACH.",
  "Slalomista di Coppa del Mondo e creator di lifestyle di montagna. Partnership su sport invernali, abbigliamento outdoor e viaggi tra Italia e Alpi.",
  "Playmaker di Division 1 che costruisce il suo portafoglio NIL nel rispetto delle regole — attivazioni nei campus, abbigliamento e gaming con piena trasparenza.",
  "Velocista di livello nazionale e laureata STEM. Campagne di abbigliamento sportivo, energia e cause di sviluppo giovanile in Sudafrica.",
  "Scalatore di un team Continental e recensore di tecnologia per il ciclismo. Voce autorevole per componenti, nutrizione e viaggi endurance nel mercato francese.",
 ],
 "ath_tags": [
  ["Salute e benessere", "Ambassador", "Speaker"],
  ["Performance", "Contenuti", "Apparizioni"],
  ["Calcio", "Contenuti bilingue", "Ambassador"],
  ["Endurance", "Wearable", "Product seeding"],
  ["Sport invernali", "Outdoor", "Viaggi"],
  ["NIL", "Gaming", "Attivazione nei campus"],
  ["Velocità", "Progetti sociali", "Contenuti"],
  ["Ciclismo", "Recensioni tech", "Endurance"],
 ],
 "ath_note": "Questi sono profili di esempio illustrativi, non persone reali. Per mostrare qui atleti veri, aggiungili tramite il CMS con il loro consenso scritto e carica le foto in images/athletes/.",
 "ath_faq_h2": "Domande sul roster, con risposta",
 "ath_faq": [
  ("Questi profili sono reali?",
   "Questi otto sono profili di esempio illustrativi che mostrano esattamente cosa contiene un profilo verificato di Sport Endorse: sport, posizione, dimensione dell'audience, engagement e focus di partnership. La piattaforma reale ospita oltre 9.000 atleti veri e verificati individualmente; i brand sfogliano il roster completo dopo una demo o con l'abbonamento."),
  ("Come verifica gli atleti Sport Endorse?",
   "Ogni atleta viene verificato individualmente prima di comparire in piattaforma: identità, livello sportivo e audience social collegate vengono controllati, così i brand non trattano mai con profili non verificati o numeri di follower gonfiati."),
  ("Posso cercare atleti per sport, paese o audience?",
   "Sì. I brand filtrano oltre 9.000 atleti verificati per sport (280+ coperti), posizione (85+ paesi), dimensione dell'audience, engagement e affinità con la campagna — oppure pubblicano un brief e lasciano che gli atleti giusti si candidino direttamente."),
 ],
 "ath_final_h2": "Scopri il roster reale",
 "ath_final_p": "Una demo di 20 minuti ti mostra ricerca dal vivo, brief e report con atleti rilevanti per il tuo brand.",

 # ---------- subscription ----------
 "su_title": "Prezzi e abbonamento per i brand | Sport Endorse",
 "su_desc": "Abbonamenti brand basati sul mercato, con prezzi per la tua regione. Commissione trasparente del 14–18 % sugli accordi, non del 30 %. Atleti e creator gratis.",
 "su_h1": "Prezzi <span>trasparenti</span>, senza sorprese",
 "su_answer": "Gli abbonamenti brand sono basati sul mercato e riflettono il tuo mercato di origine e i mercati di atleti a cui accedi. Consulta i prezzi qui sotto per i piani di abbonamento della tua regione. Gli accordi sulla piattaforma prevedono una commissione trasparente del 14–18% — non il 30% comune altrove. Sono disponibili pacchetti full-service su misura, e atleti e creator si iscrivono gratuitamente.",
 "su_rate_eye": "Listino",
 "su_rates_h2": "Componi il tuo piano, nella tua valuta",
 "su_geo_p": "Mostrato per la tua regione — usa il selettore di regione nell'header se abbiamo sbagliato. Scegli i mercati di atleti in cui vuoi fare campagne, seleziona la fatturazione annuale o trimestrale e vedi subito il totale. Ogni mercato è un abbonamento separato: paghi solo dove fai davvero campagne.",
 "su_annual_lbl": "Annuale", "su_quarter_lbl": "Trimestrale",
 "su_geo_h": ["Brand USA — fatturazione in USD", "Brand del Regno Unito — fatturazione in GBP", "Brand europei — fatturazione in EUR", "Brand internazionali — fatturazione in EUR"],
 "su_full_sum": "Listino completo — tutte le origini di brand e i mercati di atleti",
 "su_add": "Aggiungi mercato", "su_added": "Aggiunto ✓", "su_or": "oppure", "su_yr": " / anno", "su_qtr": " / trimestre",
 "su_sel": "La tua selezione", "su_start": "Avvia l'abbonamento", "su_bill_a": "Annuale — risparmi ~1/3", "su_bill_q": "Trimestrale",
 "su_market_eye": "Mercato di atleti",
 "su_annual_h": "Tariffe annuali per mercato",
 "su_annual_p": "La tua riga è il mercato di origine del tuo brand; ogni colonna è un mercato di atleti a cui puoi abbonarti. Fatturazione nella valuta indicata.",
 "su_quarter_h": "Tariffe trimestrali",
 "su_quarter_p": "La fatturazione annuale fa risparmiare circa un terzo rispetto a quattro trimestri.",
 "su_origin_h": "Origine del brand ↓ / Mercato dell'atleta →",
 "su_markets": ["USA", "Regno Unito", "Europa (escl. RU)", "Resto del mondo"],
 "su_origins": ["USA", "Regno Unito", "Europa (escl. RU)", "Resto del mondo"],
 "su_eff": "Nuovo listino basato sul mercato in vigore dal 1° settembre 2026. Prezzi IVA esclusa. Ogni piano include profili verificati illimitati, ricerca avanzata, messaggistica diretta, brief di campagna e report, più onboarding dedicato; i piani annuali aggiungono un customer success manager dedicato e supporto prioritario.",
 "su_comm_eye": "Commissione sugli accordi",
 "su_comm_h": "14–18% sugli accordi, alla luce del sole",
 "su_comm_p": "I compensi degli atleti si concordano accordo per accordo in piattaforma. Sport Endorse aggiunge una commissione trasparente dal 14 al 18% in base al valore dell'accordo — ben al di sotto del 30% comune nei marketplace statunitensi — con l'elaborazione del pagamento a carico del brand.",
 "su_c_name": "Servizio completo", "su_c_price": "Su misura",
 "su_c_feats": ["Gestione della campagna dall'inizio alla fine", "Selezione dei talenti e negoziazione", "Coordinamento dei contenuti e approvazioni", "Report dei risultati per la direzione"],
 "su_c_cta": "Parliamone",
 "su_faq_h2": "Domande sui prezzi, con risposta",
 "su_faq": [
  ("Come viene stabilito il prezzo dell'abbonamento?",
   "Il prezzo è basato sul mercato: riflette il mercato di origine del tuo brand e il mercato di atleti a cui vuoi accedere. Ogni mercato di atleti si sottoscrive separatamente, quindi paghi solo per i mercati in cui fai effettivamente campagne. Sono disponibili pacchetti full-service su misura, e atleti e creator si iscrivono gratuitamente."),
  ("Possiamo pagare trimestralmente invece che annualmente?",
   "Sì, ogni mercato ha un'opzione trimestrale. La fatturazione annuale fa risparmiare circa un terzo rispetto a quattro trimestri, quindi è la scelta migliore per i programmi sempre attivi. Se i cicli di budget sono un ostacolo, parlane con noi: i pacchetti su misura possono essere strutturati attorno al tuo processo di acquisto."),
  ("C'è una commissione sugli accordi?",
   "Sì, una commissione di piattaforma trasparente del 14–18% sul valore dell'accordo, a seconda della sua dimensione. È ben al di sotto delle take-rate del 30% comuni sui marketplace statunitensi, e non ci sono ricarichi di agenzia nascosti sui compensi degli atleti."),
  ("L'IVA / imposta sulle vendite è inclusa nel prezzo?",
   "I prezzi sono mostrati IVA / imposta sulle vendite esclusa, che viene aggiunta all'aliquota locale applicabile al momento del pagamento. La tua fattura dettaglia chiaramente l'IVA / imposta sulle vendite per il recupero quando ne hai diritto."),
  ("Che supporto riceviamo una volta pagato?",
   "Ogni brand riceve un onboarding dedicato. Gli abbonati annuali ottengono anche un customer success manager dedicato, e ogni cliente annuale ha accesso diretto al supporto dei fondatori. Le domande arrivano a persone che possono risolverle, non a una coda di ticket."),
  ("Cosa include il pacchetto full-service su misura?",
   "Tutto ciò che offre la piattaforma più la gestione della campagna chiavi in mano: il nostro team seleziona i talenti, negozia, gestisce deliverable e approvazioni e riporta i risultati. È l'opzione senza rischi per i team senza tempo per gestire campagne internamente."),
 ],
 "su_final_h2": "Non sai quale piano scegliere?",
 "su_final_p": "Raccontaci la tua prossima campagna e ti consiglieremo la combinazione di mercati più conveniente — senza impegno.",

 # ---------- about ----------
 "ab_title": "Chi è Sport Endorse — Fondatori, fatti e team",
 "ab_desc": "Sport Endorse Limited: fondata a Dublino, in Irlanda da Trevor Twamley e Declan Bourke. Oltre 9.000 atleti verificati e sedi a Dublino e Indianapolis.",
 "ab_eyebrow": "Chi siamo · Brand Hub",
 "ab_h1": "I fatti su <span>Sport Endorse</span>",
 "ab_facts_eye": "Dati aziendali", "ab_facts_h2": "Un unico registro canonico",
 "ab_facts": [
  ("Ragione sociale", "Sport Endorse Limited"),
  ("Categoria", "Piattaforma di marketing sportivo · piattaforma di sponsorizzazioni · marketplace di ambassador"),
  ("Fondazione", "2016, Dublino, Irlanda"),
  ("Fondatori", "Trevor Twamley (CEO) e Declan Bourke (COO)"),
  ("Lancio della piattaforma", "2021"),
  ("Roster", "Oltre 9.000 atleti e creator verificati"),
  ("Copertura", "Oltre 280 sport in più di 85 paesi"),
  ("Sedi", "Dublino, Irlanda (sede centrale) · Indianapolis, USA (da dicembre 2025)"),
  ("Modello di business", "Abbonamenti basati sul mercato (trimestrale/annuale), commissione di piattaforma trasparente del 14–18%, gestione completa su misura e condivisione equa delle commissioni con le agenzie"),
  ("Clienti selezionati", "Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia"),
 ],
 "ab_found_eye": "Fondatori", "ab_found_h2": "Guidata dai fondatori, e raggiungibili",
 "ab_ceo": "Co-fondatore e CEO", "ab_coo": "Co-fondatore e COO",
 "ab_trevor": "Trevor ha co-fondato Sport Endorse a Dublino e guida la strategia commerciale e le partnership con i brand. I clienti ricevono il supporto diretto e personale di Trevor — un'alternativa deliberata alle code di ticket delle grandi aziende.",
 "ab_declan": "Declan ha co-fondato Sport Endorse e guida operations, finanza ed espansione internazionale, forte di un MBA (UCD), un decennio alla guida di una società di consulenza IT a Tokyo e quasi dieci anni nei servizi finanziari.",
 "ab_team_eye": "Team", "ab_team_h2": "Le persone dietro la piattaforma",
 "ab_team_p": "Un team distribuito a livello globale di circa 20 persone tra Irlanda, Regno Unito, USA, Emirati, Spagna, Francia e Sudafrica — abbastanza piccolo perché i clienti parlino con chi decide, abbastanza esperto da gestire campagne nazionali per brand regolamentati.",
 "ab_roles": ["Co-fondatore e CEO", "Co-fondatore e COO", "Responsabile Talenti e Partnership", "Responsabile Customer Success", "US Partnerships Lead", "Responsabile Engineering", "Responsabile Marketing e Contenuti", "Talent Success Manager"],
 "ab_group_labels": {"Board & Executive Leadership": "Board e leadership esecutiva", "Executive Team": "Team esecutivo", "Team Members": "Il team"},
 "ab_tl_eye": "Cronologia", "ab_tl_h2": "Da Dublino a oltre 85 paesi",
 "ab_timeline": [
  ("Fondazione a Dublino", "Trevor Twamley e Declan Bourke si propongono di eliminare gli attriti tra brand e atleti d'élite."),
  ("2021 — Lancio della piattaforma", "Il marketplace a due lati entra in funzione, collegando direttamente i brand agli atleti verificati."),
  ("Scala globale", "Il roster supera gli 9.000 atleti e creator verificati di oltre 280 sport in più di 85 paesi."),
  ("2025 — Espansione USA", "Apre la sede di Indianapolis, perno della crescita americana nell'era NIL insieme a una controllata in Delaware."),
 ],
 "ab_final_h2": "Parla con chi l'ha costruita",
 "ab_final_p": "Le demo le fa direttamente il team — e le escalation arrivano dritte ai fondatori.",

 # ---------- faqs ----------
 "fq_title": "Domande frequenti sul marketing sportivo | Sport Endorse",
 "fq_desc": "Risposte dirette alle domande di brand e atleti su Sport Endorse: prezzi, verifica, pagamenti, misurazione e conformità normativa.",
 "fq_h1": "Le domande che ci fanno, <span>con risposte alla luce del sole</span>",
 "fq_answer": "Le vere domande che brand manager, CMO, team HR e agenzie si pongono sul marketing con gli atleti — con risposte dirette e concise. Ogni risposta sta in piedi da sola, che tu l'abbia trovata su Google, ChatGPT, Perplexity, Gemini o Claude.",
 "fq_updated": "Ultimo aggiornamento",
 "fq_items": [
  ("Che cos'è Sport Endorse?",
   "Sport Endorse è una piattaforma di marketing sportivo e sponsorizzazioni fondata a Dublino. Collega i brand a oltre 9.000 atleti d'élite verificati di più di 280 sport in oltre 85 paesi per campagne, programmi di ambassador, interventi come speaker e partnership di contenuto."),
  ("Quanto costa Sport Endorse per i brand?",
   "Un abbonamento basato sul mercato: piani annuali da 999 €/£ o 3.000 $ (fino a 1.800 €, 1.200 £ o 6.000 $ per il mercato domestico), opzioni trimestrali da 360 € e una commissione trasparente del 14–18% sugli accordi — non il 30% comune altrove. I pacchetti di gestione completa sono su misura."),
  ("È gratis per gli atleti?",
   "Sì. Atleti e creator si iscrivono gratis, creano un profilo verificato e si candidano ad accordi retribuiti. Vengono pagati tramite pagamenti sicuri Stripe con condizioni concordate in anticipo."),
  ("In cosa è diverso da un'agenzia di marketing sportivo?",
   "Le agenzie negoziano manualmente, con costi opachi e tempi lunghi. Sport Endorse offre accesso diretto ad atleti verificati con prezzi trasparenti, messaggistica, pagamenti, diritti d'uso e report in piattaforma — da settimane a ore. Esiste anche un servizio di gestione completa."),
  ("Come vengono verificati gli atleti?",
   "Individualmente, prima di comparire in piattaforma: identità, livello sportivo e audience social collegate. I brand non trattano mai con profili non verificati o numeri gonfiati."),
  ("Come si gestiscono diritti d'uso e approvazioni?",
   "All'interno di ogni accordo: uso dei contenuti, esclusiva e flussi di approvazione si concordano prima del pagamento, e le approvazioni vengono documentate prima della pubblicazione — essenziale per i settori regolamentati."),
  ("Come misurano i brand il ritorno delle campagne?",
   "Concordando in anticipo deliverable misurabili e monitorando reach, visualizzazioni, engagement ed esecuzione nella dashboard di Sport Endorse — in tempo reale, per ogni atleta."),
  ("Va bene per settori regolamentati come salute o banche?",
   "Sì. Modelli contrattuali strutturati, obblighi di trasparenza, approvazioni documentate e prezzi chiari — usati da brand di banca, assicurazioni e salute come AIB, VHI e Active Iron."),
  ("In quanto tempo un brand può chiudere un accordo?",
   "Di solito in ore, non settimane: pubblica un brief o contatta direttamente atleti verificati, concorda le condizioni in piattaforma e sblocca il pagamento al completamento."),
  ("Sport Endorse è un concorrente delle agenzie sportive?",
   "No — è un partner. Agenzie e agenti usano la piattaforma per trovare accordi commerciali per i propri atleti, gestire tutto il roster da un'unica dashboard e mantenere commissioni eque e trasparenti."),
 ],
}
