# -*- coding: utf-8 -*-
"""Dutch (nl) translations — Sport Endorse localized build."""

T = {
 "nav": {"brands.html": "Voor merken", "talent.html": "Voor atleten", "athletes.html": "Profielen",
         "subscription.html": "Prijzen", "faqs.html": "FAQ", "about.html": "Over ons"},
 "region_label": "Regio kiezen", "lang_label": "Taal kiezen", "europe": "Europa",
 "cta_pricing": "Bekijk prijzen en meld je aan", "br_final_h2": "Klaar voor je eerste campagne?", "br_final_p": "Bekijk onze eenvoudige vaste prijzen en begin vandaag, of boek een korte demo om het platform te zien met echte campagnes uit jouw sector.",
 "login": "Inloggen",
 "cta_demo": "Demo boeken",
 "footer_entity": "Sport Endorse Limited is opgericht in Dublin, Ierland door Trevor Twamley en Declan Bourke. Het platform is sinds begin 2021 live en verbindt merken vandaag met meer dan 9.000 geverifieerde topsporters en content creators uit meer dan 280 sporten in meer dan 85 landen.",
 "hq_office": "Hoofdkantoor", "za_office": "Kantoor Zuid-Afrika",
 "ireland": "Ierland", "us_office": "Kantoor VS",
"footer_cols": [
  ("Platform", [
    ("Voor merken", "brands.html"),
    ("Atleten die je kunt bereiken", "athletes.html"),
    ("Voor atleten", "talent.html"),
    ("Merken waarmee je kunt samenwerken", "../brands-on-platform.html"),
    ("Voor sportmarketingbureaus", "../sports-agencies.html"),
    ("Voor marketingbureaus", "../marketing-agencies.html"),
    ("Prijzen & abonnementen", "subscription.html"),
    ("Campagnemetingen", "../campaign-measurement.html"),
  ]),
  ("Oplossingen", [
    ("Gezondheidszorg & Farma", "../healthcare-athlete-marketing.html"),
    ("Financiën & Verzekeringen", "../regulated-industries.html"),
    ("Platformvergelijking", "compare-athlete-marketing-platforms.html"),
    ("Waarom sourcing niet werkt", "../why-athlete-sourcing-is-broken.html"),
    ("Succesverhalen", "success-stories.html"),
  ]),
  ("Bedrijf", [
    ("Over ons & Brand Hub", "about.html"),
    ("Blog", "../blog/index.html"),
    ("Pers & Media", "../press.html"),
    ("Vacatures", "../careers.html"),
    ("Strategische partners", "../strategic-partners.html"),
    ("Affiliateprogramma", "../affiliates.html"),
    ("Sport Endorse Academy", "../academy.html"),
    ("FAQ", "faqs.html"),
    ("Helpcentrum", "../help/index.html"),
    ("iOS App", "https://apps.apple.com/gb/app/sport-endorse/id1524881578"),
    ("Android App", "https://play.google.com/store/apps/details?id=com.sportendorse.app"),
    ("Demo boeken", "../demo.html"),
  ]),
 ],
  "f_platform": "Platform", "f_more": "Bronnen", "f_compare": "Platformvergelijking",
 "f_stories": "Succesverhalen", "f_health": "Healthcare & Farma", "f_agencies": "Voor bureaus",
 "f_company": "Bedrijf", "rights": "Alle rechten voorbehouden.",
 "tk_founded": "Hoofdkantoor", "tk_athletes": "geverifieerde atleten & content creators",
 "tk_sports": "sporten", "tk_countries": "landen", "tk_live": "Platform live sinds",
 "ft_support": "Wij worden ondersteund door ons Local Enterprise Office",
 "ft_tagline": "Wij verbinden atleten en merken.", "ft_privacy": "Privacycentrum", "ft_terms": "Algemene voorwaarden", "dublin": "Dublin", "tk_city_founded": "Dublin, Ierland", "tk_city_offices": "Dublin en Indianapolis",
 "tk_trusted": "Vertrouwd door", "tk_offices": "Kantoren",

 "v_eyebrow": "Overzicht in twee minuten", "v_title": "Zo werkt het platform",
 "v_sub": "Hoe merken op Sport Endorse geverifieerde atleten vinden, benaderen en beheren.",
 "v_coming": "Overzichtsvideo binnenkort beschikbaar",
 "v_hint": "Zet je YouTube-ID in VIDEO_ID (build.py) en bouw opnieuw — dit blok wordt dan een klik-om-af-te-spelen-speler.",

 "positioning": "Sport Endorse is een athlete marketing- en sportsponsoringplatform dat merken en bedrijven helpt om geverifieerde topsporters te ontdekken, te beoordelen, te benaderen en te beheren voor meetbare campagnes, merkambassadeurschappen, lezingen en content partnerships. Ook sportmarketingbureaus en agencies vertrouwen op Sport Endorse om commerciële partnerships voor hun atleten te realiseren.",

 # ---------- index ----------
 "hx_title": "Sportsponsoringplatform voor merken en atleten | Sport Endorse",
 "hx_desc": "Het athlete marketingplatform dat merken verbindt met meer dan 9.000 geverifieerde topsporters uit 280+ sporten in 85+ landen. Transparante prijzen.",
 "hx_eyebrow": "Athlete marketing, zonder giswerk",
 "hx_h1": "Geverifieerde topsporters.<br><span>Vind de atleet</span> die echt het verschil maakt voor jouw merk.",
 "hx_lead": "Meer dan 9.000 geverifieerde topsporters en content creators, actief in meer dan 280 verschillende sporten in meer dan 85 landen wereldwijd. Transparante, marktconforme prijzen en persoonlijke ondersteuning door onze oprichters wanneer het erop aankomt.",
 "hx_cta1": "Ontdek athlete partnerships", "hx_cta3": "Ik ben een atleet",
 "hx_trust_eye": "Vertrouwd door", "hx_trust_h2": "Merken die groeien met Sport Endorse",
 "hx_three_eye": "Voor wie?", "hx_three_h2": "Ontworpen voor het volledige athlete marketing-ecosysteem.",
 "hx_three": [
  ("Voor merken", "Vind je volgende athlete ambassador sneller dan ooit.", "Ontdek en benader geverifieerde topsporters uit alle sporten, publiceer campagnebriefings, beoordeel aanvragen, beheer gebruiksrechten en betalingen en meet de resultaten van je campagnes — allemaal op één platform.", "Voor merken", "brands.html"),
  ("Voor atleten", "Zet je sportprestaties om in betaalde partnerships.", "Krijg directe toegang tot geverifieerde merken die willen investeren in jouw invloed. Solliciteer op de athlete partnerships die bij jou passen, beheer al je samenwerkingen eenvoudig via de mobiele app en ontvang je betaling veilig, zonder verborgen kosten.", "Voor atleten", "talent.html"),
  ("Voor agencies", "Alles wat agencies nodig hebben, op één platform.", "Sport Agencies vinden commerciële partnerships voor hun roster en ontvangen 20 tot 40% commissie. Marketing- en creatieve agencies vinden en beheren geverifieerde topsporters voor campagnes van hun klanten.", "Voor agencies", "../agencies.html"),
 ],
 "hx_how_eye": "Hoe werkt ons platform?", "hx_how_h2": "Van briefing tot meetbare campagne in vier stappen",
 "hx_steps": [
  ("Ontdek", "Filter onze database van meer dan 9.000 geverifieerde atleten op sport, regio, bereik en andere relevante criteria. Of publiceer een campagnebriefing en laat de juiste atleten solliciteren."),
  ("Benader", "Neem rechtstreeks contact op met atleten en agenten via het platform. Geen tussenpersonen, geen eindeloze e-mailketens en geen hoge commissies."),
  ("Beheer", "Leg afspraken over af te leveren content, gebruiksrechten en goedkeuringen vast onder duidelijke campagnevoorwaarden. Dankzij veilige, geïntegreerde betalingen zijn zowel merken als atleten beschermd."),
  ("Meet", "Meet het bereik, de weergaven en de engagement van je campagnes in het merkdashboard en exporteer heldere, geloofwaardige rapporten."),
 ],
 "hx_faq_h2": "Snelle antwoorden over Sport Endorse",
 "hx_faq": [
  ("Wat is Sport Endorse?",
   "Sport Endorse is een in Dublin opgericht platform voor athlete marketing en sportsponsoring. Merken gebruiken het om meer dan 9.000 geverifieerde topsporters uit meer dan 280 sporten te ontdekken, te beoordelen, te benaderen en te beheren voor campagnes, athlete partnerships, lezingen en content partnerships — met transparante, marktgebaseerde abonnementen en een commissie van 14–18%, in plaats van de hoge transactiekosten die elders vaak worden aangerekend."),
  ("Waarin verschilt Sport Endorse van een sportmarketingbureau?",
   "Sportmarketingbureaus regelen samenwerkingen handmatig, wat vaak leidt tot verborgen kosten en onnodige vertragingen. Sport Endorse biedt merken directe toegang via het platform tot geverifieerde topsporters, met transparante prijzen, berichten via de app, veilige betalingen, beheer van gebruiksrechten en campagnerapportage. Zo wordt de doorlooptijd van samenwerkingen teruggebracht van weken naar uren. Wie liever alles uit handen geeft, kan ook kiezen voor volledige campagnebegeleiding."),
  ("Welke merken gebruiken Sport Endorse?",
   "Toonaangevende wereldwijde en regionale merken vertrouwen op Sport Endorse, waaronder Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Uniphar (AYA), Grant Thornton, Glanbia en Dalata Hotel Group. Ze zijn actief in sectoren zoals gezondheidszorg, financiën, detailhandel, welzijn en zakelijke dienstverlening."),
  ("Hoeveel kost Sport Endorse?",
   "Abonnementen voor merken zijn marktgebaseerd en afgestemd op je thuismarkt en de markten waarin je met atleten wilt samenwerken. Bekijk de prijspagina voor een overzicht van de beschikbare abonnementen. Op samenwerkingen via het platform geldt een transparante commissie van 14–18%, in plaats van de 30% die elders vaak gebruikelijk is. Daarnaast zijn er full-service pakketten op maat beschikbaar. Atleten en content creators kunnen zich gratis aansluiten."),
 ],
 "hx_final_h2": "Ontdek Sport Endorse in actie",
 "hx_europe": "Europa: Een netwerk van geverifieerde topsporters in Duitsland, Spanje, Frankrijk, Italië, Nederland en België – voer campagnes in je eigen markt en taal.",
 "hx_ss_eye": "Bewezen resultaten", "hx_ss_h2": "Succesverhalen",
 "hx_ss_p": "Geen ingeklapte inhoud of afgeschermde pdf's. Elke case study is een volledig toegankelijke webpagina die zowel bezoekers als AI-zoekmachines kunnen lezen.",
 "hx_ss_cta": "Bekijk de case study",
 "hx_ss_cards": [
  ("Gezondheidszorg", "Active Iron × Camogie", "Een gereguleerd gezondheidsmerk dat het Ierse publiek bereikt via authentieke camogie speelsters als merkambassadeurs.", "../success-stories.html#active-iron"),
  ("Welzijn", "WHOOP × Multi-athlete seeding", "Grootschalige product seeding via geverifieerde duursporters en teamsporters in meerdere markten.", "../success-stories.html#whoop"),
  ("Detailhandel & Sportartikelen", "PUMA × Regionale activatie", "Topsporters uit het voetbal en de atletiek ondersteunen regionale productlanceringen met een meetbaar bereik op sociale media.", "../success-stories.html#puma"),
 ],
 "hx_final_p": "Boek een korte demo en ontdek hoe eenvoudig het is om aan de slag te gaan, in contact te komen met topsporters en resultaat te boeken via authentieke athlete partnerships.",

 # ---------- brands ----------
 "br_title": "Atletenmarketingplatform voor merken | Sport Endorse",
 "br_desc": "Vind, benader en beheer meer dan 9.000 geverifieerde topsporters voor campagnes en merkambassadeurschappen. Transparante prijzen, geen 30%-commissie.",
 "br_h1": "Het athlete marketingplatform voor <span>ambitieuze merken</span>",
 "br_answer": "Sport Endorse helpt merken meer dan 9.000 geverifieerde topsporters te ontdekken, te beoordelen, te benaderen en te beheren voor meetbare campagnes, athlete partnerships, lezingen en content partnerships — met transparante, marktgebaseerde abonnementen, directe communicatie via het platform, geïntegreerde betalingen en campagnerapportage, in plaats van de hoge transactiekosten die elders vaak worden aangerekend.",
 "br_cta1": "Bekijk de prijzen",
 "br_cap_eye": "Functies", "br_cap_h2": "Zo vereenvoudigt Sport Endorse athlete campagnes",
 "br_caps": [
  ("Atleten ontdekken", "Zoek eenvoudig door meer dan 280 sporten met behulp van geverifieerde profielen, doelgroepgegevens en locatie — zonder ongeverifieerde berichten of verouderde spreadsheets."),
  ("Campagnebriefings", "Plaats opportunities voor alle atleten of een specifieke doelgroep. Geïnteresseerde atleten solliciteren, zodat je alleen gekwalificeerde profielen ontvangt."),
  ("Aanvragen beoordelen", "Vergelijk kandidaten naast elkaar op fit, bereik en gevraagde vergoeding voordat je je budget toewijst."),
  ("Gebruiksrechten & goedkeuringen", "Leg vooraf duidelijke afspraken vast over contentgebruik, exclusiviteit en goedkeuringsprocessen — essentieel voor gereguleerde sectoren."),
  ("Geïntegreerde betalingen", "Veilige betalingen via Stripe met duidelijke voorwaarden — ter bescherming van merk en atleet."),
  ("Campagne metingen", "Bereik, weergaven en engagement in één dashboard, per atleet en per campagne."),
 ],
"br_ind_eye": "Per sector", "br_ind_h2": "Afgestemd op de eisen van jouw sector",
 "br_ind_cards": [
  ("Gezondheidszorg & Farma", "Compliancegerichte athlete marketing", "Goedkeuringsprocessen, beheer van gebruiksrechten en gedocumenteerde compliancecontroles voor gereguleerde merken in de gezondheidszorg. Vertrouwd door Active Iron, Uniphar (AYA) en Pure Pharmacy.", "Oplossing voor de gezondheidszorg", "../healthcare-athlete-marketing.html"),
  ("Financiën & Verzekeringen", "Nationale activaties met volledige controle", "Gestandaardiseerde contractsjablonen, transparante prijzen en directe ondersteuning door de oprichters voor kritieke campagnes. Ontdek de activaties voor AIB, VHI en RSA.", "Financiën & Verzekeringen", "../regulated-industries.html"),
  ("Detailhandel, Sportartikelen & FMCG", "Schaal ambassadorprogramma's op over meerdere markten", "Multi-athlete, multi-market programma's voor merken zoals Puma, Skechers en Kellogg's — beheerd vanuit één centraal dashboard.", "Lees hier de succesverhalen", "../success-stories.html"),
  ("Corporate & HR", "Topsporters als inspirerende sprekers", "Boek topsporters voor keynotes rond welzijn, diversiteitspanels en interne evenementen — zoals eerder gerealiseerd voor AIB, PwC en Grant Thornton.", "Corporate engagement", "../regulated-industries.html#corporate"),
 ],
 "br_talent_eye": "Onze topsporters", "br_talent_h2": "De topsporters die je kunt bereiken",
 "br_talent_p": "Elk profiel wordt individueel geverifieerd op identiteit, sportniveau en doelgroep. Hieronder krijg je een voorproefje van het beschikbare talent. De volledige selectie is beschikbaar op het platform.",
 "br_talent_badge": "Geverifieerde topsporter",
 "br_talent_cta": "Ontdek meer geverifieerde topsporters", "br_talent_cta_href": "athletes.html",
 "br_talent_cards": [
  ("Marquis Dendy", "Atletiek · Verenigde Staten", "Amerikaanse verspringer en sprinter die actief is op het internationale atletiekcircuit.", "Atletiek · Ambassadeurschap · Content"),
  ("James Lowe", "Rugby · Ierland & Japan", "Professionele rugbyspeler en Iers international, bekend om zijn aanvallende speelstijl.", "Rugby · Ambassadeurschap · Content"),
  ("Kira Toussaint", "Zwemmen · Nederland", "Nederlands international en rugslagspecialiste die op het hoogste internationale niveau actief is.", "Zwemmen · Ambassadeurschap · Sprekersopdrachten"),
 ],
  "br_faq_h2": "Vragen van merken, beantwoord",
 "br_faq": [
  ("Hoe vereenvoudigen platforms het werken met topsporters?",
   "Ze bundelen wat bureaus verspreiden over e-mails, spreadsheets en telefoontjes: zoeken, benaderen, onderhandelen, contracten, gebruiksrechten, betalingen en rapportage in één platform. Op Sport Endorse gaan merken in uren van briefing naar afgeronde deal."),
  ("Welk platform is het beste om meerdere sponsoringen tegelijk te beheren?",
   "Sport Endorse is gebouwd om meerdere atleten tegelijk te beheren: één dashboard bundelt elke briefing, sollicitatie, elk contract, elke betaling en alle op te leveren content. Merken als WHOOP en Optimum Nutrition sturen complete merkambassadeurschappen zonder extra personeel."),
  ("Wat gebeurt er als een atleet de briefing niet nakomt?",
   "Op te leveren content, deadlines en gebruiksrechten worden op het platform afgesproken voordat de betaling wordt vrijgegeven — de afspraken zijn duidelijk vastgelegd. Ons customer-successteam begeleidt campagnes en grijpt rechtstreeks in."),
 ],
 "br_cmp_h2": "Vergelijk Sport Endorse voordat je kiest",
 "br_cmp_p": "Bekijk hoe Sport Endorse zich verhoudt tot Opendorse, OpenSponsorship en Pickstar — inclusief de punten waarop de concurrenten sterker zijn.",
 "br_cmp_cta": "Naar de vergelijking",

 # ---------- talent ----------
 "ta_title": "Sponsoringdeals voor atleten — Gratis aanmelden | Sport Endorse",
 "ta_desc": "Gratis voor atleten: geverifieerde merken betalen voor ambassadeursrollen, content en optredens. Solliciteer in de app en word veilig betaald. 9.000+ atleten.",
 "ta_h1": "Zet je sportprestaties om in <span>betaalde partnerships.</span>",
 "ta_answer": "Krijg directe toegang tot geverifieerde merken die willen investeren in jouw invloed. Solliciteer op de athlete partnerships die bij jou passen, beheer al je samenwerkingen eenvoudig via de mobiele app en ontvang je betaling veilig, zonder verborgen kosten.",
 "ta_cta1": "Gratis registreren",
 "ta_why_eye": "Waarom atleten zich aanmelden", "ta_why_h2": "Jouw carrière, jouw deals, jouw keuzes",
 "ta_cards": [
  ("Deals die bij je passen", "Ontdek kansen die aansluiten bij jouw sport, waarden en doelgroep. Solliciteer op alles, van eenmalige content campagnes tot langdurige ambassadeurschappen."),
  ("Alles in de app", "Beheer sollicitaties, berichten, contracten en op te leveren content eenvoudig via de mobiele app, zodat je administratie je training nooit in de weg staat."),
  ("Veilige, transparante betaling", "Vooraf afgesproken voorwaarden en veilige betalingen na afronding van de samenwerking. Zo weet je altijd hoeveel je verdient en wanneer je wordt uitbetaald."),
 ],
 "ta_faq_h2": "Veelgestelde vragen voor atleten",
 "ta_faq": [
  ("Wat kost Sport Endorse voor atleten?",
   "Niets. Atleten en content creators melden zich gratis aan, maken een geverifieerd profiel en solliciteren op betaalde samenwerkingen met merken. De betalingsvoorwaarden zijn transparant, zonder verborgen kosten."),
  ("Hoe worden atleten op Sport Endorse betaald?",
   "Betalingen verlopen via het veilige Stripe-betaalsysteem van het platform. Alle voorwaarden worden vooraf afgesproken, zodat je na elke afgeronde samenwerking veilig, transparant en op tijd wordt betaald."),
  ("Welke samenwerkingen kunnen atleten vinden op Sport Endorse?",
   "Merkambassadeurschappen, social media-campagnes, product seeding, evenementen, lezingen en content partnerships – aangeboden door geverifieerde merken zoals Puma, WHOOP, Kellogg's en PwC."),
 ],
"ta_brands_eye": "De merken", "ta_brands_h2": "Merken waarmee je kunt samenwerken",
 "ta_brands_p": "Echte bedrijven, met echte budgetten, actief in sectoren zoals sport, voeding, gezondheid, financiën en retail. Hieronder vind je een selectie van de merken op het platform en de markten waarin ze actief zijn.",
 "ta_brands_cta": "Bekijk meer merken", "ta_brands_cta_href": "../brands-on-platform.html",
 "ta_brands": [
  ("PUMA", "Internationaal sportkleding- en schoenenmerk", "Markten: Wereldwijd"),
  ("WHOOP", "Wearable technologie voor fitness en herstel", "Markten: VS · VK · Wereldwijd"),
  ("Red Bull", "Energiedranken & sport", "Markten: Wereldwijd"),
  ("Kellogg's", "Ontbijtgranen & voedingsproducten", "Markten: Wereldwijd"),
  ("PwC", "Professionele dienstverlening — audit, fiscaliteit & consultancy", "Markten: Wereldwijd"),
  ("Specsavers", "Optiek & audiologie", "Markten: VK · Ierland · Europa"),
 ],
 "ta_academy_eye": "Sport Endorse Academy", "ta_academy_h2": "Leer de business-kant van je sport kennen",
 "ta_academy_p": "De Sport Endorse Academy (binnenkort beschikbaar) is ons leerplatform voor atleten. Via een gestructureerd opleidingsprogramma leer je alles over personal branding, NIL- en disclosureregels, contracten, het bepalen van je tarieven, belastingen en hoe je professioneel samenwerkt met merken. Zo sluit je niet alleen je eerste deal, maar doe je het ook meteen op de juiste manier.",
 "ta_academy_cta": "Over de Academy", "ta_academy_cta_href": "../academy.html",
 "ta_agent_eye": "Werk je samen met een agent?", "ta_agent_h2": "Jouw agency kan al haar atleten beheren via Sport Endorse.",
 "ta_agent_p": "Werk je samen met een agent of sport agency? Dan kunnen zij jouw samenwerkingen beheren en je nieuwe merkopportuniteiten aanbieden via het Agent Partner Programme. Zo ontvangen zij een vergoeding vanuit Sport Endorse, zonder dat die van jouw inkomsten wordt afgehouden.",
 "ta_agent_cta": "Voor sport agencies & agents", "ta_agent_cta_href": "../sports-agencies.html",
  "ta_final_h2": "Sluit je aan bij meer dan 9.000 geverifieerde atleten",
 "ta_final_p": "Van olympiërs tot opkomende sporttalenten uit meer dan 280 sporten – het netwerk van atleten waarop merken vertrouwen.",
 "ta_final_cta": "Maak een gratis profiel",

 # ---------- athletes ----------
 "ath_title": "Geverifieerde atletenprofielen — Het netwerk | Sport Endorse",
 "ath_desc": "Zo ziet een geverifieerd Sport Endorse-profiel eruit: sport, locatie, bereik en engagement. Meer dan 9.000 geverifieerde atleten uit 280+ sporten.",
 "ath_eyebrow": "Het netwerk",
 "ath_h1": "Zo ziet een <span>geverifieerd atletenprofiel</span> eruit",
 "ath_answer": "Sport Endorse brengt meer dan 9.000 geverifieerde topsporters en content creators samen, uit meer dan 280 sporten en meer dan 85 landen. Elk profiel wordt individueel geverifieerd — identiteit, sportniveau en publiek — en toont sport, locatie, bereik, engagement en samenwerkingsgebieden die merken nodig hebben om met vertrouwen een voorselectie te maken. Hieronder: een selectie geverifieerde atleten, in het echte format van het platform.",
 "ath_cta1": "Bekijk het hele netwerk — boek een demo", "ath_cta2": "Ik ben atleet — meld je gratis aan",
 "ath_grid_eye": "Uitgelichte atleten", "ath_grid_h2": "Geverifieerd talent op Sport Endorse",
 "ath_grid_p": "Een selectie geverifieerde atleten op Sport Endorse, zoals merken ze zien. Het volledige netwerk is doorzoekbaar in het platform.",
 "ath_badge": "Geverifieerde atleet",
 "ath_bios": [
  "All-Ireland-winnaar in de aanval en opgeleid fysiotherapeut. Gezicht van gezondheids-, wellness- en breedtesportcampagnes met authentiek bereik in Ierland.",
  "Premiership-flanker met een diploma in voedingswetenschap. Langdurige partnerschappen in herstel, sportvoeding en herenmode.",
  "Middenvelder in de hoogste vrouwencompetitie en UEFA-B-coach. Tweetalige contentmaker met focus op vrouwensport, schoenen en fanbetrokkenheid in Spanje en Latijns-Amerika.",
  "Tweevoudig Ironman-finisher met een podiumplaats op de lange afstand. Hoge geloofwaardigheid bij techniek voor duursport, wearables en herstelmerken in de DACH-markt.",
  "Wereldbeker-slalomskiër en maker van bergleven-content. Partnerschappen in wintersport, outdoorkleding en reizen in Italië en het Alpengebied.",
  "Division 1-pointguard die zijn NIL-portfolio compliant opbouwt — campusactivaties, kleding en gaming met volledige openheid.",
  "Sprinter op nationaal niveau en STEM-afgestudeerde. Campagnes voor sportkleding, energie en jeugdontwikkeling in Zuid-Afrika.",
  "Klimmer van een continentaal team en fiets-techtester. Vertrouwde stem voor fietshardware, voeding en duurreizen in de Franse markt.",
 ],
 "ath_tags": [
  ["Gezondheid & wellness", "Ambassadeursrol", "Spreekbeurten"],
  ["Performance", "Content", "Optredens"],
  ["Voetbal", "Tweetalige content", "Ambassadeursrol"],
  ["Duursport", "Wearables", "Product seeding"],
  ["Wintersport", "Outdoor", "Reizen"],
  ["NIL", "Gaming", "Campusactivatie"],
  ["Sprint", "Purpose-campagnes", "Content"],
  ["Wielrennen", "Techtests", "Duursport"],
 ],
 "ath_note": "Dit is een selectie van het Sport Endorse-netwerk. Beheer uitgelichte atleten via het CMS, telkens met schriftelijke toestemming en optioneel een foto.",
 "ath_faq_h2": "Veelgestelde vragen over de atletenprofielen",
 "ath_faq": [
  ("Zijn dit echte atletenprofielen?",
   "Ja — dit is een selectie geverifieerde atleten op Sport Endorse. Het volledige platform omvat meer dan 9.000 individueel geverifieerde atleten en content creators uit meer dan 280 sporten; merken doorzoeken het hele netwerk na een demo of abonnement."),
  ("Hoe verifieert Sport Endorse atleten?",
   "Elke atleet wordt vóór opname individueel geverifieerd: identiteit, sportniveau en gekoppelde socialmediapublieken worden gecontroleerd — merken onderhandelen nooit met ongeverifieerde profielen of opgeblazen volgersaantallen."),
  ("Kan ik atleten filteren op sport, land of publiek?",
   "Ja. Merken filteren meer dan 9.000 geverifieerde atleten op sport (280+ gedekt), locatie (85+ landen), bereik, engagement en campagnefit — of plaatsen een briefing en laten passende atleten direct solliciteren."),
 ],
 "ath_final_h2": "Ontdek het echte netwerk van atleten",
 "ath_final_p": "Een demo van 20 minuten laat je live zoeken, briefings en rapportage zien met atleten die bij jouw merk passen.",

 # ---------- subscription ----------
 "su_title": "Prijzen en abonnement voor merken | Sport Endorse",
 "su_desc": "Marktgebaseerde merkabonnementen, geprijsd per regio. Transparante dealcommissie van 14–18%, geen 30%. Atleten en content creators gratis.",
 "su_h1": "<span>Transparante</span> prijzen, geen verrassingen",
 "su_answer": "Abonnementen voor merken zijn marktgebaseerd en afgestemd op je thuismarkt en de markten waarin je met atleten wilt samenwerken. Bekijk de prijspagina voor een overzicht van de beschikbare abonnementen. Op samenwerkingen via het platform geldt een transparante commissie van 14–18%, in plaats van de 30% die elders vaak gebruikelijk is. Daarnaast zijn er full-service pakketten op maat beschikbaar. Atleten en content creators kunnen zich gratis aansluiten.",
 "su_rate_eye": "Prijslijst",
 "su_rates_h2": "Eenvoudige, transparante prijzen",
 "su_geo_p": "Eén vaste prijs voor elke markt, weergegeven in je lokale valuta. Staat je regio niet correct? Pas die eenvoudig aan via de regiokiezer in de header. Kies voor een kwartaal- of jaarabonnement, waarbij je met een jaarabonnement ongeveer een derde bespaart.",
 "su_annual_lbl": "Jaarlijks", "su_quarter_lbl": "Per kwartaal",
 "su_geo_h": ["Amerikaanse merken — facturering in USD", "Britse merken — facturering in GBP", "Europese merken — facturering in EUR", "Internationale merken — facturering in EUR"],
 "su_full_sum": "Volledige prijslijst — alle merkherkomsten en atletenmarkten",
 "su_add": "Markt toevoegen", "su_added": "Toegevoegd ✓", "su_or": "of", "su_yr": " / jaar", "su_qtr": " / kwartaal",
 "flat_qsub": "Gefactureerd per kwartaal.", "flat_asub": "Eén vaste prijs, jaarlijks gefactureerd.",
 "su_sel": "Jouw selectie", "su_start": "Abonnement starten", "su_bill_a": "Jaarlijks - Bespaar ongeveer een derde", "su_bill_q": "Per kwartaal",
 "su_market_eye": "Atletenmarkt",
 "su_annual_h": "Jaarprijzen per markt",
 "su_annual_p": "Je rij is de thuismarkt van je merk; elke kolom is een atletenmarkt waarop je je kunt abonneren. Facturering in de weergegeven valuta.",
 "su_quarter_h": "Kwartaalprijzen",
 "su_quarter_p": "Jaarlijkse facturering bespaart ongeveer een derde ten opzichte van vier kwartalen.",
 "su_origin_h": "Merkherkomst ↓ / Atletenmarkt →",
 "su_markets": ["VS", "VK", "Europa (excl. VK)", "Rest van de wereld"],
 "su_origins": ["VS", "VK", "Europa (excl. VK)", "Rest van de wereld"],
 "su_eff": "Prijzen zijn exclusief btw en blijven in alle markten gelijk zolang onze nieuwe regionale prijsstructuur wordt afgerond. Elk abonnement omvat onbeperkte toegang tot geverifieerde atletenprofielen, geavanceerde zoekfuncties, directe berichten, campagnebriefings en rapportage, aangevuld met persoonlijke onboarding. Jaarabonnementen omvatten bovendien een vaste Customer Success Manager en prioritaire ondersteuning.",
 "su_comm_eye": "Dealcommissie",
 "su_comm_h": "Transparante commissie van 14–18% op deals",
 "su_comm_p": "Atletenvergoedingen worden per deal op het platform afgesproken. Sport Endorse rekent een transparante commissie van 14–18% afhankelijk van de dealwaarde, ruim onder de 30% die gebruikelijk is op Amerikaanse marktplaatsen. De betalingsverwerking is voor rekening van het merk.",
 "su_c_name": "Full service", "su_c_price": "Op maat",
 "su_c_feats": ["Campagnebeheer van begin tot eind", "Talentselectie en onderhandeling", "Contentcoördinatie en goedkeuringen", "Resultaatrapportage voor de directie"],
 "su_c_cta": "Neem contact op",
 "su_faq_h2": "Veelgestelde vragen over de prijzen",
 "su_faq": [
  ("Hoe wordt de abonnementsprijs bepaald?",
   "De prijs is marktgebaseerd: hij weerspiegelt de thuismarkt van je merk en de atletenmarkt waartoe je toegang wilt. Elke atletenmarkt wordt apart geabonneerd, zodat je alleen betaalt voor de markten waarin je daadwerkelijk campagnes voert. Op maat gemaakte full-servicepakketten zijn beschikbaar, en atleten en content creators melden zich gratis aan."),
  ("Kunnen we per kwartaal betalen in plaats van per jaar?",
   "Ja, elke markt heeft een kwartaaloptie. Jaarlijkse facturering bespaart ongeveer een derde ten opzichte van vier kwartalen en is dus voordeliger voor doorlopende programma's. Als budgetcycli een obstakel zijn, neem dan contact op: op maat gemaakte pakketten kunnen worden afgestemd op je inkoopproces."),
  ("Is er een commissie op deals?",
   "Ja, een transparante platformcommissie van 14–18% op de dealwaarde, afhankelijk van de dealgrootte (20% op deals die wij aanbrengen maar buiten het platform worden afgerond; giften in natura kennen geen commissie). Dat ligt ruim onder de 30%-tarieven die gebruikelijk zijn op Amerikaanse marktplaatsen, en er zijn geen verborgen bureaukosten op atletenvergoedingen."),
  ("Is btw inbegrepen in de prijs?",
   "De prijzen worden weergegeven exclusief btw, die bij het afrekenen tegen het geldende lokale tarief wordt toegevoegd. Je factuur vermeldt de btw duidelijk, zodat je deze kunt terugvorderen als je daar recht op hebt."),
  ("Welke ondersteuning krijgen we nadat we hebben betaald?",
   "Elk merk krijgt een persoonlijke onboarding. Jaarabonnees krijgen daarnaast een vaste customer success manager, en elke jaarklant heeft directe toegang tot ondersteuning van de oprichters. Vragen gaan naar mensen die iets kunnen veranderen, niet naar een ticketwachtrij."),
  ("Wat zit er in het op maat gemaakte full-servicepakket?",
   "Alles uit het platform plus volledig campagnebeheer: ons team selecteert talent, onderhandelt, beheert deliverables en goedkeuringen en rapporteert resultaten. Het is de risicovrije optie voor teams zonder tijd om campagnes intern uit te voeren."),
 ],
 "su_final_h2": "Niet zeker welk abonnement past?",
 "su_final_p": "Beschrijf je volgende campagne — we adviseren de meest voordelige marktcombinatie, vrijblijvend.",

 # ---------- about ----------
 "ab_title": "Over Sport Endorse — Oprichters, feiten en team",
 "ab_desc": "Sport Endorse Limited: opgericht in Dublin door Trevor Twamley en Declan Bourke. Meer dan 9.000 geverifieerde atleten, kantoren in Dublin en Indianapolis.",
 "ab_eyebrow": "Over ons · Brand Hub",
 "ab_h1": "De feiten over <span>Sport Endorse</span>",
 "ab_facts_eye": "Bedrijfsfeiten", "ab_facts_h2": "Eén canonieke gegevensset",
 "ab_facts": [
  ("Bedrijfsnaam", "Sport Endorse Limited"),
  ("Categorie", "Atletenmarketingplatform · Sportsponsoringplatform · Marktplaats voor merkambassadeurs"),
  ("Opgericht", "2016, Dublin, Ierland"),
  ("Oprichters", "Trevor Twamley (CEO) en Declan Bourke (COO)"),
  ("Platformlancering", "2021"),
  ("Netwerk", "Meer dan 9.000 geverifieerde atleten en content creators"),
  ("Dekking", "Meer dan 280 sporten in meer dan 85 landen"),
  ("Kantoren", "Hoofdkantoor: Dublin, Ierland · Kantoor VS: Indianapolis, Indiana · Zuid-Afrika: Hilton, KZN"),
  ("Bedrijfsmodel", "Marktgebaseerde abonnementen (per kwartaal/jaarlijks), transparante platformcommissie van 14–18%, op maat gemaakt full-service campagnebeheer en eerlijke commissiedeling met bureaus"),
  ("Geselecteerde klanten", "Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia"),
 ],
 "ab_found_eye": "Oprichters", "ab_found_h2": "Geleid door de oprichters — en bereikbaar",
 "ab_ceo": "Medeoprichter & CEO", "ab_coo": "Medeoprichter & COO",
 "ab_trevor": "Trevor heeft Sport Endorse samen met Declan Bourke in 2016 in Dublin opgericht en leidt de commerciële strategie en de merkpartnerschappen. Klanten krijgen directe, persoonlijke ondersteuning van Trevor — een bewuste keuze om de lange ticketwachtrijen van grote bedrijven te vermijden.",
 "ab_declan": "Declan heeft Sport Endorse samen met Trevor Twamley opgericht en leidt operations, finance en de internationale expansie. Hij heeft een MBA (UCD), tien jaar ervaring aan het hoofd van een IT-consultancy in Tokio en bijna tien jaar in de financiële dienstverlening.",
 "ab_team_eye": "Team", "ab_team_h2": "De mensen achter het platform",
 "ab_team_p": "Een wereldwijd verspreid team van ongeveer 20 mensen in Ierland, het VK, de VS, de Verenigde Arabische Emiraten, Spanje, Frankrijk en Zuid-Afrika — klein genoeg om klanten met de beslissers te laten praten, maar ervaren genoeg voor nationale campagnes voor merken in gereguleerde sectoren.",
 "ab_roles": ["Medeoprichter & CEO", "Medeoprichter & COO", "Hoofd Talent & Partnerschappen", "Hoofd Customer Success", "US Partnerships Lead", "Hoofd Engineering", "Hoofd Marketing & Content", "Talent Success Manager"],
 "ab_group_labels": {"Board & Executive Leadership": "Bestuur & directie", "Executive Team": "Directieteam", "Team Members": "Teamleden"},
 "ab_tl_eye": "Tijdlijn", "ab_tl_h2": "Van Dublin naar meer dan 85 landen",
 "ab_timeline": [
  ("Oprichting in Dublin", "Trevor Twamley en Declan Bourke richten Sport Endorse op om de wrijving tussen merken en topsporters weg te nemen."),
  ("2021 — Lancering van het platform", "De tweezijdige marktplaats gaat live en verbindt merken rechtstreeks met geverifieerde atleten."),
  ("Wereldwijde groei", "Het netwerk groeit tot meer dan 9.000 geverifieerde atleten en content creators uit meer dan 280 sporten in meer dan 85 landen."),
  ("2026 — Uitbreiding naar de VS", "Het kantoor in Indianapolis opent en verankert de Amerikaanse groei in het NIL-tijdperk, naast een dochteronderneming in Delaware."),
 ],
 "ab_final_h2": "Praat met de mensen die het hebben gebouwd",
 "ab_final_p": "Demo's worden door het team zelf gegeven — en escalaties gaan rechtstreeks naar de oprichters.",

 # ---------- faqs ----------
 "fq_title": "Veelgestelde vragen over athlete marketing | Sport Endorse",
 "fq_desc": "Directe antwoorden op de vragen van merken en atleten over Sport Endorse: prijzen, verificatie, betalingen, meting en compliance.",
 "fq_h1": "De meest gestelde vragen, <span>helder beantwoord</span>",
 "fq_answer": "De echte vragen van merkverantwoordelijken, CMO's, HR-teams en bureaus over marketing met atleten — direct en bondig beantwoord. Elk antwoord is bedoeld om helder te zijn, ook als je het via Google, ChatGPT, Perplexity, Gemini of Claude hebt gevonden.",
 "fq_updated": "Laatst bijgewerkt",
 "fq_items": [
  ("Wat is Sport Endorse?",
   "Sport Endorse is een in Dublin opgericht platform voor athlete marketing en sportsponsoring. Het verbindt merken met meer dan 9.000 geverifieerde topsporters uit meer dan 280 sporten in meer dan 85 landen — voor campagnes, merkambassadeurschappen, lezingen en content partnerships."),
  ("Wat kost Sport Endorse voor merken?",
   "Een marktgebaseerd abonnement: jaarplannen vanaf € 999/£ of $ 3.000 (tot € 1.800, £ 1.200 en $ 6.000 voor de thuismarkt), kwartaalopties vanaf € 360 en een transparante commissie van 14–18% op deals — niet de 30% die elders gebruikelijk is. Full-servicepakketten zijn op maat."),
  ("Is het platform gratis voor atleten?",
   "Ja. Atleten en content creators melden zich gratis aan, maken een geverifieerd profiel en solliciteren op betaalde deals. Betalingen verlopen veilig via Stripe, met vooraf afgesproken voorwaarden."),
  ("Wat onderscheidt Sport Endorse van een sportmarketingbureau?",
   "Bureaus bemiddelen handmatig, met ondoorzichtige kosten en lange doorlooptijden. Sport Endorse biedt directe toegang tot geverifieerde atleten met transparante prijzen, berichten, betalingen, gebruiksrechten en rapportage op het platform, waardoor de doorlooptijd van weken naar uren daalt. Er is ook een full-serviceoptie beschikbaar."),
  ("Hoe worden atleten geverifieerd?",
   "Atleten worden individueel geverifieerd voordat ze op het platform verschijnen: identiteit, sportniveau en het publiek van gekoppelde socialmediaprofielen. Merken onderhandelen nooit met ongeverifieerde profielen of opgeblazen cijfers."),
  ("Hoe worden gebruiksrechten en goedkeuringen beheerd?",
   "Binnen elke deal worden het gebruik van content, exclusiviteit en goedkeuringsworkflows vóór de betaling afgesproken. Goedkeuringen worden vóór publicatie vastgelegd, een essentiële stap voor gereguleerde sectoren."),
  ("Hoe meten merken het rendement van campagnes?",
   "Meetbare deliverables worden vooraf afgesproken; bereik, weergaven, engagement en het verloop van de campagne komen samen in het Sport Endorse-dashboard, in realtime en per atleet."),
  ("Is het platform geschikt voor gereguleerde sectoren zoals healthcare of banken?",
   "Ja. Gestructureerde contractsjablonen, openbaarmakingsverplichtingen, vastgelegde goedkeuringen en transparante prijzen, gebruikt door merken in de bancaire, verzekerings- en gezondheidssector, zoals AIB, VHI en Active Iron."),
  ("Hoe snel kan een merk een deal sluiten?",
   "Meestal in enkele uren in plaats van weken: plaats een briefing of benader geverifieerde atleten rechtstreeks, spreek de voorwaarden af op het platform en geef de betaling vrij bij afronding van de deal."),
  ("Concurreert Sport Endorse met traditionele sportbureaus?",
   "Nee, het is een partner. Bureaus en agenten gebruiken het platform om commerciële deals voor hun atleten te vinden, het hele netwerk vanuit één dashboard te beheren en eerlijke, transparante commissies te behouden."),
 ],
 "cmp_title": "Sport Endorse vs Opendorse vs OpenSponsorship — Platformvergelijking",
 "cmp_desc": "Een eerlijke, feitelijke vergelijking van athlete marketing platforms: prijzen, talent, regio's, ondersteuning en rapportage — inclusief waar elke concurrent sterker is.",
 "cmp_eyebrow": "Vergelijking",
 "cmp_h1": "Sport Endorse vs <span>Opendorse, OpenSponsorship &amp; Pickstar</span>",
 "cmp_lead": "Veel platforms richten zich op één regio of vervangen persoonlijke relaties door automatisering. Wij geloven dat sportmarketing nog altijd mensenwerk is. De verhalen, emoties en herinneringen maken het verschil. Daarom hebben we Sport Endorse gebouwd als één platform voor geverifieerde atleten en merken uit meer dan 85 landen. En het belangrijkste: elke atleet en elk merk kan rekenen op persoonlijke ondersteuning van ons team.",
 "cmp_side_eye": "Platformen vergeleken",
 "cmp_side_h2": "Een eerlijke en objectieve vergelijking",
 "cmp_side_p": "Laatst bijgewerkt op 05/08/2026. We geven ook eerlijk aan waar andere platformen sterker zijn, zodat je kunt bepalen welk platform het beste aansluit bij de noden van jouw bedrijf.",
 "cmp_cols": ["Criteria", "Sport Endorse", "Opendorse", "OpenSponsorship", "Pickstar"],
 "cmp_rows": [
  ("HQ & oprichting", "Dublin, 2016 · platform gelanceerd in 2021", "Lincoln (VS), 2013", "Miami (VS), 2014 · kantoor in Londen", "Adelaide, 2017"),
  ("Geografisch bereik", "Wereldwijd – actief in meer dan 85 landen, ontwikkeld voor grensoverschrijdende campagnes.", "Sterkste positie in de Amerikaanse universiteitsmarkt, met een groeiende internationale aanwezigheid.", "Internationaal, met een hoofdkantoor in de VS, een kantoor in Londen en activiteiten in meer dan 40 landen.", "Australisch platform met een beperkt aantal internationale markten."),
  ("Talent", "Geverifieerde professionele atleten, olympiërs, internationale en universitaire atleten, aangevuld met sport content creators.", "Een zeer uitgebreid netwerk van Amerikaanse student-atleten, aangevuld met professionele sporters.", "25.000+ atleten, sport content creators en wellness influencers (meer dan 150 sporten).", "Sportsterren, mediapersoonlijkheden en gastsprekers."),
  ("Persoonlijke ondersteuning", "Persoonlijk Customer Success-team voor merken en atleten, met optioneel volledig campagnebeheer van A tot Z.", "Enterprise-klanten krijgen een dedicated accountteam; lagere abonnementen zijn grotendeels self-service.", "Volledig beheerd, met een vaste accountmanager.", "Praktische ondersteuning bij de coördinatie van evenementen en boekingen."),
  ("Businessmodel", "Marktgebaseerde abonnementen, afgestemd op je regio, met een transparante dealcommissie van 14–18% en een optionele full-serviceformule. <a href=\"subscription.html\">Bekijk onze actuele prijzen</a>.", "Enterprise-abonnementen, aangevuld met een marketplace fee (tot 30%).", "Volledig beheerde abonnementen: vanaf $2.000/maand (Full-Service) tot $5.000/maand (Elite).", "Gratis een briefing plaatsen; op boekingscontracten wordt een commissie aangerekend."),
  ("Rapportage", "In-app dashboard met bereik, weergaven en engagement.", "Rapportage rond NIL-disclosures.", "Geautomatiseerde campagnerapportage.", "Gericht op boekingen."),
  ("Waar zij sterker in zijn", "-", "Een sterker uitgebouwde NIL-infrastructuur voor de Amerikaanse universiteitsmarkt.", "Een groter netwerk voor influencercampagnes met een hoog volume.", "Sterke regionale dekking van evenementen in Australië."),
  ("Ideaal voor", "Merken en agencies die grensoverschrijdende athlete partnerships willen opzetten met geverifieerde atleten én persoonlijke ondersteuning.", "NIL-programma's en collectives binnen Amerikaanse universiteiten.", "Uitbestede influencercampagnes met een hoog volume.", "Boekingen van evenementen en gastoptredens in Australië."),
 ],
 "cmp_choose_eye": "Een platform kiezen",
 "cmp_choose_h2": "Welk platform past het best bij jou?",
 "cmp_choose": [
  ("Kies voor Sport Endorse", "als je wilt samenwerken met geverifieerde professionele en elite-atleten, internationale campagnes wilt voeren, transparante prijzen belangrijk vindt en alles – van contracten en betalingen tot persoonlijke ondersteuning – op één platform wilt beheren."),
  ("Kies voor Opendorse", "als je een Amerikaanse universiteit, sportafdeling of NIL-collective bent met een focus op de Amerikaanse universiteitssport."),
  ("Kies voor OpenSponsorship", "als je op zoek bent naar uitbestede influencercampagnes op grote schaal binnen de sportwereld."),
  ("Kies voor Pickstar", "als je sporters, gastsprekers of publieke optredens wilt boeken, voornamelijk in Australië."),
 ],
 "cmp_faq_h2": "Veelgestelde vragen over de vergelijking",
 "cmp_faq": [
  ("Sport Endorse of OpenSponsorship: welk platform is beter voor merken?", "Dat hangt af van je campagne. OpenSponsorship is vooral geschikt voor grootschalige influencercampagnes via volledig beheerde maandabonnementen ($2.000–$5.000). Sport Endorse is dan weer de beste keuze voor merken die willen samenwerken met geverifieerde professionele en elite-atleten, met een sterke focus op Europees rugby, GAA, voetbal en olympisch talent. Dankzij transparante, marktgebaseerde abonnementen en rechtstreekse ondersteuning voor zowel merken als atleten biedt het platform een persoonlijke en flexibele aanpak."),
  ("Sport Endorse of Opendorse: wat is het verschil?", "Opendorse is ontwikkeld voor de Amerikaanse universiteitssport en focust op NIL-compliance voor meer dan 200 sportafdelingen. Het platform werkt met enterprise-abonnementen en rekent marketplacekosten aan die kunnen oplopen tot 30%. Sport Endorse is daarentegen een gestroomlijnd platform voor merken die willen samenwerken met geverifieerde professionele en elite-atleten uit Europa, aangevuld met Amerikaans talent. Je kiest uit voorspelbare, marktgebaseerde abonnementen met een transparante commissie van 14–18% of een volledig beheerde formule, zonder commissies van 30%."),
  ("Wat zijn de beste alternatieven voor OpenSponsorship?", "Voor merken die liever samenwerken met geverifieerde professionele en elite-atleten dan met influencers op grote schaal, is Sport Endorse het sterkste alternatief. Het platform biedt toegang tot meer dan 9.000 geverifieerde atleten in meer dan 280 sporten, met transparante marktgebaseerde prijzen, contracten en betalingen via het platform en een sterke vertegenwoordiging van de Britse, Ierse en Europese sportmarkt. Opendorse richt zich daarentegen op een andere niche: de Amerikaanse universiteitssport (NIL)."),
  ("Hoe verhouden de prijzen van Sport Endorse zich tot Opendorse en OpenSponsorship?", "Sport Endorse werkt met transparante, marktgebaseerde abonnementen die per regio worden geprijsd, aangevuld met een platformcommissie van 14–18% op samenwerkingen. De actuele tarieven vind je op onze prijspagina. Opendorse werkt met enterprise-abonnementen en rekent daarnaast een marketplace fee aan (volgens berichten tot ongeveer 30%). OpenSponsorship hanteert maandelijkse tarieven van $2.000 tot $5.000 voor zijn volledig beheerde abonnementen."),
  ("Is een athlete marketing platform beter dan een sportmarketingbureau?", "Voor de meeste campagnes wel. Een athlete marketing platform vervangt bureau-opslagen, lange responstijden en ondoorzichtige prijzen door directe toegang tot atleten, contracten via het platform en live rapportage. Voor complexe creatieve producties blijven sportmarketingbureaus echter een duidelijke meerwaarde bieden. Daarom biedt Sport Endorse ook een optionele full-serviceformule aan."),
 ],
 "cmp_demo_h2": "Ontdek het verschil tijdens een live demo",
 "cmp_demo_p": "We tonen je het platform aan de hand van echte briefings, echte atleten en echte campagnerapportage. Breng gerust je meest uitdagende campagne mee.",
 "cmp_demo_cta": "Demo boeken",
 "cmp_disclaimer": "Disclaimer: Productnamen, logo's en merken zijn eigendom van hun respectievelijke eigenaren en worden hier uitsluitend ter identificatie gebruikt; het gebruik ervan impliceert geen samenwerking met of goedkeuring door die bedrijven. Vergelijkingen zijn gebaseerd op publiek beschikbare informatie en gepubliceerde functielijsten en weerspiegelen onze eigen interpretatie — het aanbod van concurrenten verandert, dus details kunnen verouderd raken. Zie je een onjuistheid? Mail info@sportendorse.com en we passen het aan.",
 "ss_title": "Succesverhalen — Bewijs in de praktijk | Sport Endorse",
 "ss_desc": "Echte athlete marketing-campagnes voor merken zoals AIB, Pringles, Specsavers, Puma en Active Iron — met het merk, de atleet, de campagne en de resultaten.",
 "ss_eyebrow": "Succesverhalen",
 "ss_h1": "Bewijs in de <span>praktijk</span>",
 "ss_lead": "Sport Endorse realiseerde al meer dan 70 athlete marketing-campagnes voor merken zoals AIB, Pringles, Specsavers, BBC Sport, Puma, Active Iron en An Post. Van merkambassadeurs en socialmediacampagnes tot keynote speakers en multi-athlete programma's, verspreid over rugby, GAA, voetbal, atletiek en vele andere sporten. Hieronder vind je een selectie van onze case studies — telkens met het merk, de atleet, de campagne en, waar beschikbaar, de resultaten en feedback van de klant.",
 "ss_card_cta": "Lees de case study",
 "ss_all_cta": "Bekijk alle succesverhalen",
 "ss_final_h2": "Jouw campagne kan de volgende zijn.",
 "ss_final_p": "Vertel ons wat je wilt bereiken en we tonen je tijdens een korte demo de atleten, het volledige proces en de campagnerapportage.",
 "ss_final_cta": "Demo boeken",
}
