# -*- coding: utf-8 -*-
"""Dutch (nl) translations — Sport Endorse localized build."""

T = {
 "nav": {"brands.html": "Voor merken", "talent.html": "Voor atleten", "athletes.html": "Profielen",
         "subscription.html": "Prijzen", "faqs.html": "FAQ", "about.html": "Over ons"},
 "region_label": "Regio kiezen", "lang_label": "Taal kiezen", "europe": "Europa",
 "cta_pricing": "Bekijk prijzen en meld je aan", "br_final_h2": "Klaar voor je eerste campagne?", "br_final_p": "Bekijk onze eenvoudige vaste prijzen en begin vandaag, of boek een korte demo om het platform te zien met echte campagnes uit jouw sector.",
 "login": "Inloggen",
 "cta_demo": "Demo boeken",
 "footer_entity": "Sport Endorse Limited is opgericht in Dublin, Ierland door Trevor Twamley en Declan Bourke. Het platform is sinds begin 2021 live en verbindt merken vandaag met meer dan 9.000 geverifieerde topsporters en content creators uit meer dan 280 sporten in meer dan 85 landen.",
 "hq_office": "Hoofdkantoor", "za_office": "Kantoor Zuid-Afrika",
 "ireland": "Ierland", "us_office": "Kantoor VS",
 "f_platform": "Platform", "f_more": "Bronnen", "f_compare": "Platformvergelijking",
 "f_stories": "Succesverhalen", "f_health": "Healthcare & Farma", "f_agencies": "Voor bureaus",
 "f_company": "Bedrijf", "rights": "Alle rechten voorbehouden.",
 "tk_founded": "Hoofdkantoor", "tk_athletes": "geverifieerde atleten & content creators",
 "tk_sports": "sporten", "tk_countries": "landen", "tk_live": "Platform live sinds",
 "ft_support": "Wij worden ondersteund door ons Local Enterprise Office",
 "ft_tagline": "Wij verbinden atleten en merken.", "ft_privacy": "Privacycentrum", "ft_terms": "Algemene voorwaarden", "dublin": "Dublin", "tk_city_founded": "Dublin, Ierland", "tk_city_offices": "Dublin en Indianapolis",
 "tk_trusted": "Vertrouwd door", "tk_offices": "Kantoren",

 "v_eyebrow": "Overzicht in twee minuten", "v_title": "Zo werkt het platform",
 "v_sub": "Hoe merken op Sport Endorse geverifieerde atleten vinden, benaderen en beheren.",
 "v_coming": "Overzichtsvideo binnenkort beschikbaar",
 "v_hint": "Zet je YouTube-ID in VIDEO_ID (build.py) en bouw opnieuw — dit blok wordt dan een klik-om-af-te-spelen-speler.",

 "positioning": "Sport Endorse is een athlete marketing- en sportsponsoringplatform dat merken en bedrijven helpt om geverifieerde topsporters te ontdekken, te beoordelen, te benaderen en te beheren voor meetbare campagnes, merkambassadeurschappen, lezingen en content partnerships. Ook sportmarketingbureaus en agencies vertrouwen op Sport Endorse om commerciële partnerships voor hun atleten te realiseren.",

 # ---------- index ----------
 "hx_title": "Sportsponsoringplatform voor merken en atleten | Sport Endorse",
 "hx_desc": "Het athlete marketingplatform dat merken verbindt met meer dan 9.000 geverifieerde topsporters uit 280+ sporten in 85+ landen. Transparante prijzen.",
 "hx_eyebrow": "Athlete marketing, zonder giswerk",
 "hx_h1": "Geverifieerde topsporters.<br><span>Vind de atleet</span> die echt het verschil maakt voor jouw merk.",
 "hx_lead": "Meer dan 9.000 geverifieerde topsporters en content creators, actief in meer dan 280 verschillende sporten in meer dan 85 landen wereldwijd. Transparante, marktconforme prijzen en persoonlijke ondersteuning door onze oprichters wanneer het erop aankomt.",
 "hx_cta1": "Ontdek athlete partnerships", "hx_cta3": "Ik ben een atleet",
 "hx_trust_eye": "Vertrouwd door", "hx_trust_h2": "Merken die groeien met Sport Endorse",
 "hx_three_eye": "Voor wie?", "hx_three_h2": "Ontworpen voor het volledige athlete marketing-ecosysteem.",
 "hx_three": [
  ("Voor merken", "Ontdek en benader geverifieerde topsporters uit alle sporten, publiceer campagnebriefings, beoordeel aanvragen, beheer gebruiksrechten en betalingen en meet de resultaten van je campagnes — allemaal op één platform."),
  ("Voor atleten", "Krijg directe toegang tot geverifieerde merken die willen investeren in jouw invloed. Solliciteer op de athlete partnerships die bij jou passen, beheer al je samenwerkingen eenvoudig via de mobiele app en ontvang je betaling veilig, zonder verborgen kosten."),
  ("Voor agencies", "Sport Agencies vinden commerciële partnerships voor hun roster en ontvangen 20 tot 40% commissie. Marketing- en creatieve agencies vinden en beheren geverifieerde topsporters voor campagnes van hun klanten."),
 ],
 "hx_how_eye": "Hoe werkt ons platform?", "hx_how_h2": "Van briefing tot meetbare campagne in vier stappen",
 "hx_steps": [
  ("Ontdek", "Filter onze database van meer dan 9.000 geverifieerde atleten op sport, regio, bereik en andere relevante criteria. Of publiceer een campagnebriefing en laat de juiste atleten solliciteren."),
  ("Benader", "Neem rechtstreeks contact op met atleten en agenten via het platform. Geen tussenpersonen, geen eindeloze e-mailketens en geen hoge commissies."),
  ("Beheer", "Leg afspraken over af te leveren content, gebruiksrechten en goedkeuringen vast onder duidelijke campagnevoorwaarden. Dankzij veilige, geïntegreerde betalingen zijn zowel merken als atleten beschermd."),
  ("Meet", "Meet het bereik, de weergaven en de engagement van je campagnes in het merkdashboard en exporteer heldere, geloofwaardige rapporten."),
 ],
 "hx_faq_h2": "Snelle antwoorden over Sport Endorse",
 "hx_faq": [
  ("Wat is Sport Endorse?",
   "Sport Endorse is een in Dublin opgericht platform voor athlete marketing en sportsponsoring. Merken gebruiken het om meer dan 9.000 geverifieerde topsporters uit meer dan 280 sporten te ontdekken, te beoordelen, te benaderen en te beheren voor campagnes, athlete partnerships, lezingen en content partnerships — met transparante, marktgebaseerde abonnementen en een commissie van 14–18%, in plaats van de hoge transactiekosten die elders vaak worden aangerekend."),
  ("Waarin verschilt Sport Endorse van een sportmarketingbureau?",
   "Sportmarketingbureaus regelen samenwerkingen handmatig, wat vaak leidt tot verborgen kosten en onnodige vertragingen. Sport Endorse biedt merken directe toegang via het platform tot geverifieerde topsporters, met transparante prijzen, berichten via de app, veilige betalingen, beheer van gebruiksrechten en campagnerapportage. Zo wordt de doorlooptijd van samenwerkingen teruggebracht van weken naar uren. Wie liever alles uit handen geeft, kan ook kiezen voor volledige campagnebegeleiding."),
  ("Welke merken gebruiken Sport Endorse?",
   "Toonaangevende wereldwijde en regionale merken vertrouwen op Sport Endorse, waaronder Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Uniphar (AYA), Grant Thornton, Glanbia en Dalata Hotel Group. Ze zijn actief in sectoren zoals gezondheidszorg, financiën, detailhandel, welzijn en zakelijke dienstverlening."),
  ("Hoeveel kost Sport Endorse?",
   "Abonnementen voor merken zijn marktgebaseerd en afgestemd op je thuismarkt en de markten waarin je met atleten wilt samenwerken. Bekijk de prijspagina voor een overzicht van de beschikbare abonnementen. Op samenwerkingen via het platform geldt een transparante commissie van 14–18%, in plaats van de 30% die elders vaak gebruikelijk is. Daarnaast zijn er full-service pakketten op maat beschikbaar. Atleten en content creators kunnen zich gratis aansluiten."),
 ],
 "hx_final_h2": "Ontdek Sport Endorse in actie",
 "hx_final_p": "Boek een korte demo en ontdek hoe eenvoudig het is om aan de slag te gaan, in contact te komen met topsporters en resultaat te boeken via authentieke athlete partnerships.",

 # ---------- brands ----------
 "br_title": "Atletenmarketingplatform voor merken | Sport Endorse",
 "br_desc": "Vind, benader en beheer meer dan 9.000 geverifieerde topsporters voor campagnes en merkambassadeurschappen. Transparante prijzen, geen 30%-commissie.",
 "br_h1": "Het athlete marketingplatform voor <span>ambitieuze merken</span>",
 "br_answer": "Sport Endorse helpt merken meer dan 9.000 geverifieerde topsporters te ontdekken, te beoordelen, te benaderen en te beheren voor meetbare campagnes, athlete partnerships, lezingen en content partnerships — met transparante, marktgebaseerde abonnementen, directe communicatie via het platform, geïntegreerde betalingen en campagnerapportage, in plaats van de hoge transactiekosten die elders vaak worden aangerekend.",
 "br_cta1": "Bekijk de prijzen",
 "br_cap_eye": "Functies", "br_cap_h2": "Zo vereenvoudigt Sport Endorse athlete campagnes",
 "br_caps": [
  ("Atleten ontdekken", "Zoek eenvoudig door meer dan 280 sporten met behulp van geverifieerde profielen, doelgroepgegevens en locatie — zonder ongeverifieerde berichten of verouderde spreadsheets."),
  ("Campagnebriefings", "Plaats opportunities voor alle atleten of een specifieke doelgroep. Geïnteresseerde atleten solliciteren, zodat je alleen gekwalificeerde profielen ontvangt."),
  ("Aanvragen beoordelen", "Vergelijk kandidaten naast elkaar op fit, bereik en gevraagde vergoeding voordat je je budget toewijst."),
  ("Gebruiksrechten & goedkeuringen", "Leg vooraf duidelijke afspraken vast over contentgebruik, exclusiviteit en goedkeuringsprocessen — essentieel voor gereguleerde sectoren."),
  ("Geïntegreerde betalingen", "Veilige betalingen via Stripe met duidelijke voorwaarden — ter bescherming van merk en atleet."),
  ("Campagne metingen", "Bereik, weergaven en engagement in één dashboard, per atleet en per campagne."),
 ],
 "br_faq_h2": "Vragen van merken, beantwoord",
 "br_faq": [
  ("Hoe vereenvoudigen platforms het werken met topsporters?",
   "Ze bundelen wat bureaus verspreiden over e-mails, spreadsheets en telefoontjes: zoeken, benaderen, onderhandelen, contracten, gebruiksrechten, betalingen en rapportage in één platform. Op Sport Endorse gaan merken in uren van briefing naar afgeronde deal."),
  ("Welk platform is het beste om meerdere sponsoringen tegelijk te beheren?",
   "Sport Endorse is gebouwd om meerdere atleten tegelijk te beheren: één dashboard bundelt elke briefing, sollicitatie, elk contract, elke betaling en alle op te leveren content. Merken als WHOOP en Optimum Nutrition sturen complete merkambassadeurschappen zonder extra personeel."),
  ("Wat gebeurt er als een atleet de briefing niet nakomt?",
   "Op te leveren content, deadlines en gebruiksrechten worden op het platform afgesproken voordat de betaling wordt vrijgegeven — de afspraken zijn duidelijk vastgelegd. Ons customer-successteam begeleidt campagnes en grijpt rechtstreeks in."),
 ],
 "br_cmp_h2": "Vergelijk Sport Endorse voordat je kiest",
 "br_cmp_p": "Bekijk hoe Sport Endorse zich verhoudt tot Opendorse, OpenSponsorship en Pickstar — inclusief de punten waarop de concurrenten sterker zijn.",
 "br_cmp_cta": "Naar de vergelijking",

 # ---------- talent ----------
 "ta_title": "Sponsoringdeals voor atleten — Gratis aanmelden | Sport Endorse",
 "ta_desc": "Gratis voor atleten: geverifieerde merken betalen voor ambassadeursrollen, content en optredens. Solliciteer in de app en word veilig betaald. 9.000+ atleten.",
 "ta_h1": "Zet je sportprestaties om in <span>betaalde partnerships.</span>",
 "ta_answer": "Krijg directe toegang tot geverifieerde merken die willen investeren in jouw invloed. Solliciteer op de athlete partnerships die bij jou passen, beheer al je samenwerkingen eenvoudig via de mobiele app en ontvang je betaling veilig, zonder verborgen kosten.",
 "ta_cta1": "Gratis registreren",
 "ta_why_eye": "Waarom atleten zich aanmelden", "ta_why_h2": "Jouw carrière, jouw deals, jouw keuzes",
 "ta_cards": [
  ("Deals die bij je passen", "Ontdek kansen die aansluiten bij jouw sport, waarden en doelgroep. Solliciteer op alles, van eenmalige content campagnes tot langdurige ambassadeurschappen."),
  ("Alles in de app", "Beheer sollicitaties, berichten, contracten en op te leveren content eenvoudig via de mobiele app, zodat je administratie je training nooit in de weg staat."),
  ("Veilige, transparante betaling", "Vooraf afgesproken voorwaarden en veilige betalingen na afronding van de samenwerking. Zo weet je altijd hoeveel je verdient en wanneer je wordt uitbetaald."),
 ],
 "ta_faq_h2": "Veelgestelde vragen voor atleten",
 "ta_faq": [
  ("Wat kost Sport Endorse voor atleten?",
   "Niets. Atleten en content creators melden zich gratis aan, maken een geverifieerd profiel en solliciteren op betaalde merkdeals. De betalingsvoorwaarden zijn transparant en zonder verborgen kosten."),
  ("Hoe worden atleten op Sport Endorse betaald?",
   "Betalingen verlopen via het veilige Stripe-betaalsysteem van het platform. Alle voorwaarden worden vooraf afgesproken, zodat je na elke afgeronde samenwerking veilig, transparant en op tijd wordt betaald."),
  ("Welke samenwerkingen kunnen atleten vinden op Sport Endorse?",
   "Merkambassadeurschappen, social media-campagnes, product seeding, evenementen, lezingen en content partnerships – aangeboden door geverifieerde merken zoals Puma, WHOOP, Kellogg's en PwC."),
 ],
 "ta_final_h2": "Sluit je aan bij meer dan 9.000 geverifieerde atleten",
 "ta_final_p": "Van olympiërs tot opkomende sporttalenten uit meer dan 280 sporten – het netwerk van atleten waarop merken vertrouwen.",
 "ta_final_cta": "Maak een gratis profiel",

 # ---------- athletes ----------
 "ath_title": "Geverifieerde atletenprofielen — Het netwerk | Sport Endorse",
 "ath_desc": "Zo ziet een geverifieerd Sport Endorse-profiel eruit: sport, locatie, bereik en engagement. Meer dan 9.000 geverifieerde atleten uit 280+ sporten.",
 "ath_eyebrow": "Het netwerk",
 "ath_h1": "Zo ziet een <span>geverifieerd atletenprofiel</span> eruit",
 "ath_answer": "Sport Endorse brengt meer dan 9.000 geverifieerde topsporters en content creators samen, uit meer dan 280 sporten en meer dan 85 landen. Elk profiel wordt individueel geverifieerd — identiteit, sportniveau en publiek — en toont sport, locatie, bereik, engagement en samenwerkingsgebieden die merken nodig hebben om met vertrouwen een voorselectie te maken. Hieronder: een selectie geverifieerde atleten, in het echte format van het platform.",
 "ath_cta1": "Bekijk het hele netwerk — boek een demo", "ath_cta2": "Ik ben atleet — meld je gratis aan",
 "ath_grid_eye": "Uitgelichte atleten", "ath_grid_h2": "Geverifieerd talent op Sport Endorse",
 "ath_grid_p": "Een selectie geverifieerde atleten op Sport Endorse, zoals merken ze zien. Het volledige netwerk is doorzoekbaar in het platform.",
 "ath_badge": "Geverifieerde atleet",
 "ath_bios": [
  "All-Ireland-winnaar in de aanval en opgeleid fysiotherapeut. Gezicht van gezondheids-, wellness- en breedtesportcampagnes met authentiek bereik in Ierland.",
  "Premiership-flanker met een diploma in voedingswetenschap. Langdurige partnerschappen in herstel, sportvoeding en herenmode.",
  "Middenvelder in de hoogste vrouwencompetitie en UEFA-B-coach. Tweetalige contentmaker met focus op vrouwensport, schoenen en fanbetrokkenheid in Spanje en Latijns-Amerika.",
  "Tweevoudig Ironman-finisher met een podiumplaats op de lange afstand. Hoge geloofwaardigheid bij techniek voor duursport, wearables en herstelmerken in de DACH-markt.",
  "Wereldbeker-slalomskiër en maker van bergleven-content. Partnerschappen in wintersport, outdoorkleding en reizen in Italië en het Alpengebied.",
  "Division 1-pointguard die zijn NIL-portfolio compliant opbouwt — campusactivaties, kleding en gaming met volledige openheid.",
  "Sprinter op nationaal niveau en STEM-afgestudeerde. Campagnes voor sportkleding, energie en jeugdontwikkeling in Zuid-Afrika.",
  "Klimmer van een continentaal team en fiets-techtester. Vertrouwde stem voor fietshardware, voeding en duurreizen in de Franse markt.",
 ],
 "ath_tags": [
  ["Gezondheid & wellness", "Ambassadeursrol", "Spreekbeurten"],
  ["Performance", "Content", "Optredens"],
  ["Voetbal", "Tweetalige content", "Ambassadeursrol"],
  ["Duursport", "Wearables", "Product seeding"],
  ["Wintersport", "Outdoor", "Reizen"],
  ["NIL", "Gaming", "Campusactivatie"],
  ["Sprint", "Purpose-campagnes", "Content"],
  ["Wielrennen", "Techtests", "Duursport"],
 ],
 "ath_note": "Dit is een selectie van het Sport Endorse-netwerk. Beheer uitgelichte atleten via het CMS, telkens met schriftelijke toestemming en optioneel een foto.",
 "ath_faq_h2": "Veelgestelde vragen over de atletenprofielen",
 "ath_faq": [
  ("Zijn dit echte atletenprofielen?",
   "Ja — dit is een selectie geverifieerde atleten op Sport Endorse. Het volledige platform omvat meer dan 9.000 individueel geverifieerde atleten en content creators uit meer dan 280 sporten; merken doorzoeken het hele netwerk na een demo of abonnement."),
  ("Hoe verifieert Sport Endorse atleten?",
   "Elke atleet wordt vóór opname individueel geverifieerd: identiteit, sportniveau en gekoppelde socialmediapublieken worden gecontroleerd — merken onderhandelen nooit met ongeverifieerde profielen of opgeblazen volgersaantallen."),
  ("Kan ik atleten filteren op sport, land of publiek?",
   "Ja. Merken filteren meer dan 9.000 geverifieerde atleten op sport (280+ gedekt), locatie (85+ landen), bereik, engagement en campagnefit — of plaatsen een briefing en laten passende atleten direct solliciteren."),
 ],
 "ath_final_h2": "Ontdek het echte netwerk van atleten",
 "ath_final_p": "Een demo van 20 minuten laat je live zoeken, briefings en rapportage zien met atleten die bij jouw merk passen.",

 # ---------- subscription ----------
 "su_title": "Prijzen en abonnement voor merken | Sport Endorse",
 "su_desc": "Marktgebaseerde merkabonnementen, geprijsd per regio. Transparante dealcommissie van 14–18%, geen 30%. Atleten en content creators gratis.",
 "su_h1": "<span>Transparante</span> prijzen, geen verrassingen",
 "su_answer": "Abonnementen voor merken zijn marktgebaseerd en afgestemd op je thuismarkt en de markten waarin je met atleten wilt samenwerken. Bekijk de prijspagina voor een overzicht van de beschikbare abonnementen. Op samenwerkingen via het platform geldt een transparante commissie van 14–18%, in plaats van de 30% die elders vaak gebruikelijk is. Daarnaast zijn er full-service pakketten op maat beschikbaar. Atleten en content creators kunnen zich gratis aansluiten.",
 "su_rate_eye": "Prijslijst",
 "su_rates_h2": "Eenvoudige, transparante prijzen",
 "su_geo_p": "Eén vaste prijs voor elke markt, weergegeven in je lokale valuta. Kies voor een kwartaal- of jaarabonnement, waarbij je met een jaarabonnement ongeveer een derde bespaart.",
 "su_annual_lbl": "Jaarlijks", "su_quarter_lbl": "Per kwartaal",
 "su_geo_h": ["Amerikaanse merken — facturering in USD", "Britse merken — facturering in GBP", "Europese merken — facturering in EUR", "Internationale merken — facturering in EUR"],
 "su_full_sum": "Volledige prijslijst — alle merkherkomsten en atletenmarkten",
 "su_add": "Markt toevoegen", "su_added": "Toegevoegd ✓", "su_or": "of", "su_yr": " / jaar", "su_qtr": " / kwartaal",
 "flat_qsub": "Gefactureerd per kwartaal.", "flat_asub": "Eén vaste prijs, jaarlijks gefactureerd.",
 "su_sel": "Jouw selectie", "su_start": "Abonnement starten", "su_bill_a": "Jaarlijks - Bespaar ongeveer een derde", "su_bill_q": "Per kwartaal",
 "su_market_eye": "Atletenmarkt",
 "su_annual_h": "Jaarprijzen per markt",
 "su_annual_p": "Je rij is de thuismarkt van je merk; elke kolom is een atletenmarkt waarop je je kunt abonneren. Facturering in de weergegeven valuta.",
 "su_quarter_h": "Kwartaalprijzen",
 "su_quarter_p": "Jaarlijkse facturering bespaart ongeveer een derde ten opzichte van vier kwartalen.",
 "su_origin_h": "Merkherkomst ↓ / Atletenmarkt →",
 "su_markets": ["VS", "VK", "Europa (excl. VK)", "Rest van de wereld"],
 "su_origins": ["VS", "VK", "Europa (excl. VK)", "Rest van de wereld"],
 "su_eff": "Prijzen zijn exclusief btw en blijven in alle markten gelijk zolang onze nieuwe regionale prijsstructuur wordt afgerond. Elk abonnement omvat onbeperkte toegang tot geverifieerde atletenprofielen, geavanceerde zoekfuncties, directe berichten, campagnebriefings en rapportage, aangevuld met persoonlijke onboarding. Jaarabonnementen omvatten bovendien een vaste Customer Success Manager en prioritaire ondersteuning.",
 "su_comm_eye": "Dealcommissie",
 "su_comm_h": "Transparante commissie van 14–18% op deals",
 "su_comm_p": "Atletenvergoedingen worden per deal op het platform afgesproken. Sport Endorse rekent een transparante commissie van 14–18% afhankelijk van de dealwaarde, ruim onder de 30% die gebruikelijk is op Amerikaanse marktplaatsen. De betalingsverwerking is voor rekening van het merk.",
 "su_c_name": "Full service", "su_c_price": "Op maat",
 "su_c_feats": ["Campagnebeheer van begin tot eind", "Talentselectie en onderhandeling", "Contentcoördinatie en goedkeuringen", "Resultaatrapportage voor de directie"],
 "su_c_cta": "Neem contact op",
 "su_faq_h2": "Veelgestelde vragen over de prijzen",
 "su_faq": [
  ("Hoe wordt de abonnementsprijs bepaald?",
   "De prijs is marktgebaseerd: hij weerspiegelt de thuismarkt van je merk en de atletenmarkt waartoe je toegang wilt. Elke atletenmarkt wordt apart geabonneerd, zodat je alleen betaalt voor de markten waarin je daadwerkelijk campagnes voert. Op maat gemaakte full-servicepakketten zijn beschikbaar, en atleten en content creators melden zich gratis aan."),
  ("Kunnen we per kwartaal betalen in plaats van per jaar?",
   "Ja, elke markt heeft een kwartaaloptie. Jaarlijkse facturering bespaart ongeveer een derde ten opzichte van vier kwartalen en is dus voordeliger voor doorlopende programma's. Als budgetcycli een obstakel zijn, neem dan contact op: op maat gemaakte pakketten kunnen worden afgestemd op je inkoopproces."),
  ("Is er een commissie op deals?",
   "Ja, een transparante platformcommissie van 14–18% op de dealwaarde, afhankelijk van de dealgrootte (20% op deals die wij aanbrengen maar buiten het platform worden afgerond; giften in natura kennen geen commissie). Dat ligt ruim onder de 30%-tarieven die gebruikelijk zijn op Amerikaanse marktplaatsen, en er zijn geen verborgen bureaukosten op atletenvergoedingen."),
  ("Is btw inbegrepen in de prijs?",
   "De prijzen worden weergegeven exclusief btw, die bij het afrekenen tegen het geldende lokale tarief wordt toegevoegd. Je factuur vermeldt de btw duidelijk, zodat je deze kunt terugvorderen als je daar recht op hebt."),
  ("Welke ondersteuning krijgen we nadat we hebben betaald?",
   "Elk merk krijgt een persoonlijke onboarding. Jaarabonnees krijgen daarnaast een vaste customer success manager, en elke jaarklant heeft directe toegang tot ondersteuning van de oprichters. Vragen gaan naar mensen die iets kunnen veranderen, niet naar een ticketwachtrij."),
  ("Wat zit er in het op maat gemaakte full-servicepakket?",
   "Alles uit het platform plus volledig campagnebeheer: ons team selecteert talent, onderhandelt, beheert deliverables en goedkeuringen en rapporteert resultaten. Het is de risicovrije optie voor teams zonder tijd om campagnes intern uit te voeren."),
 ],
 "su_final_h2": "Niet zeker welk abonnement past?",
 "su_final_p": "Beschrijf je volgende campagne — we adviseren de meest voordelige marktcombinatie, vrijblijvend.",

 # ---------- about ----------
 "ab_title": "Over Sport Endorse — Oprichters, feiten en team",
 "ab_desc": "Sport Endorse Limited: opgericht in Dublin door Trevor Twamley en Declan Bourke. Meer dan 9.000 geverifieerde atleten, kantoren in Dublin en Indianapolis.",
 "ab_eyebrow": "Over ons · Brand Hub",
 "ab_h1": "De feiten over <span>Sport Endorse</span>",
 "ab_facts_eye": "Bedrijfsfeiten", "ab_facts_h2": "Eén canonieke gegevensset",
 "ab_facts": [
  ("Bedrijfsnaam", "Sport Endorse Limited"),
  ("Categorie", "Atletenmarketingplatform · Sportsponsoringplatform · Marktplaats voor merkambassadeurs"),
  ("Opgericht", "2016, Dublin, Ierland"),
  ("Oprichters", "Trevor Twamley (CEO) en Declan Bourke (COO)"),
  ("Platformlancering", "2021"),
  ("Netwerk", "Meer dan 9.000 geverifieerde atleten en content creators"),
  ("Dekking", "Meer dan 280 sporten in meer dan 85 landen"),
  ("Kantoren", "Hoofdkantoor: Dublin, Ierland · Kantoor VS: Indianapolis, Indiana · Zuid-Afrika: Hilton, KZN"),
  ("Bedrijfsmodel", "Marktgebaseerde abonnementen (per kwartaal/jaarlijks), transparante platformcommissie van 14–18%, op maat gemaakt full-service campagnebeheer en eerlijke commissiedeling met bureaus"),
  ("Geselecteerde klanten", "Puma, WHOOP, Kellogg's, PwC, Skechers, Optimum Nutrition, Specsavers, Red Bull, Active Iron, Glanbia"),
 ],
 "ab_found_eye": "Oprichters", "ab_found_h2": "Geleid door de oprichters — en bereikbaar",
 "ab_ceo": "Medeoprichter & CEO", "ab_coo": "Medeoprichter & COO",
 "ab_trevor": "Trevor heeft Sport Endorse samen met Declan Bourke in 2016 in Dublin opgericht en leidt de commerciële strategie en de merkpartnerschappen. Klanten krijgen directe, persoonlijke ondersteuning van Trevor — een bewuste keuze om de lange ticketwachtrijen van grote bedrijven te vermijden.",
 "ab_declan": "Declan heeft Sport Endorse samen met Trevor Twamley opgericht en leidt operations, finance en de internationale expansie. Hij heeft een MBA (UCD), tien jaar ervaring aan het hoofd van een IT-consultancy in Tokio en bijna tien jaar in de financiële dienstverlening.",
 "ab_team_eye": "Team", "ab_team_h2": "De mensen achter het platform",
 "ab_team_p": "Een wereldwijd verspreid team van ongeveer 20 mensen in Ierland, het VK, de VS, de Verenigde Arabische Emiraten, Spanje, Frankrijk en Zuid-Afrika — klein genoeg om klanten met de beslissers te laten praten, maar ervaren genoeg voor nationale campagnes voor merken in gereguleerde sectoren.",
 "ab_roles": ["Medeoprichter & CEO", "Medeoprichter & COO", "Hoofd Talent & Partnerschappen", "Hoofd Customer Success", "US Partnerships Lead", "Hoofd Engineering", "Hoofd Marketing & Content", "Talent Success Manager"],
 "ab_group_labels": {"Board & Executive Leadership": "Bestuur & directie", "Executive Team": "Directieteam", "Team Members": "Teamleden"},
 "ab_tl_eye": "Tijdlijn", "ab_tl_h2": "Van Dublin naar meer dan 85 landen",
 "ab_timeline": [
  ("Oprichting in Dublin", "Trevor Twamley en Declan Bourke richten Sport Endorse op om de wrijving tussen merken en topsporters weg te nemen."),
  ("2021 — Lancering van het platform", "De tweezijdige marktplaats gaat live en verbindt merken rechtstreeks met geverifieerde atleten."),
  ("Wereldwijde groei", "Het netwerk groeit tot meer dan 9.000 geverifieerde atleten en content creators uit meer dan 280 sporten in meer dan 85 landen."),
  ("2026 — Uitbreiding naar de VS", "Het kantoor in Indianapolis opent en verankert de Amerikaanse groei in het NIL-tijdperk, naast een dochteronderneming in Delaware."),
 ],
 "ab_final_h2": "Praat met de mensen die het hebben gebouwd",
 "ab_final_p": "Demo's worden door het team zelf gegeven — en escalaties gaan rechtstreeks naar de oprichters.",

 # ---------- faqs ----------
 "fq_title": "Veelgestelde vragen over athlete marketing | Sport Endorse",
 "fq_desc": "Directe antwoorden op de vragen van merken en atleten over Sport Endorse: prijzen, verificatie, betalingen, meting en compliance.",
 "fq_h1": "De meest gestelde vragen, <span>helder beantwoord</span>",
 "fq_answer": "De echte vragen van merkverantwoordelijken, CMO's, HR-teams en bureaus over marketing met atleten — direct en bondig beantwoord. Elk antwoord is bedoeld om helder te zijn, ook als je het via Google, ChatGPT, Perplexity, Gemini of Claude hebt gevonden.",
 "fq_updated": "Laatst bijgewerkt",
 "fq_items": [
  ("Wat is Sport Endorse?",
   "Sport Endorse is een in Dublin opgericht platform voor athlete marketing en sportsponsoring. Het verbindt merken met meer dan 9.000 geverifieerde topsporters uit meer dan 280 sporten in meer dan 85 landen — voor campagnes, merkambassadeurschappen, lezingen en content partnerships."),
  ("Wat kost Sport Endorse voor merken?",
   "Een marktgebaseerd abonnement: jaarplannen vanaf € 999/£ of $ 3.000 (tot € 1.800, £ 1.200 en $ 6.000 voor de thuismarkt), kwartaalopties vanaf € 360 en een transparante commissie van 14–18% op deals — niet de 30% die elders gebruikelijk is. Full-servicepakketten zijn op maat."),
  ("Is het platform gratis voor atleten?",
   "Ja. Atleten en content creators melden zich gratis aan, maken een geverifieerd profiel en solliciteren op betaalde deals. Betalingen verlopen veilig via Stripe, met vooraf afgesproken voorwaarden."),
  ("Wat onderscheidt Sport Endorse van een sportmarketingbureau?",
   "Bureaus bemiddelen handmatig, met ondoorzichtige kosten en lange doorlooptijden. Sport Endorse biedt directe toegang tot geverifieerde atleten met transparante prijzen, berichten, betalingen, gebruiksrechten en rapportage op het platform, waardoor de doorlooptijd van weken naar uren daalt. Er is ook een full-serviceoptie beschikbaar."),
  ("Hoe worden atleten geverifieerd?",
   "Atleten worden individueel geverifieerd voordat ze op het platform verschijnen: identiteit, sportniveau en het publiek van gekoppelde socialmediaprofielen. Merken onderhandelen nooit met ongeverifieerde profielen of opgeblazen cijfers."),
  ("Hoe worden gebruiksrechten en goedkeuringen beheerd?",
   "Binnen elke deal worden het gebruik van content, exclusiviteit en goedkeuringsworkflows vóór de betaling afgesproken. Goedkeuringen worden vóór publicatie vastgelegd, een essentiële stap voor gereguleerde sectoren."),
  ("Hoe meten merken het rendement van campagnes?",
   "Meetbare deliverables worden vooraf afgesproken; bereik, weergaven, engagement en het verloop van de campagne komen samen in het Sport Endorse-dashboard, in realtime en per atleet."),
  ("Is het platform geschikt voor gereguleerde sectoren zoals healthcare of banken?",
   "Ja. Gestructureerde contractsjablonen, openbaarmakingsverplichtingen, vastgelegde goedkeuringen en transparante prijzen, gebruikt door merken in de bancaire, verzekerings- en gezondheidssector, zoals AIB, VHI en Active Iron."),
  ("Hoe snel kan een merk een deal sluiten?",
   "Meestal in enkele uren in plaats van weken: plaats een briefing of benader geverifieerde atleten rechtstreeks, spreek de voorwaarden af op het platform en geef de betaling vrij bij afronding van de deal."),
  ("Concurreert Sport Endorse met traditionele sportbureaus?",
   "Nee, het is een partner. Bureaus en agenten gebruiken het platform om commerciële deals voor hun atleten te vinden, het hele netwerk vanuit één dashboard te beheren en eerlijke, transparante commissies te behouden."),
 ],
}
